### ISSUE TITLE
Graph with multiple edges

### ISSUE THREAD

**Issue by amarradi** [gephi/gephi#1646] opened 2016-12-30 08:33 UTC
Hello together,

i've a table like this in the attachment.
[Test.txt](https://github.com/gephi/gephi/files/678436/Test.txt)

How can i get four edges between source 1 and target 2?

Thanks

**Comment by eduramiba** [comment] 2016-12-30 10:52
Hi, this should just work with import spreadsheet feature to edges table in Gephi 0.9.1+

**Comment by amarradi** [comment] 2017-01-02 13:00
Hi,
how have i to import this file, that i can see every edge?

**Comment by eduramiba** [comment] 2017-01-02 13:45
Hi,
At the moment Gephi will only graphically show one edge even if there are multiple edges with the same source and target. But you can see all edges' data in Data Laboratory.

**Comment by jbliesener** [comment] 2017-01-02 13:57
See #1480

**Comment by eduramiba** [comment] 2017-01-02 14:07
Right, closing as duplicate of #1480

**Comment by amarradi** [comment] 2017-01-02 14:07
@eduramiba that would be very nice, if we can see every edge between the nodes

**Closed by eduramiba** 2017-01-02 14:07 UTC
Labels: Spreadsheet, Visualization
