### ISSUE TITLE
Cannot find Java 1.8 or higher.

### ISSUE THREAD

**Issue by RBR66** [gephi/gephi#2209] opened 2020-08-27 12:21 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by RBR66** [comment] 2020-08-27 12:24
I have Java version 8 (buid 1.8.0), but when I try load Gephi, a error message "Cannot find Java 1.8 or higher" is popped up. I am using Windows 10 64 bits. Can someone help me?

**Comment by eduramiba** [comment] 2020-08-31 08:54
Hi, make sure Gephi is picking java 8 installation and not other, as you might have several java versions in your system.

To do that, edit the gephi.conf file and set `jdkhome` manually. Explained here: #2180 and #2074 for example

**Comment by eduramiba** [comment] 2020-08-31 08:55
Closing as duplicate of #2180

**Closed by eduramiba** 2020-08-31 08:55 UTC
