### ISSUE TITLE
Gephi does not show nodes in preview and Gephi does not export nodes, only edges.

### ISSUE THREAD

**Issue by RRKLRRKL** [gephi/gephi#1985] opened 2018-06-27 15:57 UTC
## Expected Behavior

Gephi does not show nodes in preview. Gephi does not export nodes in PDF and SVG.
The polygone plugin is not installed. So that can not be the problem. The Gephi renderer is just not able to render the nodes.

## Current Behavior

It is not possible to see nodes in preview. Nodes are not exported by Gephi.

## Possible Solution

Update Gephi with better code.

## Steps to Reproduce

1. Use preview
2. Try to export
3.
4.

## Context

It is useless to use Gephi if it is not able to export the graphs correctly.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: 

Mac OSX 10.13.5

**Comment by eduramiba** [comment] 2018-06-27 15:59
Can you attach a sample graph to reproduce?
Nodes renderer should work fine, make sure it's enabled in the 'Manage renderers' tab in preview.

**Comment by RRKLRRKL** [comment] 2018-07-04 08:31
I am sorry, but that is not possible because it contains patient information. 

I cannot use this software anymore because of two reasons:

1) Saved projects cannot be (re)opened by Gephi.
2) Nodes are not displayed: the export function does not work correctly.

These are "showstoppers" because these issues represent core functions of (the) software.

Kind regards,
R. Klont

**Comment by aldou** [comment] 2018-08-03 15:02
No nodes displayed is likely a duplicate of issue #1997 
Check the workaround explained over there.

**Comment by ManishS6** [comment] 2021-05-09 09:02
Running gephi as Administrator (Windows 10 20H) solved the issue for me. Everything was visible in preview then.

**Comment by mbastian** [comment] 2022-10-24 20:25
Hi, closing this issue as we don't have a way to reproduce it. Either there is an error log or we can get some file sample. Otherwise I don't see a chance to make progress here.

**Closed by mbastian** 2022-10-24 20:25 UTC
Labels: Preview, Can't reproduce
