### ISSUE TITLE
Modularity results in java.lang.NullPointerException

### ISSUE THREAD

**Issue by rmhorne** [gephi/gephi#1411] opened 2016-03-03 16:18 UTC
System Specs: Gephi .9.1 on OS X El Capitan (10.11.3) and java version 1.8.0_73

This problem seems to happen when data is brought in through an external .csv edge file that creates the nodes automatically, or for running Modularity on data for the first time. For Gephi projects from old versions where "Modularity Class" is already a column with pre-existing data this problem does not seem to occur.

When this error occurs the application also is unable to be closed, and requires a "force quit".

Here is the output:

java.lang.NullPointerException
	at org.gephi.statistics.plugin.Modularity$CommunityStructure.removeNodeFrom(Modularity.java:289)
	at org.gephi.statistics.plugin.Modularity$CommunityStructure.moveNodeTo(Modularity.java:342)
	at org.gephi.statistics.plugin.Modularity$CommunityStructure.access$300(Modularity.java:127)
	at org.gephi.statistics.plugin.Modularity.computeModularity(Modularity.java:507)
	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:467)
	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:456)
	at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:162)
	at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:149)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cdgoodwin** [comment] 2016-03-24 19:02
Do you have any duplicate edges in your CSV? I found one and deleted it in mine, then the modularity functioned normally again..

**Comment by eduramiba** [comment] 2016-04-01 12:39
Closing as duplicate of #1419

**Closed by eduramiba** 2016-04-01 12:39 UTC
