### ISSUE TITLE
Gephi never opens Mac OSX Yosemite 10.10.2

### ISSUE THREAD

**Issue by shaystrong** [gephi/gephi#1026] opened 2015-03-06 18:40 UTC
I've downloaded the gephi 0.8.2 beta dmg and opened it. (I've also tried dragging the application to my applications folder). My java is up to date. When I click on the gephi icon, it shows the loading image and then closes, with no error indication. Not sure what is preventing it from loading.

**Comment by jackiekazil** [comment] 2015-03-08 21:04
See if this helps: https://medium.com/coder-snorts/gephi-is-broken-on-mac-os-97fbaef4305e

**Comment by eduramiba** [comment] 2015-08-26 16:49
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:49 UTC
