### ISSUE TITLE
Installation problem on MacOS X Yosemite

### ISSUE THREAD

**Issue by D-rabbit** [gephi/gephi#978] opened 2014-11-22 22:32 UTC
No problem downloading it. But can't open it to install. It turned to "Loading cached objects" and quitted itself without any explanation or alert.

**Comment by joel1di1** [comment] 2015-01-16 16:17
Same problem.
Here is my log

-------------------------------------------------------------------------------
>Log Session: Friday, January 16, 2015 5:13:53 PM CET
>System Info: 
  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Mac OS X version 10.10.1 running on x86_64
  Java; VM; Vendor        = 1.8.0_25; Java HotSpot(TM) 64-Bit Server VM 25.25-b02; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_25-b17
  Java Home               = /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /Users/joel1di1
  Current Directory       = /
  User Directory          = /Users/joel1di1/Library/Application Support/gephi/0.8.2/dev
  Cache Directory         = /Users/joel1di1/Library/Application Support/gephi/0.8.2/dev/var/cache
  Installation            = /Applications/Gephi.app/Contents/Resources/gephi/gephi
                            /Applications/Gephi.app/Contents/Resources/gephi/platform
                            /Applications/Gephi.app/Contents/Resources/gephi/platform
  Boot & Ext. Classpath   = /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/classes:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/System/Library/Java/Extensions/AppleScriptEngine.jar:/System/Library/Java/Extensions/dns_sd.jar:/System/Library/Java/Extensions/j3daudio.jar:/System/Library/Java/Extensions/j3dcore.jar:/System/Library/Java/Extensions/j3dutils.jar:/System/Library/Java/Extensions/jai_codec.jar:/System/Library/Java/Extensions/jai_core.jar:/System/Library/Java/Extensions/mlibwrapper_jai.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/System/Library/Java/Extensions/vecmath.jar
  Application Classpath   = /Applications/Gephi.app/Contents/Resources/gephi/platform/lib/boot.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-modules.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util-lookup.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_zh_TW.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/tools.jar
Startup Classpath       = /Applications/Gephi.app/Contents/Resources/gephi/platform/core/core.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/org-openide-filesystems.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/Applications/Gephi.app/Contents/MacOS/../Resources/gephi/bin/../gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
java.lang.IllegalStateException: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:423)
	at org.openide.util.WeakListenerImpl.create(WeakListenerImpl.java:164)
	at org.openide.util.WeakListeners.create(WeakListeners.java:271)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:125)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:142)
	at org.openide.filesystems.MultiFileSystem.getMultiRoot(MultiFileSystem.java:267)
	at org.openide.filesystems.MultiFileSystem.findResource(MultiFileSystem.java:355)
	at org.openide.filesystems.FileUtil.getConfigFile(FileUtil.java:2276)
	at org.openide.filesystems.FileUtil.getConfigRoot(FileUtil.java:2306)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:158)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:398)
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:413)
	... 12 more

**Comment by psychemedia** [comment] 2015-01-17 01:07
I've just successfully got Gephi working with an old version of java (1.6) - http://support.apple.com/kb/DL1572 

I didn't try 1.7; but it failed for me on 1.8.

**Comment by eduramiba** [comment] 2015-08-26 15:58
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:58 UTC
