### ISSUE TITLE
Serious Problem with Mac OS 10.10.3

### ISSUE THREAD

**Issue by maestrocorona** [gephi/gephi#1073] opened 2015-07-01 01:34 UTC
HI:

With the last beta version 0.8.2 I find several problems. the screen of the display never load, all the menus are present in the top bar but when I try to display are emty.

I clean the java, install the patch of mac by work with java version 7, but I have the same problem

**Comment by kungfujam** [comment] 2015-07-06 14:26
Hey,

I'm on mac 10.10 (Yosemite). To get it working you need to download Java 1.6 and link gephi to it via it's configuration file. These instructions worked perfectly for me. http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/ (the blog references Mavericks, but I'm on Yosemite and it worked fine).

**Comment by eduramiba** [comment] 2015-08-26 15:53
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:53 UTC
