### ISSUE TITLE
No appearance window in Gephi 0.9.2

### ISSUE THREAD

**Issue by susae** [gephi/gephi#1882] opened 2017-12-22 00:26 UTC
## Expected Behavior
There should be an appearance window in the overview section that allows to change node size and colours. 

## Current Behavior
I just cannot manage to anyhow open the appearance window in the overview section, it is nowhere to be found

## Steps to Reproduce

1. Imported nodes and edges table in CSV format to gephi 
2.
3.
4.

## Context

I am trying to set the node size by attribute, attributes were imported with the node table. However, I don't get top even open the appearance window. 
I am very sorry if this is a stupid beginner's question, but I cannot find it since hours and I am slowly starting to be desperate. Help would be SO appreciated 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Version 8 Update 152
* Operating System: Windows 10 Home

**Comment by eduramiba** [comment] 2017-12-22 09:16
Hi,
Can you show an screenshot? Make sure you didn't close the window and try to open it again in Window menu

**Comment by susae** [comment] 2017-12-28 13:55
Hey, 
I worked around the problem in the following way: 

I opend LesMiserables sample
I deleted nodes & edges
I imported my own files 
-> the appearance window was there.

**Comment by hugoguercio** [comment] 2018-07-09 03:36
@eduramiba 
I was stuck into this, both in my desktop and notebook.
This workaround works, but I can give more info.

When going to window > appearance, after I click the output is :
`[SEVERE] null 
java.lang.IllegalStateException: Cannot find TopComponent with preferredID AppearanceTopComponent, see IDE log for more details.
	at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:92)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

After I've done the trick @susae  the error was gone.

This paste can help too:
https://pastebin.com/eNpB7TCD

After I've done the work around and changed back to my old project, the appearance tab was there but I could no click it and it was empty...

PS: the forums are in readonly mode but I can't read !!!! Wasted 2hours but found this hehe

If you need something, I'm here!

**Comment by tillgrallert** [comment] 2019-11-12 21:41
Same here on most recent version of macOS Mojave. The work around works but is annoying.

**Comment by edmangog** [comment] 2020-12-01 08:09
Facing same situation on Gephi 0.9.2

**Comment by johschuster** [comment] 2021-12-09 09:13
Hi everyone, I'm facing the same problem on Gephi 0.9.2 and can't find a solution. The one suggested by susae didn't work. Does anyone have a different idea?

**Comment by mbastian** [comment] 2022-02-17 20:12
As suggested and visible from the log the root cause is https://github.com/gephi/gephi/issues/2297. This issue has been fixed and therefore this problem will disappear too. The fix will be included in the upcoming 0.9.3 release.

**Closed by mbastian** 2022-02-17 20:12 UTC
