### ISSUE TITLE
count the average path length of directed graph

### ISSUE THREAD

**Issue by LancelotHolmes** [gephi/gephi#1683] opened 2017-03-04 07:22 UTC
## problem description
I want to know the formula to compute the average path length in the directed graph in Gephi, as the formula in [wikipedia](https://en.wikipedia.org/wiki/Average_path_length) is 
> ![formula.png](https://ooo.0o0.ooo/2017/03/04/58ba68c6588db.png)

but it seemed the calculate result is different from the gephi, for example,if I have a simple directed graph
![figure_1-1.png](https://ooo.0o0.ooo/2017/03/04/58ba6998bb2da.png)
* Node : A,B,C,D
* Edge: (A->B),(B->C),(B->D)
and if I count the average shortest path length by the formula above I will get a result of `0.583`,but the gephi gave a result of `1.4` which make me comfused
![QQ截图20170304152129.jpg](https://ooo.0o0.ooo/2017/03/04/58ba6b12dc590.jpg)

I search the wiki but it didn't give the formula and the reference for the implement algorithm does not work, so I wonder how gephi count the average path length, is it the same as average shortest path length?

Any help is appreciated, thank you
## Environment
* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by duncdrum** [comment] 2017-03-04 10:47
duplicate of #1507?

**Comment by eduramiba** [comment] 2017-03-04 14:27
Yeah, this might be issue #1507 (planned for 0.9.2). I will add this to 0.9.2 milestone too, to make sure it's fixed. Thanks for the report!

**Comment by LancelotHolmes** [comment] 2017-03-05 01:01
Well,I've checked #1507 before,but here is a little different,since #1507 focused on the calculation between directed and un-directed graph,but what I am concerned is the accuracy of calculation formula

**Comment by eduramiba** [comment] 2017-07-04 19:40
Hi,
The problem of #1507 is now fixed. The directed/undirected choice was not being correctly used.

About this distance, calculation, please have in mind that edge weights are not taken into account by the algorithm so the directed avg path length is still 1.4 and the undirected one is 1.5:

`directed = (1 + 2 + 2 + 1 + 1) / 5 = 4`

`undirected = (1 + 2 + 2 + 1 + 1 + 1 + 1 + 2 + 2 + 1 + 2 + 2) / 12 = 1.5`

Maybe we could implement a weighted option.

**Comment by eduramiba** [comment] 2017-07-05 20:38
Closing as not an issue anymore. Weighted metrics issue already existing at #557

**Closed by eduramiba** 2017-07-05 20:38 UTC
Labels: High, Statistics

**Comment by Moradnejad** [comment] 2017-09-16 08:53
I am assuming you divide the sum to the number of available routes (and not `n*(n-1)`) which seems logical to me.

This is the reason the questioner got different results.

**Comment by rloth** [comment] 2018-06-22 12:35
The classic formula found on wikipedia does take into account all "imaginable" enpoints in a directed graph (ie if you have 4 vertices, there are indeed 4 x 3 = 12 ordered couples of distinct vertices).

The formula used by eduramiba does reflect this principle but has several small mistakes:
  - it has reversed labels (the "directed" case is the one that has 12 possibilities, not the other one)
  - it forgets one possibility: the "undirected", which should have less possibilities, has in fact 12/2 = 6 possibilities
  - in the directed case with 12 possibilities, it counts the same value for X -> Y and Y -> X, maybe because he didn't realize it was in fact the directed case... If you only have X -> Y and no indirect route then Y -> X is usually counted 0...

so in the end the real results are:
```
undirected = (1 + 2 + 2 + 1 + 1 + 2) / 6 = 1.5
the set:  {AB   AC   AD
               BC   BD   CD}

directed = (1 + 2 + 2 + 1 + 1 + 0 + 0 + 0 + 0 + 0 + 0 + 0 ) / 12 = 0.58333..
the set: {AB   AC   AD
              BC   BD   CD
              BA   CA   DA
              CB   DB   DC}
```
