### ISSUE TITLE
wont load with Java 1.8

### ISSUE THREAD

**Issue by trevor** [gephi/gephi#833] opened 2013-09-30 20:25 UTC
Gephi loads splash screen and exits with Java 1.8:

```
% ./gephi
Found jdkhome=/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
[exits]
%
```

(Note also that it doesn't seem to use the $JAVA_HOME environment variable.)

**Comment by eduramiba** [comment] 2015-08-26 17:09
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:09 UTC
