### ISSUE TITLE
Gephi beta 0.8.2 

### ISSUE THREAD

**Issue by jcelestin** [gephi/gephi#1140] opened 2015-10-02 12:15 UTC
I downloaded the beta version. When launch I can see the initial page and it disappears with nothing on the screen.

**Comment by dhicks** [comment] 2015-10-02 21:34
Try the instructions here, at least through step 5:  [http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/]()

**Comment by jcelestin** [comment] 2015-10-02 22:48
Dan thanks
The issue seems be that I am running Java 8 on Windows 7. Maybe I should wait for Gephi 9?

**Comment by dhicks** [comment] 2015-10-02 23:05
Ah, sorry, for some reason I assumed that you were using a Mac.  It seems like there's a longstanding issue with Macs running Java 7 and later; the instructions explain how to install a legacy version of Java.  #748 has a long discussion of the problem.  I suppose you might try something similar.  If that doesn't work, I recommend posting more detailed information about your system, any error logs you can generate, etc.

**Comment by eduramiba** [comment] 2015-10-05 21:32
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-10-05 21:32 UTC
