### ISSUE TITLE
Gephi failed importing the project

### ISSUE THREAD

**Issue by akendall1974** [gephi/gephi#2065] opened 2019-01-02 20:28 UTC
## Expected Behavior
Am trying to open a Gephi project file in Gephi64 0.9.2 but the project won't open.

## Current Behavior
This is the information from the Output - Log:

[INFO] External Changes Refresh on focus gain disabled 
[SEVERE] null 
org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: ClassCastException : org.gephi.graph.api.types.IntervalSet cannot be cast to org.gephi.graph.api.types.TimeMap
File: org.gephi.appearance.AttributePartitionImpl
Line : 91
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: org.gephi.graph.api.types.IntervalSet cannot be cast to org.gephi.graph.api.types.TimeMap
	at org.gephi.appearance.AttributePartitionImpl.refresh(AttributePartitionImpl.java:91)
	at org.gephi.appearance.AppearanceModelImpl$ElementFunctionsModel.refreshAttributeFunctions(AppearanceModelImpl.java:549)
	at org.gephi.appearance.AppearanceModelImpl$ElementFunctionsModel.refreshFunctions(AppearanceModelImpl.java:482)
	at org.gephi.appearance.AppearanceModelImpl$FunctionsModel.getFunctions(AppearanceModelImpl.java:420)
	at org.gephi.appearance.AppearanceModelImpl$FunctionsModel.getNodeFunctions(AppearanceModelImpl.java:412)
	at org.gephi.appearance.AppearanceModelImpl.getNodeFunctions(AppearanceModelImpl.java:127)
	at org.gephi.filters.plugin.partition.InterEdgesBuilder.getBuilders(InterEdgesBuilder.java:92)
	at org.gephi.filters.FilterModelPersistenceProvider.readQuery(FilterModelPersistenceProvider.java:257)
	at org.gephi.filters.FilterModelPersistenceProvider.readXML(FilterModelPersistenceProvider.java:178)
	at org.gephi.filters.FilterModelPersistenceProvider.readXML(FilterModelPersistenceProvider.java:88)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenXML(LoadTask.java:298)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:128)
	... 7 more

## Steps to Reproduce

1.
2.
3.
4.

## Context

Hope you can help as this is a project for my PhD dissertation. Everything was working fine two weeks ago when I saved it however I can't open it today. I can open other files (like Les Miserables.gexf)

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: Windows

**Comment by jcmundy** [comment] 2019-02-19 17:11
I think I've been having the same problem.  I cannot save gephi project files, but exporting to gexf works fine (so I have been doing that for everything).

**Comment by anunezji** [comment] 2020-02-17 12:44
I have been having the same problem. It (seemingly at random) appears and disappears when trying to import a project. 

I am using:
Product Version: Gephi 0.9.2 201709241107
Java: 1.8.0_241; Java HotSpot(TM) 64-Bit Server VM 25.241-b07
Runtime: Java(TM) SE Runtime Environment 1.8.0_241-b07
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (gephi)

This is the output log:
[SEVERE] null 
org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: ClassCastException : org.gephi.graph.api.types.IntervalSet cannot be cast to org.gephi.graph.api.types.TimeMap
File: org.gephi.appearance.AttributePartitionImpl
Line : 91
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.gephi.graph.api.types.IntervalSet cannot be cast to org.gephi.graph.api.types.TimeMap
	at org.gephi.appearance.AttributePartitionImpl.refresh(AttributePartitionImpl.java:91)
	at org.gephi.appearance.AppearanceModelImpl$ElementFunctionsModel.refreshAttributeFunctions(AppearanceModelImpl.java:549)
	at org.gephi.appearance.AppearanceModelImpl$ElementFunctionsModel.refreshFunctions(AppearanceModelImpl.java:482)
	at org.gephi.appearance.AppearanceModelImpl$FunctionsModel.getFunctions(AppearanceModelImpl.java:420)
	at org.gephi.appearance.AppearanceModelImpl$FunctionsModel.getEdgeFunctions(AppearanceModelImpl.java:416)
	at org.gephi.appearance.AppearanceModelImpl.getEdgeFunctions(AppearanceModelImpl.java:132)
	at org.gephi.desktop.appearance.AppearanceUIModel.initSelectedTransformerUIs(AppearanceUIModel.java:107)
	at org.gephi.desktop.appearance.AppearanceUIModel.<init>(AppearanceUIModel.java:99)
	at org.gephi.desktop.appearance.AppearanceUIController$1.select(AppearanceUIController.java:109)
	at org.gephi.project.impl.ProjectControllerImpl.fireWorkspaceEvent(ProjectControllerImpl.java:331)
	at org.gephi.project.impl.ProjectControllerImpl.openProject(ProjectControllerImpl.java:240)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:161)
	... 7 more

I am not sure I fully understand the error message but it seems Gephi tries to cast one type of dynamic data into another (my project has "IntervalSet" data and Gephi tries to import it as "TimeMap"). Would it be possible to (a) check what dynamic data type the project being imported has before trying to load it? or (b) try "TimeMap" and if there is an exception, try "IntervalSet", and if neither work then output an exception?

I have zero experience with Java so I would appreciate any help - thanks in advance!

**Comment by mbastian** [comment] 2021-11-16 19:37
Duplicate of #2297

**Closed by mbastian** 2021-11-16 19:37 UTC
Labels: IO
