### ISSUE TITLE
BUG: Unable to size nodes based on numeric attribute

### ISSUE THREAD

**Issue by swayson** [gephi/gephi#1525] opened 2016-06-28 12:03 UTC
Hi there,

In gephi 0.9 and in 0.9.1, node sizes can only be based on Degree. That is, all the numeric attributes are not available in the drop down except for degree. However, you can colour the nodes by these attributes. Thus, it seems to only impact the sizing of nodes.

This is clearly a bug as it worked fine in 0.8.2.

What is the workaround, or plan to resolve this bug? 

Any information will be greatly appreciated .

**Comment by eduramiba** [comment] 2016-06-28 12:17
Closing as duplicate of #1525 please check it for a workaround

**Comment by eduramiba** [comment] 2016-06-28 12:17
Sorry I meant #1459

**Closed by eduramiba** 2016-06-28 12:17 UTC
