### ISSUE TITLE
Forum register

### ISSUE THREAD

**Issue by tomyjo** [gephi/gephi#1423] opened 2016-03-10 12:23 UTC
Hello
When trying to register at the forum I was denied based on the following sentence:
"Your IP 108.162.229.147 has been blocked because it is blacklisted. For details please see http://www.ahbl.org/lktool?lookup=108.162.229.147.
An entry on the blacklist may have several reasons."

I know  I am not.... If you go to the website http://www.ahbl.org/

it is written by them "i'll be wildcarding all zones no longer in operation - this includes rhsbl.ahbl.org, dnsbl.ahbl.org, and ircbl.ahbl.org.  This means that these services will return positive responses for any queries. If you are still using these services, this may cause you to incorrectly tag e-mail as spam, or create other unintended consequences. "

so i guess this is why. Can you fix it, such a way I may register to the forum ?

thanks 

Thomas

**Comment by Allekalle** [comment] 2016-03-18 12:26
Hello, 
same here. I get the message "Your IP 162.158.92.179 has been blocked because it is blacklisted." 
Funny thing is, my IP is not 162.158.92.179 but within 87.158.x.x (German Telekom). 
Greets
Kalle

**Comment by cdgoodwin** [comment] 2016-03-24 18:16
Hi -- Same problem here. Tried it from work, home, and my mobile device with same "blacklisted" message.

**Comment by eduramiba** [comment] 2016-04-04 08:12
Duplicate of #1047

**Closed by eduramiba** 2016-04-04 08:12 UTC
