### ISSUE TITLE
Hung on Initializing using Java 11.0.16 on iOS

### ISSUE THREAD

**Issue by dbergvinson** [gephi/gephi#2627] opened 2022-09-17 11:55 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment
Macbook running Java 11.0.16
* Version used: Gephi 0.9.7
* Operating System: Montery 12.6

**Comment by mbastian** [comment] 2022-11-21 21:28
Duplicate of #2546

**Closed by mbastian** 2022-11-21 21:28 UTC
Labels: To review
