### ISSUE TITLE
cannot run Gephi

### ISSUE THREAD

**Issue by Youngsikko** [gephi/gephi#989] opened 2014-12-29 14:37 UTC
I've already downloaded new version of Gephi and installed it.
And then I run the program but it didn't show up Gephi. 
I've checked on Firewall, JAVA and any programs I should install. 
What should I do?

**Comment by eduramiba** [comment] 2015-08-26 16:53
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:53 UTC
