### ISSUE TITLE
0.8.2 now freezing on Mac 10.8.5

### ISSUE THREAD

**Issue by leahmac** [gephi/gephi#848] opened 2013-10-30 17:42 UTC
Gephi installed and loaded fine last week, and I used it. Now, on startup it begins to load, then hangs. I have downgraded back to Java 6 without success. I have reinstalled Gephi without success.

Suggestions?

**Comment by eduramiba** [comment] 2015-08-26 17:09
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:09 UTC
