### ISSUE TITLE
Workspace tabs panel is missing when opening project file

### ISSUE THREAD

**Issue by NetMastr5** [gephi/gephi#1827] opened 2017-10-25 19:53 UTC
## Expected Behavior
Open a save project with multiple workspaces, workspaces tabs strip should be shown

## Current Behavior
Open a save project with multiple workspaces, workspaces tabs strip is not visible

## Steps to Reproduce

1. open gexf file
2. save to gephi file
3. open another gexf file adding to new workspace
4. save gephi file
5. open gephi file (workspace tabs section does not exist)

## Context

This prevents me from looking at any other workspace besides the one that is shown when the file if opened

The workspaces are still there as I can do a delete from the workspace menu and the currently visible workspace is deleted and the next one in line is now shown.

Adding a new workspace via the menu does not cause the workspaces tab strip to reappear either, but the workspace is created as I can click delete workspace an additional time.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_131; Java HotSpot(TM) 64-Bit Server VM 25.131-b11
* Operating System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (gephi)

[messages.log](https://github.com/gephi/gephi/files/1415944/messages.log)

![what i see](https://user-images.githubusercontent.com/8885064/32019742-cc5bb118-b993-11e7-888d-da4e3ccd9b2e.png)

**Comment by michihenninger** [comment] 2018-12-28 16:48
Hi
I was just facing the same issue. The first time I opened a .gephi file there were many workspaces... Then gephi crashed and when opening the same file again no workspaces were visible at all (only one graph). Even removing the file, copying it from the origin and open the new one did not help.

The only thing that helped was to open another gephi file first with some workspaces and then opening the gephi file from above (without closing gephi, right from the file menue)... Luckily the workspaces appeared again... Hope this hint helps (you or someone else).

**Comment by gaspa93** [comment] 2019-03-20 16:23
Hi,

exact same configuration and problem, @michihenninger tick solved. 
Thank you,

Mattia

**Comment by mbastian** [comment] 2022-03-02 20:13
Hi, I was not able to reproduce this issue on the latest [0.9.3 nightly build](https://github.com/gephi/gephi#nightly-builds). We have made some improvements in the Gephi IO part so maybe this fixed this issue as well. I'm closing but feel free to reopen if the problem persists once you get to try the new version. Thx!

**Comment by mbastian** [comment] 2022-03-23 21:16
Hi, I think I was finally able to reproduce this issue. It seems to happen only when opening the project by double-clicking on the file itself, which opens Gephi with this file loaded.

**Closed** 2022-03-23 21:20 UTC
Labels: Fix Committed, UI
