### ISSUE TITLE
Beta version freezes on Mac

### ISSUE THREAD

**Issue by mso1830** [gephi/gephi#1055] opened 2015-05-17 08:10 UTC
I have mac 10.10.2
gephi is not working

**Comment by eduramiba** [comment] 2015-08-26 16:43
Possible duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:43 UTC

**Comment by mso1830** [comment] 2015-10-26 03:55
Thanks
