### ISSUE TITLE
Float cannot be cast to Double when opening a dynamic GEXF file

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#1401] opened 2016-02-26 12:52 UTC
> java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
>     at org.gephi.graph.impl.EdgeImpl.getWeight(EdgeImpl.java:181)
>     at org.gephi.visualization.bridge.DataBridge.updateWorld(DataBridge.java:194)
>     at org.gephi.visualization.opengl.CompatibilityEngine.updateWorld(CompatibilityEngine.java:105)
>     at org.gephi.visualization.scheduler.CompatibilityScheduler.updateWorld(CompatibilityScheduler.java:176)
>     at org.gephi.visualization.scheduler.CompatibilityScheduler$2.run(CompatibilityScheduler.java:105)
> [catch] at org.gephi.visualization.scheduler.BasicFPSAnimator.run(BasicFPSAnimator.java:34)

sample weight:

`<attvalue for="weight" value="2000.000000" start="2011-10-23" end="2011-10-30" />`

**Comment by mbastian** [comment] 2022-01-22 18:55
I can't reproduce this anymore and the code does seem right to me. Closing.

**Closed by mbastian** 2022-01-22 18:55 UTC
Labels: GEXF
