### ISSUE TITLE
Gephi 9.1 crashes after message"can't find the name of intel icd opengl driver"

### ISSUE THREAD

**Issue by mauhirata** [gephi/gephi#1755] opened 2017-07-19 00:56 UTC
## Steps to Reproduce

1. open Gephi
2. message appear on loading
3. close message
4. opens and freezes afterwards

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10; Intel Graphics HD 620, OpenGL 4.4 Java 1.8.0. 

![sem titulo-1](https://user-images.githubusercontent.com/30276034/28345937-ddd46f4e-6c03-11e7-9c04-bb2cd0304277.jpg)

**Comment by eduramiba** [comment] 2017-07-19 07:28
Duplicate of #1724

**Closed by eduramiba** 2017-07-19 07:28 UTC
