### ISSUE TITLE
can't load gephi version 8

### ISSUE THREAD

**Issue by RichardKusnierz** [gephi/gephi#980] opened 2014-11-26 17:20 UTC
Hi I followed the instructions and downloaded the latest version of Java as suggested , I' then ran the setup which created an icon on my desktop but when I click on that the Gephi welcome screen appears then disappears and I done seem to be able to use the application.

can someone either send me an email to advise of contact me during working hours in the UK o +44 207 801 2400

Many thanks 

Richard Kusnierz

**Comment by eduramiba** [comment] 2015-08-26 16:54
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:54 UTC
