### ISSUE TITLE
Performance related problem

### ISSUE THREAD

**Issue by kelemusosa** [gephi/gephi#2696] opened 2022-11-16 16:07 UTC
Dear all
I have downloaded gephi 9.7 on my MacBook pro and tried to use it. Though the program opens with different windows, it doesn't; allow me to import data as the cursor is busy for an unlimited period. Could you give me any advice on this, please?

**Comment by mbastian** [comment] 2022-11-21 21:27
Duplicate of #2546

**Closed by mbastian** 2022-11-21 21:27 UTC
