### ISSUE TITLE
Portable Version for Business applications?

### ISSUE THREAD

**Issue by ElfenB** [gephi/gephi#2163] opened 2020-01-20 08:15 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2020-01-24 10:40
Duplicate of https://github.com/gephi/gephi/issues/843

**Closed by eduramiba** 2020-01-24 10:40 UTC
