### ISSUE TITLE
Java or Java9 issues

### ISSUE THREAD

**Issue by gbolcer** [gephi/gephi#1912] opened 2018-02-07 20:59 UTC
## Expected Behavior

Launch of UI

## Current Behavior

Dialog w/ Cannot find Java 1.8 or higher

## Possible Solution

Need to set Java path, java9 or java8 to support c:/java

## Steps to Reproduce

1. Download gephi 0.9.2
2. Install
3. Double click desktop icon
4. View dialog

## Context

Have previous visualization files would like to open and update.  

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java9 (9.0.4.11+)
* Operating System: Windows 10 x64

Couldn't find community board dealing w/ issues. Would prefer just viewing discussion over submitting issue.

**Comment by gbolcer** [comment] 2018-02-07 21:03
"C:\Program Files\Gephi-0.9.2\bin\gephi64.exe" --jdkhome C:\java
Seems to work.  Setting to $JAVA_HOME even though variable was set did not work.

**Comment by eduramiba** [comment] 2018-02-08 09:01
Duplicate of #1849 We don't control the NetBeans platform launcher that we use anyway and I am not sure if it supports java 9 at all.

**Closed by eduramiba** 2018-02-08 09:01 UTC

**Comment by pdeman** [comment] 2019-03-20 07:42
did you find any solution for this ? I can't find a way to run gephi...

**Comment by eduramiba** [comment] 2019-03-20 09:37
Check https://github.com/gephi/gephi/issues/2081 or https://github.com/gephi/gephi/issues/2087
