### ISSUE TITLE
No node labels visible when importing from dot

### ISSUE THREAD

**Issue by proteusGIT** [gephi/gephi#2213] opened 2020-09-18 15:48 UTC
I have no node labels for the example [gephi-dot-example](https://gephi.org/users/supported-graph-formats/graphviz-dot-format/).
```
digraph sample2 {
A -> B [ label = "Edge A to B" ];
B -> C [ label = "Edge B to C" ];
A [label="Node A"];
}
````
I am importing the file but there are only black circles instead of labels.
I turned on `Preview->Node Label->Show Labels` but that did not change anything.
Any ideas?

**Comment by mbastian** [comment] 2021-12-23 09:43
Hi, I'm not able to reproduce this issue on the 0.9.2 version. The label appears as expected. Could you maybe provide additional details? Thank you!

**Comment by mbastian** [comment] 2022-03-01 19:38
As I didn't hear back I'll close this one. Feel free to reopen when needed.

**Closed by mbastian** 2022-03-01 19:38 UTC
Labels: Awaiting for response, Import
