### ISSUE TITLE
Error running with Oracle Java 8 64 bit on Ubuntu

### ISSUE THREAD

**Issue by atiq-cs** [gephi/gephi#1048] opened 2015-04-26 07:36 UTC
```$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)```

gephi crashes and exits right after showing the splash screen everytime.

I got following error analyzing log,
$cat ~/.gephi/0.8.2/dev/var/log/messages.log
-------------------------------------------------------------------------------
>Log Session: Sunday, April 26, 2015 3:19:55 AM EDT
>System Info: 
  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Linux version 3.19.3-031903-generic running on amd64
  Java; VM; Vendor        = 1.8.0_45; Java HotSpot(TM) 64-Bit Server VM 25.45-b02; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_45-b14
  Java Home               = /home/atique/jre1.8.0_45
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /home/atique
  Current Directory       = /home/atique/gephi
  User Directory          = /home/atique/.gephi/0.8.2/dev
  Cache Directory         = /home/atique/.gephi/0.8.2/dev/var/cache
  Installation            = /home/atique/gephi/gephi/gephi
                            /home/atique/gephi/gephi/platform
                            /home/atique/gephi/gephi/platform
  Boot & Ext. Classpath   = /home/atique/jre1.8.0_45/lib/resources.jar:/home/atique/jre1.8.0_45/lib/rt.jar:/home/atique/jre1.8.0_45/lib/sunrsasign.jar:/home/atique/jre1.8.0_45/lib/jsse.jar:/home/atique/jre1.8.0_45/lib/jce.jar:/home/atique/jre1.8.0_45/lib/charsets.jar:/home/atique/jre1.8.0_45/lib/jfr.jar:/home/atique/jre1.8.0_45/classes:/home/atique/jre1.8.0_45/lib/ext/cldrdata.jar:/home/atique/jre1.8.0_45/lib/ext/nashorn.jar:/home/atique/jre1.8.0_45/lib/ext/localedata.jar:/home/atique/jre1.8.0_45/lib/ext/jfxrt.jar:/home/atique/jre1.8.0_45/lib/ext/sunjce_provider.jar:/home/atique/jre1.8.0_45/lib/ext/sunec.jar:/home/atique/jre1.8.0_45/lib/ext/dnsns.jar:/home/atique/jre1.8.0_45/lib/ext/zipfs.jar:/home/atique/jre1.8.0_45/lib/ext/sunpkcs11.jar
  Application Classpath   = /home/atique/gephi/gephi/platform/lib/boot.jar:/home/atique/gephi/gephi/platform/lib/org-openide-modules.jar:/home/atique/gephi/gephi/platform/lib/org-openide-util.jar:/home/atique/gephi/gephi/platform/lib/org-openide-util-lookup.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_ar_SA.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_bg.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_ca.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_cs.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_de.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_es.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_fr.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_gl_ES.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_in_ID.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_it.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_ja.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_ko.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_nl_NL.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_pl.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_pt_BR.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_pt_PT.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_ro.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_ru.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_si.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_sq.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_sv.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_tr.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_zh_CN.jar:/home/atique/gephi/gephi/platform/lib/locale/boot_zh_TW.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_bg.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_ca.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_cs.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_de.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_es.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_fr.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_it.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_ja.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_ko.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_pl.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_ro.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_ru.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_si.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_sq.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_sv.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_tr.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_bg.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_ca.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_cs.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_de.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_es.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_fr.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_it.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_ja.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_ko.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_pl.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_ro.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_ru.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_si.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_sq.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_sv.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_tr.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/home/atique/gephi/gephi/platform/lib/locale/org-openide-util_zh_TW.jar
  Startup Classpath       = /home/atique/gephi/gephi/platform/core/org-openide-filesystems.jar:/home/atique/gephi/gephi/platform/core/core.jar:/home/atique/gephi/gephi/platform/core/locale/core_ko.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/home/atique/gephi/gephi/platform/core/locale/core_sv.jar:/home/atique/gephi/gephi/platform/core/locale/core_si.jar:/home/atique/gephi/gephi/platform/core/locale/core_pt_PT.jar:/home/atique/gephi/gephi/platform/core/locale/core_nl_NL.jar:/home/atique/gephi/gephi/platform/core/locale/core_cs.jar:/home/atique/gephi/gephi/platform/core/locale/core_sq.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/home/atique/gephi/gephi/platform/core/locale/core_fr.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_it.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/home/atique/gephi/gephi/platform/core/locale/core_it.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/home/atique/gephi/gephi/platform/core/locale/core_ro.jar:/home/atique/gephi/gephi/platform/core/locale/core_ca.jar:/home/atique/gephi/gephi/platform/core/locale/core_es.jar:/home/atique/gephi/gephi/platform/core/locale/core_ja.jar:/home/atique/gephi/gephi/platform/core/locale/core_in_ID.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/home/atique/gephi/gephi/platform/core/locale/core_zh_CN.jar:/home/atique/gephi/gephi/platform/core/locale/core_pt_BR.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/home/atique/gephi/gephi/platform/core/locale/core_ru.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/home/atique/gephi/gephi/platform/core/locale/core_pl.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_de.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_es.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_si.jar:/home/atique/gephi/gephi/platform/core/locale/core_tr.jar:/home/atique/gephi/gephi/platform/core/locale/core_gl_ES.jar:/home/atique/gephi/gephi/platform/core/locale/core_bg.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/home/atique/gephi/gephi/platform/core/locale/core_de.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/home/atique/gephi/gephi/platform/core/locale/core_zh_TW.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/home/atique/gephi/gephi/platform/core/locale/core_ar_SA.jar:/home/atique/gephi/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/home/atique/gephi/gephi/bin/../gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
java.lang.IllegalStateException: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:423)
	at org.openide.util.WeakListenerImpl.create(WeakListenerImpl.java:164)
	at org.openide.util.WeakListeners.create(WeakListeners.java:271)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:125)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:142)
	at org.openide.filesystems.MultiFileSystem.getMultiRoot(MultiFileSystem.java:267)
	at org.openide.filesystems.MultiFileSystem.findResource(MultiFileSystem.java:355)
	at org.openide.filesystems.FileUtil.getConfigFile(FileUtil.java:2276)
	at org.openide.filesystems.FileUtil.getConfigRoot(FileUtil.java:2306)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:158)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:412)
	at org.ope```

**Comment by sacsdu** [comment] 2015-05-02 08:21
Runs with Java 7 fine. I guess gephi is not yet ready for Java 8!! :|

**Comment by varac** [comment] 2015-05-18 21:53
same here, ubuntu 15.04, java version:

```
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

```

using openjdk-7 works.

**Comment by skyebend** [comment] 2015-05-27 05:11
Same for me. I was also only able to get it work by using openjdk-7, and explicitly setting the JAVA_HOME environment var

**Comment by skyebend** [comment] 2015-05-27 05:17
even weirder, it still reports:

  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Linux version 3.13.0-44-generic running on i386
  Java; VM; Vendor        = 1.7.0_80; Java HotSpot(TM) Server VM 24.80-b11; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.7.0_80-b15
  Java Home               = /usr/lib/jvm/java-7-oracle/jre

even when the console java version 

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.10.2)
OpenJDK Server VM (build 24.79-b02, mixed mode)

and the JAVA_HOME environment var point to openJDK.   Let me know if I can post helpful log files.

**Comment by eduramiba** [comment] 2015-08-26 16:04
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:04 UTC
