### ISSUE TITLE
OSX  10.9

### ISSUE THREAD

**Issue by cja001** [gephi/gephi#816] opened 2013-09-04 07:22 UTC
Is there any Beta for 10.9 for OS X ? :+1:

**Comment by eduramiba** [comment] 2015-08-26 16:00
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:00 UTC
