### ISSUE TITLE
Why can't I launch Gephi v0.8.2 on my Win7 64bit PC?

### ISSUE THREAD

**Issue by xy0806** [gephi/gephi#1199] opened 2015-12-04 12:03 UTC
![image](https://cloud.githubusercontent.com/assets/16151255/11589224/c9fe3564-9ac1-11e5-888c-1f4a616f1721.png)

I tried v0.8.1 & 0.8.2, but all of them couldn't launch successfully.
After above picture showed, nothing happened then.
Please help, I really want to have a try with this software, especially after I watched the awesome video!

**Comment by computermacgyver** [comment] 2015-12-04 12:05
You will either need to install Java 7 or use the preview build of version 0.9 as explained at #1188

**Comment by xy0806** [comment] 2015-12-04 12:07
Thanks! Hope it work!

**Comment by eduramiba** [comment] 2015-12-04 20:19
Thanks for the help Scott.
Closing as duplicate of #748

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6 on Windows.

**Closed by eduramiba** 2015-12-04 20:19 UTC
