### ISSUE TITLE
gephi not working in macos big sur

### ISSUE THREAD

**Issue by danielaristo** [gephi/gephi#2222] opened 2020-11-20 04:37 UTC
Hi, I updated my mac with macos big sur. I couldn't get gephi working, it hangs with the colored ball spinning. What can I do to solve it?
Thank you

**Comment by IsabelFE** [comment] 2020-11-30 16:43
I have the same issue. Are you working on an updated release to fix this issue soon? Or should I go back to a previous MacOS version?

**Comment by rll307** [comment] 2020-12-16 18:30
I have the same problem. I sorted it out by emulating Linux in a VirtualBox, but it is far from adequate. Are going to be any update on Gephi?

**Comment by buchkremer** [comment] 2020-12-18 08:35
I also have the same problem - pls get it fized for Big Sur....

**Comment by NetwarSystem** [comment] 2020-12-25 03:55
Before you do something drastic like backing up a whole OS rev, see what version of Java you have. Gephi wants version 8, which is pretty much archaic any more. Oracle java version are a  hassle, maybe Corretto just for Gephi would be a workable solution?

https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by fguimara** [comment] 2020-12-29 02:37
My Java is the correct one...
$ java -showversion
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)

Not working for Big Sur as well. It opens and hangs.

**Comment by rll307** [comment] 2021-01-14 13:39
# Update

I was using Brew version of Gephi. When I download it straight from Original Website, it seems to work fine.

**Comment by buchkremer** [comment] 2021-01-14 14:03
Thanx - what do you mean by "Orginal Website" - I can´t find the "Brew" version...

**Comment by UTH-Tuan** [comment] 2021-01-14 16:13
> Thanx - what do you mean by "Orginal Website" - I can´t find the "Brew" version...

From gephi.org website. The brew is the command line install.

**Comment by danielaristo** [comment] 2021-01-14 22:35
i I repeated the installation via brew https://brewinstall.org/install-gephi-mac-osx/
Same result, the program open and hangs

**Comment by rll307** [comment] 2021-01-15 12:37
> > Thanx - what do you mean by "Orginal Website" - I can´t find the "Brew" version...
> 
> From gephi.org website. The brew is the command line install.

Exactly. I seems that the version made available by Homebrew (pack management system) that seems to be the problem. the Brew version is available at https://formulae.brew.sh/cask/gephi#default

**Comment by vlorenzo** [comment] 2021-01-26 14:51
I get it work on big sur. 
just edited the config file /Applications/Gephi.app/Contents/Resources/gephi/etc/gephi.conf
and set jdkhome param as following:
jdkhome="/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre"

PS:
 to know your system available jdk installation paths you can use the command:
/usr/libexec/java_home -V

**Comment by jeremyreffin** [comment] 2021-01-30 09:01
I found a very very simple fix to the "hangs on start with colored ball spinning" issue following a new install of Big Sur. 

For my install the problem was attributable to a change in default tab vs window settings in System Preferences. Big Sur defaults to enforcing tabs instead of windows for multiple open screens (Gephi opens two windows on start with its default setting). It appears Gephi can't cope with tabs and we get the hang/colored ball spinning aftr rendering the two screens as tabs (rather than main screen plus pop-out".

The fix is to change Big Sur's System Preferences:

1. Open System Preferences
2. Open General
3. Towards the bottom change Prefer tabs from "always" to "never"

Also a reminder to all Mac users in Gephi to switch the look-and-feel to Metal (or Nimbus, I believe) rather than the default setting ("Mac OS X") - otherwise Gepi hangs when you try to export a table. The fix here is menu-based: gephi>preferences>appearance>look and feel> and change the preferred look and feel to "Metal".

**Comment by rll307** [comment] 2021-02-01 09:55
Thank you very much!
[]s
Rodrigo
--
<https://linktr.ee/rll307>

**Comment by danielaristo** [comment] 2021-02-01 13:32
Thank you Lorenzo and Jeremy. It works for me

**Comment by IsabelFE** [comment] 2021-02-01 22:36
Thanks @jeremyreffin that works for me!

**Comment by buchkremer** [comment] 2021-02-08 13:12
Many thanks, Jeremy!!

**Comment by shohil-kishore** [comment] 2021-05-18 22:41
Thanks Jeremy, worked for me too!

**Comment by mbastian** [comment] 2021-12-23 09:37
We don't officially support the Brew cask but it seems pretty straightforward downloading from the GitHub release so I'm not sure what might be different.

Regarding the spinning wheel issue I can't reproduce it locally. Would you mind trying out the [current development build](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.3-SNAPSHOT&c=macos&p=dmg) and let me know whether this is still an issue. Thank you!

**Comment by rll307** [comment] 2021-12-23 11:58
Hi,

Thank you for your reply. I am now using the Github repo version any
everything seems to be fine.

I think you can close this topic.

All the best

Rod

r.

**Comment by mbastian** [comment] 2021-12-23 13:15
Thanks, closing the issue then

**Closed by mbastian** 2021-12-23 13:15 UTC
Labels: MacOS, Awaiting for response
