### ISSUE TITLE
Incorrect graph import from GraphML file

### ISSUE THREAD

**Issue by dk766** [gephi/gephi#1719] opened 2017-05-19 11:27 UTC
## Problem description

In some cases (when node attributes are not "grouped" in the file) some attributes are incorrectly interpreted.

I save a graph (generated with NetworkX) and save it in graphml and try to import it in Gephi
The nodes have the following attributes:
- id
- label (similar value with the id)
- x, y, z
- r, g, b

After importing in Gephi I see that some attributes have wrong values: the label field contains the value from one of the rgb components, the r,g,b values are wrong etc.

http://forum-gephi.org/viewtopic.php?f=29&t=6206&p=14383&hilit=Import+graphml#p14383

## Expected Behavior
All the attributes from the graphml file should be correctly loaded

## Current Behavior
The attribute values are read from the input file but assigned to wrong attributes:
- label field contains the value from one of the rgb components
- the values of the r,g,b are wrong

## Possible Solution

By changing the order of the <key> elements and making sure that x,y,x and r,g,b are in the correct order the problem is usually avoided. However this is only a workaround since the definition of the attributes can be in any order in the graphml file

## Steps to Reproduce

1. Import in Gephi the "test.graphml" file provided (on the gephi forum) http://forum-gephi.org/download/file.php?id=719
2. Right click on a node and choose "Select in data laboratory"
3. Click on tab "Data laboratory"
4. Right click on the selected line from the table and choose: "Edit Node"
5. In the left pane inspect the values for attributes: Position (x),Position (y),Position (z),Color, Label and notice they are different from the values within the test.graphml provided file

## Context

I am dynamically generating  graph with hundreds of node with NetworkX (and I customly set the positions and colours of the nodes/edges based on the app logic). I save it in graphml (no control over how NetworkX is saving the file)

## Your Environment

* Version used: Gephi 0.9.1 (but same with the latest 0.9.2 snapshot)
* Operating System: Ubuntu 16.04: 4.4.0-78-generic #99-Ubuntu SMP x86_64 GNU/Linux
* NetworkX version 1.11
* Python Python 3.5.2

**Comment by eduramiba** [comment] 2017-06-29 19:44
The problem is this

https://github.com/gephi/gephi/blob/6efb108718fa67d1055160f3a18b63edb4ca7be2/modules/ImportPlugin/src/main/java/org/gephi/io/importer/plugin/file/ImporterGraphML.java#L111
https://github.com/gephi/gephi/blob/6efb108718fa67d1055160f3a18b63edb4ca7be2/modules/ImportPlugin/src/main/java/org/gephi/io/importer/plugin/file/ImporterGraphML.java#L126

So this should be fixed giving priority to attr.name if existing, then id.  At line https://github.com/gephi/gephi/blob/6efb108718fa67d1055160f3a18b63edb4ca7be2/modules/ImportPlugin/src/main/java/org/gephi/io/importer/plugin/file/ImporterGraphML.java#L555

**Closed** 2017-06-29 20:14 UTC
Labels: Confirmed, High

**Comment by eduramiba** [comment] 2017-11-14 09:42
What does d3 contain in your file? The problem is some users want d3 to be the label, and others don't. Not sure what to do with this format, but it seems it's either not well defined or not well used by many tools (why "d3"? it says very little about what it contains).

Anyway, I suggest you try to remove that d3 attribute or try to make the label attribute appear **after** d3 attribute, so label overwrites it.
