### ISSUE TITLE
Gephi failed to start: default Java home on mac os x 10.7.2

### ISSUE THREAD

**Issue by jarodwen** [gephi/gephi#485] opened 2011-11-29 20:26 UTC
Gephi 0.8 beta failed to start (even cannot show the splash screen) on mac os x 10.7.2. The problem can be solved by setting the Java home in the configuration file in the package:

jdkhome="/Library/Java/JavaVirtualMachines/1.6.0_26-b03-383.jdk/Contents/Home"

**Comment by eduramiba** [comment] 2015-08-26 16:34
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:34 UTC
