### ISSUE TITLE
Gephi on Mac 

### ISSUE THREAD

**Issue by Mitizie** [gephi/gephi#879] opened 2014-01-23 09:12 UTC
I have trouble installing Gephi on my Mac, with Mavericks software. I'm new with Mac generally, but I have installed Java and do as the installation guide suggests. Anyone has an idea?

**Comment by eduramiba** [comment] 2015-08-26 17:08
Probable duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:08 UTC
