### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Abncoffee** [gephi/gephi#907] opened 2014-04-17 19:09 UTC
Everytime I try to open Gephi, it shows the splash-screen for a few seconds and then it closes, nothing happens.
This is my PC's specs:
Windows 7 Ultimate 32-bit
Core 2 Duo E7400 2,8GHz
Nvidia GeForce GT240 (Driver's version is the 9.18.13.3523, from March 4th, 2014. I updated it 3 days ago).
And Java 8.
I need Gephi for some College works and I can't open it. I've even tried opening the gdf file, which my friend sent me, using NodeXL, but it's no the same thing :/
What do I do?

**Comment by narfman0** [comment] 2015-07-10 02:48
For the googlers, try using the nightly snapshot (worked for me): https://github.com/gephi/gephi#nightly-builds

**Comment by mbastian** [comment] 2015-11-25 23:03
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by mbastian** 2015-11-25 23:03 UTC
