### ISSUE TITLE
Gephi 0.9.1 partition

### ISSUE THREAD

**Issue by kchelmin** [gephi/gephi#1576] opened 2016-10-04 14:23 UTC
I can't find partition as an option in the Appearance tab. I want to be able to color code particular categories of nodes but I can't find how to do this.
Thanks,
K

**Comment by eduramiba** [comment] 2016-10-04 14:29
Hi,
It's possible you are encountering this problem #1459

**Comment by kchelmin** [comment] 2016-10-04 14:51
Hi No I don't see ranking or partition as an option. I only get different options of centrality and in-degree/out-degree....

**Comment by eduramiba** [comment] 2016-10-04 15:06
The UI has changed a bit and we need to update documentation.
Now, you can access ranking/partition at Appearance (select Attribute instead of Uniq). Then there is a small button to switch between ranking and partition.

**Comment by kchelmin** [comment] 2016-10-04 15:08
I am under attribute in Appearance, but do not see ranking or partition as option, or a small button that lets me switch between the two. Can you clarify?

**Comment by eduramiba** [comment] 2016-10-04 15:10
Yeah, ranking/partition is automatically chosen based on the column data, but you can switch it manually.
Once chosen, select a color palette and click on *Apply*

**Comment by kchelmin** [comment] 2016-10-04 15:18
I don't follow, sorry. I have added a new column for these categories (in my case its organization type: multilateral, bilateral, etc). But this column is not showing up still so i can choose it manually...How do I choose it if its not showing up in the pull down menu?

**Comment by eduramiba** [comment] 2016-10-04 15:21
Right, it's not appearing for sizing because of this bug #1459 To workaround it, you need to go to node coloring part of appearance, select that column and make sure that you leave it in ranking mode. Then go back to node sizing in appearance and the column should be available.

**Comment by eduramiba** [comment] 2016-10-23 10:44
Closing as duplicate of #1459

**Closed by eduramiba** 2016-10-23 10:44 UTC
