### ISSUE TITLE
Gephi freezes when I select the "preview" tab

### ISSUE THREAD

**Issue by sjbenham** [gephi/gephi#2711] opened 2022-12-05 19:49 UTC
## Expected Behavior
Visualize the network in the "preview" tab 

## Current Behavior
I can import files, change settings on the "overview" tab and make edits to the 'data laboratory' tab. However, when I select the "preview" tab, the application consistently freezes and will not respond. 

## Possible Solution
I have reinstalled Gephi, closed out any other running applications, restarted my computer, installed any pending updates, all to no avail.

 

## Steps to Reproduce

1. Click on preview tab on main window
2.
3.
4.

## Context

 Attempting to preview network and unable to do so

## Your Environment

* Version used: Gephi 0.9.7
* Operating System: macOS Ventura 13.0.1

**Comment by mbastian** [comment] 2022-12-30 12:36
Duplicate of #2546

**Closed by mbastian** 2022-12-30 12:36 UTC
Labels: To review
