### ISSUE TITLE
Gephi doesn't start

### ISSUE THREAD

**Issue by AlokNalawade** [gephi/gephi#959] opened 2014-10-12 22:34 UTC
Hi,

I am not getting any error. whenever i am trying to open it, it just shows initializing and then the application closes by itself without any warnings or errors.

Thanks,
Alok

**Comment by alex-roc** [comment] 2015-02-28 14:32
Same issue in Windows 8.1, Java 8 (jre1.8.0_31). Any progress in this issue?

**Comment by withforesight** [comment] 2015-02-28 17:16
had the same problem (on Windows 8.1 32-bit, Java 8 (jre1.8.0_31)
What worked for me was downloading the snapshot version from here:
https://github.com/gephi/gephi (under Nightly Builds)

Also unzipped the snapshot out-side of normal c:\program files ....

Maybe the "stable" version has some permission issue or a there is a bug in the installer.

In any case the snapshot version worked for me.

**Comment by sumesh1988** [comment] 2015-05-30 07:04
Gephi works better with Java 7. You need to tell gephi to use specific JDK/JRE by setting config file. It is located at "location of gephi\gephi\etc\gephi.config". Set jdkhome in that config file to the path of your JDK/JRE 1.6 or 1.7. Don't use 1.8.

**Comment by eduramiba** [comment] 2015-08-26 15:58
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:58 UTC
