### ISSUE TITLE
Spam in Gephi Forum

### ISSUE THREAD

**Issue by hbruch** [gephi/gephi#1379] opened 2016-02-15 07:09 UTC
The Gephi forum is currently not really usable, too much spam there.
Is it planned to support it further?

Let me know, if you need a helping hand.

**Comment by mbastian** [comment] 2016-02-18 22:02
Thanks for proposing help! Please contact @jacomyma as he's trying to solve this issue by migrating the forum somewhere else. Closing as duplicate of #1047.

**Closed by mbastian** 2016-02-18 22:02 UTC
