### ISSUE TITLE
Opening Gephi

### ISSUE THREAD

**Issue by FRadice1977** [gephi/gephi#1085] opened 2015-07-31 13:24 UTC
I have downloaded the latest version of JAVA and GIT installed Gephi on a Windows 64bit machine. However I cannot open Gephi. Do I need to install anything else?

**Comment by navabi-rvadakkeparambil** [comment] 2015-07-31 15:12
Gephi doesn't run with the latest Java version (v8) and has big problems with Java v7. It works best with Java v6.

**Comment by eduramiba** [comment] 2015-08-26 15:54
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:54 UTC
