### ISSUE TITLE
Working in Windows 8.1

### ISSUE THREAD

**Issue by kkaatz** [gephi/gephi#1198] opened 2015-12-03 18:53 UTC
Hi there, I just downloaded Gephi and tried to start it.  It looked like it was starting, but then nothing happened.  Any advice?

**Comment by mbastian** [comment] 2015-12-03 18:54
Which Gephi version?

**Comment by kkaatz** [comment] 2015-12-03 18:56
Version 0.8.2

**Comment by computermacgyver** [comment] 2015-12-04 12:06
Hi Kkaatz. Please make sure you have Java 7 installed or download the preview (may have bugs!) version 0.9 from GitHub. Please see #1188 for more details.

**Comment by eduramiba** [comment] 2015-12-04 20:19
Thanks for the help Scott.
Closing as duplicate of #748

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6 on Windows.

**Closed by eduramiba** 2015-12-04 20:19 UTC
