### ISSUE TITLE
Node size by attribute issue

### ISSUE THREAD

**Issue by rmhorne** [gephi/gephi#1484] opened 2016-05-10 15:37 UTC
In both the 0.9.1 stable and 0.9.2 snapshot, only Degree, In-Degree, and Out-Degree appear as options for node sizes (despite not running any statistics, so the values are null). After running eigenvector centrality there is no option to assign it as a node size - I copied the column, converted it to float, and it still does not show up on the list. This may be similar to #1479  

Stats for my system:
Java: 1.8.0_74; Java HotSpot(TM) 64-Bit Server VM 25.74-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_74-b02
System: Mac OS X version 10.11.4 running on x86_64; UTF-8; en_US (gephi)

**Comment by oxygala** [comment] 2016-05-18 06:22
I am having the same issue on Ubuntu 16.04 x86_64 with Java(TM) SE Runtime Environment (build 1.8.0_91-b14) on both 0.9.1 stable and 0.9.2 snapshot

**Comment by BernardoFBBraga** [comment] 2016-09-14 18:16
I had a similar problem and found a potential solution
I found that the COLOR settings of nodes affected the available attributes in the SIZE options.
If the color settings were switched to partition, my attributes do not appear as available to selection when I'm in the size ranking. If I switch color settings to ranking, the attributes show again.

**Comment by mbastian** [comment] 2016-10-23 11:43
Duplicate of #1459 1459

**Closed by mbastian** 2016-10-23 11:43 UTC
Labels: Appearance
