### ISSUE TITLE
Data Laboratory imports all Weight as "1.0"

### ISSUE THREAD

**Issue by GuillaumeLegoy** [gephi/gephi#1420] opened 2016-03-08 22:58 UTC
Hello,

I installed Gephi today and I have the exact same issue listed here: 
https://github.com/gephi/gephi/issues/1243

Thank you!

**Comment by eduramiba** [comment] 2016-04-12 16:20
Hi,
What version are you using? Is the problem the same as https://github.com/gephi/gephi/issues/1251#issuecomment-190250518 ?

**Comment by judithmp** [comment] 2016-04-29 17:11
Same for me, working with Gephi 0.9.1
Once trying, weights became bigger than one, but all rounded up.
During the import everything looks ok, weights are set to be imported as "double".
![gephi_import_spreadshet](https://cloud.githubusercontent.com/assets/5262148/14923540/157db4ca-0e3e-11e6-8e7d-aba6dd03b8d3.png)
![gephi_import_spreadsheet_wrong_output](https://cloud.githubusercontent.com/assets/5262148/14923544/1b4aaa66-0e3e-11e6-8132-26575e62c41e.png)

**Comment by eduramiba** [comment] 2016-10-04 13:26
Closing as duplicate of #1251

**Closed by eduramiba** 2016-10-04 13:26 UTC
