### ISSUE TITLE
Unstable on Win 7 x64 (JRE 8u20)

### ISSUE THREAD

**Issue by ymranx** [gephi/gephi#948] opened 2014-09-13 17:02 UTC
crashes after startup screen.

**Comment by eduramiba** [comment] 2015-08-26 16:56
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:56 UTC
