### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by jcodell45** [gephi/gephi#1116] opened 2015-09-05 23:06 UTC
Downloads take forever and then fail.  Why?  I have a MAC OS X 10.9.5

**Comment by eduramiba** [comment] 2015-09-05 23:08
Are you downloading from http://gephi.github.io/users/download ?
It works fine for me at the moment.

**Comment by jcodell45** [comment] 2015-09-05 23:09
Yes, that’s where I’m downloading from.  It’s been almost an hour and it’s still downloading.

**Comment by eduramiba** [comment] 2015-09-05 23:15
It must be a temporal problem with your network provider, please try again later or from a different network.

Also, it's hosted in launchpad so we can't do much about it https://launchpad.net/gephi/0.8/0.8.2beta

**Comment by jcodell45** [comment] 2015-09-06 00:19
Thanks for trying to help Now that it’s downloaded it will not open!  What now?

**Comment by eduramiba** [comment] 2015-09-06 00:22
Check issue #748 This problem is probably happening to you.

**Comment by jcodell45** [comment] 2015-09-06 00:27
Thanks; then there is no way I can use this.  The link you sent me is gobbled gook and the suggested fixes require a techie, which I am not. I have Java and I downloaded the right version of Gelphi.  The problem is yours, not mine, as some of the responses indicate.  I should not have to learn codes to use this software!  Too bad; I once used Gelphi and found it very helpful two years ago.  If you want donations from users, you are doing to have to fix this Mac-Gelphi problem!  You should read the responses on the link you sent me.  No way I can fix this. Thanks anyway.

**Comment by eduramiba** [comment] 2015-09-06 00:32
Right, that link has way too much info. Please try to follow these steps http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/

We are working on fixing this for next version.

**Comment by jcodell45** [comment] 2015-09-06 02:28
Thanks, again.  This is not something I can do and I think most people would find this as daunting as I do. I have no idea what the directions mean or how to do them.  Hope you can get this fixed, though by then I will have started using other software and may not return to Gelphi, unless I have to. Good luck.

**Comment by eduramiba** [comment] 2015-09-06 10:47
Closing as duplicate of #748

**Closed by eduramiba** 2015-09-06 10:47 UTC
Labels: Not an issue
