### ISSUE TITLE
How to export legand of relative size of node in graph display 

### ISSUE THREAD

**Issue by Wang960823** [gephi/gephi#1867] opened 2017-12-04 10:54 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2017-12-04 10:57
Duplicate of https://github.com/gephi/gephi/issues/511

**Closed by eduramiba** 2017-12-04 10:57 UTC
