### ISSUE TITLE
Problematic gephi installation on ubuntu 12.04

### ISSUE THREAD

**Issue by varun7rs** [gephi/gephi#943] opened 2014-08-23 23:02 UTC
Hello,

I am trying to install gephi on my ubuntu 12.04 kernel 3.5.0-54-generic.
But, I'm very much disturbed because after installation, when I try to run gephi. The splash screen shows up and thats it. Its been a severe problem and my online classes are about to start in a week. So, I need your help in fixing this issue. Please help me out!
I am not sure if the java thing recommended for this software is right. So, I'm posting a few lines following the command
varun@laptop:~/gephi$ sudo update-alternatives --config java
[sudo] password for varun: 
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                           Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-oracle/jre/bin/java         1062      auto mode
  1            /usr/lib/jvm/java-6-openjdk-i386/jre/bin/java   1061      manual mode
  2            /usr/lib/jvm/java-7-openjdk-i386/jre/bin/java   1051      manual mode
* 3            /usr/lib/jvm/java-8-oracle/jre/bin/java         1062      manual mode

Please help me guys

**Comment by eduramiba** [comment] 2015-08-26 16:16
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:16 UTC
