### ISSUE TITLE
installation for mac fail

### ISSUE THREAD

**Issue by Renatabk** [gephi/gephi#913] opened 2014-05-03 06:42 UTC
When trying to install the new beta version for mac, it throws an exception when clicking ok to the box it ends the installation.
The exception message is: "Unable to load libjogl_awt.jnilib"

**Comment by eduramiba** [comment] 2015-08-26 17:00
Probable duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:00 UTC
