### ISSUE TITLE
Characteristics (colors, shape) associated with nodes attributes

### ISSUE THREAD

**Issue by Caddarik** [gephi/gephi#808] opened 2013-07-26 10:17 UTC
Hello,

First : it should be fine to have a new nodes characteristic : shape (ellipse, circle, triangle, square, hexagon,  octagon)  especially for bipartite graph (graph white at least 2 types of nodes)

Secondly : it should be fine to associate characteristic : shape and color with nodes attributes in GEXF. For instance to associate a category white a color and a type with a shape

<attributes class="node" mode="static">
    ...
    <attribute id="type" title="type" type="string"/>
    <attribute id="category" title="category" type="string"/>
</attributes>
<characteristics>
    <characteristic for="type" value="person" shape="circle"/>
    <characteristic for="type" value="project" shape="hexagon"/>
    <characteristic for="type" value="organization" shape="square"/>
    <characteristic for="category" value="America" color="green"/>
    <characteristic for="category" value="Europa" color="blue"/>
    <characteristic for="category" value="Asia" color="red"/>
    <characteristic for="category" value="Africa" color="rgb(12,164,33)"/>
    <characteristic for="category" value="Oceania" color="rgb(45,12,148)"/>
</characteristics>
something like that 

even without the shape new stuff it could help us to do new map without choosing again all colors on by one...

Thank you for your greate work

**Comment by eduramiba** [comment] 2017-03-08 17:57
Closing as duplicate of #1291

**Closed by eduramiba** 2017-03-08 17:57 UTC
