### ISSUE TITLE
Gephi won't start after installation?

### ISSUE THREAD

**Issue by jlhoward46** [gephi/gephi#972] opened 2014-11-04 23:06 UTC
Have a 64 bit windows 7 with Java 8 installed. Not sure why Gephi won't start?
Thanks
Jane

**Comment by eduramiba** [comment] 2015-08-26 16:10
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:10 UTC
