### ISSUE TITLE
Error occuring in terms of loading Edgelist csv file

### ISSUE THREAD

**Issue by radicallbut** [gephi/gephi#2231] opened 2021-01-04 21:45 UTC
## Expected Behavior
I wanted to load the data from the edges spreadsheet (source, target) with my data (# of rows: 1,048,577) in the Edges tab of the Data Laboratory in Gephi after importing this through the "Import Spreadsheet" function.

<img width="358" alt="Screen Shot 2021-01-04 at 3 42 07 PM" src="https://user-images.githubusercontent.com/73622185/103582474-8ac90e00-4ea3-11eb-8e53-90289bbfa8b4.png">

## Current Behavior
The program does not recognize my edgelist and shows the RECORD error as below

<img width="638" alt="Screen Shot 2021-01-04 at 3 43 41 PM" src="https://user-images.githubusercontent.com/73622185/103582564-b815bc00-4ea3-11eb-8d59-a12fef2802bb.png">

I would really appreciate your input on this.

Thanks.

**Comment by mbastian** [comment] 2021-12-23 09:15
Hi, I can't reproduce this issue. Would you mind providing a small sample of your CSV file. Thank you!

**Comment by mbastian** [comment] 2022-03-01 19:37
As I didn't hear back I'll close this one. Feel free to reopen when needed.

**Closed by mbastian** 2022-03-01 19:37 UTC
Labels: Spreadsheet, Awaiting for response, Import, To review
