### ISSUE TITLE
Registering for the forum broken - AHBL is defunct

### ISSUE THREAD

**Issue by gorbynet** [gephi/gephi#1410] opened 2016-03-03 13:03 UTC
I'd like to register for the forum, but can't because you're using a defunct spam detection process. AHBL has been defunct since January 1st 2015, and now reports _everything_ as suspect.
http://www.ahbl.org/content/last-notice-wildcarding-services-jan-1st
Please can you fix this?

**Comment by cdgoodwin** [comment] 2016-03-24 18:31
Yes! Same for me and others.

https://github.com/gephi/gephi/issues/1423

**Comment by eduramiba** [comment] 2016-04-04 08:12
Duplicate of #1047

**Closed by eduramiba** 2016-04-04 08:12 UTC
