### ISSUE TITLE
Problem in Mac

### ISSUE THREAD

**Issue by sotmihos** [gephi/gephi#1131] opened 2015-09-22 21:28 UTC
The program does not open in Mac. After loading picture in shuts down.

Regards,
Michos Sotiris

**Comment by eduramiba** [comment] 2015-09-22 21:30
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac

**Closed by eduramiba** 2015-09-22 21:30 UTC

**Comment by sotmihos** [comment] 2015-09-22 21:36
Thank you for the immediate reply! :)
