### ISSUE TITLE
Error on opening project

### ISSUE THREAD

**Issue by Quendiz** [gephi/gephi#2555] opened 2022-06-30 15:40 UTC
## Current Behavior
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 11
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.gephi.desktop.project.ProjectControllerUIImpl$6.run(ProjectControllerUIImpl.java:322)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

## Context

Error on opening project. The Preview tab is blank on refresh.

## Your Environment
Product Version: Gephi 0.9.6 202206221744
Java: 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10
Runtime: OpenJDK Runtime Environment 11.0.15+10
System: Windows 10 version 10.0 running on amd64; Cp1252; en_GB (gephi)

**Comment by totetmatt** [comment] 2022-06-30 15:47
If it can helps for the investigation, I also got this issue since update to 0.9.6-SNAPSHOT when I was developing plugin recently.
Also it appears to me when I do "Create a new Workspace".

**Comment by mbastian** [comment] 2022-07-17 15:21
@totetmatt I think I know what's going on. This error appears when the current project has been created with the `ProjectController` instead of the `ProjectControllerUI`. I know this might be confusing and is something that I would like to cleanup eventually. If I'm not mistaken, your plugin does automatically create a project, which I think is causing this. You can't reproduce this in core gephi as we always use the `ProjectControllerUI` class to manage projects.

**Comment by totetmatt** [comment] 2022-07-17 15:51
Confirmed, fix will come with next release

**Comment by mbastian** [comment] 2022-07-23 19:26
Closing as the Twitter plugin was updated to 2.0.2 with a fix. Problem should no longer appear after upgrade.

**Closed by mbastian** 2022-07-23 19:26 UTC
Labels: To review
