### ISSUE TITLE
i am importing data from database, but i want store in database only, not in my local system 

### ISSUE THREAD

**Issue by pradeepkum** [gephi/gephi#1655] opened 2017-01-23 07:53 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment] 2017-01-23 08:44
Closing as duplicate of #1654

**Closed by eduramiba** 2017-01-23 08:44 UTC
