### ISSUE TITLE
Freeze on Mac 12.6

### ISSUE THREAD

**Issue by Tiquetou** [gephi/gephi#2651] opened 2022-10-01 03:47 UTC
Hi, I'm currently experiencing a problem with Gephi 0.9.7 on Mac version 12.6 (The last one).

## Expected Behavior

Be able to use the software

## Current Behavior

As soon as I open Gephi the screen freeze with the loading icon. Even after trying multiple versions of Gephi several times and restarting my computer it never works. It actually worked not long ago(a few days) and I didn't update my computer since.

## Your Environment

* Version used: Gephi 0.9.7
* Operating System: Mac 12.6 Monteray

**Comment by enacoding** [comment] 2022-10-04 09:31
Same problem here :(

**Comment by oneextrafact** [comment] 2022-10-04 14:47
And here

**Comment by erinmr** [comment] 2022-10-07 21:12
me too

**Comment by arockenberger** [comment] 2022-10-11 10:54
Same here. Sometimes I can get it to open but crashes in <5min.

**Comment by bifenglin** [comment] 2022-10-12 02:48
same here

**Comment by wvrossem** [comment] 2022-10-17 13:08
I'm experiencing the same problem macOS version 11.7.

**Comment by vladUng** [comment] 2022-10-24 12:20
I experienced this issue on macOS 12.6 and believe that Gephi couldn't find the home for JDK for some reason or another. It seems the problem lies in the `gephic.conf ` file from` /Applications/Gephi.app/Contents/Resources/gephi/etc` at the line with:

`jdkhome="../../PlugIns/jdk-11.0.16+8-jre/Contents/Home"`

There are 3 folders away from Plugins and not 2, so I've changed it to the one below. Note, this doesn't have a relative path as I wasn't sure from where the app starts.

`jdkhome="/Applications/Gephi.app/Contents/PlugIns/jdk-11.0.16+8-jre/Contents/Home"`

**Side notes: **

This worked for me but not sure why. I've changed jdkHome to the original value and Gephi worked again(?!). So, the change might trigger other events?

**Comment by mbastian** [comment] 2022-10-25 20:03
> I experienced this issue on macOS 12.6 and believe that Gephi couldn't find the home for JDK for some reason or another. It seems the problem lies in the `gephic.conf ` file from` /Applications/Gephi.app/Contents/Resources/gephi/etc` at the line with:
> 
> `jdkhome="../../PlugIns/jdk-11.0.16+8-jre/Contents/Home"`
> 
> There are 3 folders away from Plugins and not 2, so I've changed it to the one below. Note, this doesn't have a relative path as I wasn't sure from where the app starts.
> 
> `jdkhome="/Applications/Gephi.app/Contents/PlugIns/jdk-11.0.16+8-jre/Contents/Home"`
> 
> **Side notes: **
> 
> This worked for me but not sure why. I've changed jdkHome to the original value and Gephi worked again(?!). So, the change might trigger other events?

Hi, this workaround is probably misleading. There are no issues with the JDK path.

**Comment by mbastian** [comment] 2022-10-25 20:05
For those experiencing a freeze, have you tried cleaning up the user folder at `/Users/USERNAME/Library/Application\ Support/gephi/0.9/`?

**Comment by enacoding** [comment] 2022-11-28 22:02
Yes, I have done it. If I clean that folder, Gephi runs quickly (super fast, compared to my immediate previous try), but the eternal rainbow circle appears after the window for starting projects :(

**Comment by mbastian** [comment] 2022-12-01 19:51
Duplicate of #2546. Please fill his [questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSfBzLAiebu8hVISiWJ1SlAza3TNlO96EEArWD1uVhCIipytiQ/viewform?usp=sf_link) about the issue. Much appreciated!

**Closed by mbastian** 2022-12-01 19:51 UTC
Labels: MacOS, To review
