### ISSUE TITLE
Error trying to open Gephi project

### ISSUE THREAD

**Issue by cmilhorance** [gephi/gephi#1971] opened 2018-06-02 16:50 UTC
## Current Behavior
I try to open an old gephi project. The software is launched, but the project does not open. Nothing happens. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: windows 10

**Comment by aldou** [comment] 2018-08-03 15:02
Duplicate of issue #1997 
Check the workaround explained over there.

**Comment by wetneb** [comment] 2021-12-02 11:07
Closing as duplicate of #1997.

**Closed by wetneb** 2021-12-02 11:07 UTC
