### ISSUE TITLE
color settings in Overview/Appearance are lost when a gephi file is opened

### ISSUE THREAD

**Issue by alexbovet** [gephi/gephi#1927] opened 2018-03-09 11:00 UTC
## Expected Behavior
After opening a saved project where specific colors were chosen for nodes, e.g. choosing a variable for ranking and specifying colors for a gradient, I expect to see the same previously chosen parameters in the Overview/Appearance menu. 

## Current Behavior

Instead the parameters are reset to default. Note that the colors are correctly saved as node attribute and are restored in Graph window and Preview panel. The issue is in the Appearance panel.

I am not sure if this is a bug or a missing feature as I couldn't find mentions of this issue elsewhere.

## Steps to Reproduce

1. Open a file
2. Change node colors in the appearance menu
3. Save file
4. Reopen file

## Context

This issue is hindering my workflow and makes the usage of gephi difficult in a context where reproducibility and consistency are important.

## Your Environment

* Version used: Gephi 0.9.2 201709241107
* Java version: 1.8.0_162; OpenJDK 64-Bit Server VM 25.162-b12
* Runtime: OpenJDK Runtime Environment 1.8.0_162-b12
* Operating System: Linux version 4.15.7-1-ARCH running on amd64

**Comment by eduramiba** [comment] 2018-03-09 11:02
Duplicate of #1861

**Closed by eduramiba** 2018-03-09 11:02 UTC

**Comment by alexbovet** [comment] 2018-03-09 11:06
Wasn't sure if it was the same issue than for *node color palette* since node colors are correctly saved for me...

**Comment by eduramiba** [comment] 2018-03-09 11:09
Sure, it refers to the palettes used in appearance. Node colors are just the colors and work fine.
