### ISSUE TITLE
Gephi does not import all of the edges

### ISSUE THREAD

**Issue by Sebastian-Eriksson-Berggren** [gephi/gephi#2174] opened 2020-03-01 14:30 UTC
## Expected Behavior
Having all of the imported edges included in my data laboratory when importing my csv file with edges. 
## Current Behavior
There are appoximately 67 edges out of 773 missing when the import is made. Gephi acknowIedge all of the edges in the steps leading up to the import but then excludes a number of them when I check my added edges. I have also tried with a .xslx file to see if it's something fishy with the .csv import, with the same under par result.
## Possible Solution
Since I am in a hurry I am wondering if it is possible to manually add the missing edges manually and enter the weight manually?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: Windows 10

**Comment by Marmeladenbrot** [comment] 2020-03-10 21:29
Are some of the edges self loops? Afaik default option is to not include edges where Source Id == Target Id.

Maybe you could upload the node/edge file if possible.

**Comment by mbastian** [comment] 2022-04-26 18:47
Hi, I can't reproduce this issue - even on 0.9.2. Could you please detail the steps more precisely?

**Comment by ecchy** [comment] 2022-05-06 12:34
> Hi, I can't reproduce this issue - even on 0.9.2. Could you please detail the steps more precisely?

Hi, I was in French locale... maybe the language is the culprit here?

**Comment by mbastian** [comment] 2022-06-17 18:58
> > Hi, I can't reproduce this issue - even on 0.9.2. Could you please detail the steps more precisely?
> 
> Hi, I was in French locale... maybe the language is the culprit here?

No, language doesn't play any role in import.

**Comment by mbastian** [comment] 2022-06-17 18:59
Closing as we can't reproduce.

**Closed by mbastian** 2022-06-17 18:59 UTC
Labels: Spreadsheet, Awaiting for response, Can't reproduce
