### ISSUE TITLE
Export-To-Earth Plugin for Gephi 0.9.1 Fails to Install

### ISSUE THREAD

**Issue by sindimo** [gephi/gephi#1467] opened 2016-04-21 05:34 UTC
The Export-To-Earth plugin fails to install through the plugin manager in Gephi 0.9.1, would appreciate any help please on how to install this plugin with Gephi 0.9.1, thanks!

**Comment by eduramiba** [comment] 2016-04-21 08:05
Closing as duplicate of https://github.com/gephi/gephi-plugins/issues/105

**Closed** 2016-10-26 21:10 UTC
