### ISSUE TITLE
gephi is not working

### ISSUE THREAD

**Issue by eiatnas** [gephi/gephi#1107] opened 2015-08-27 23:10 UTC
hi, 
iwm currently using windows 10, but the occured in win 7 as well
gephi is loading, and then does nothing.
i tried to reinstall a few times and still not working,
i also tried to reinstall java, not working.

any suggestions?
is there any upcomig version with bug fix?

thank you very much

**Comment by techtonik** [comment] 2015-08-28 04:56
There is the Roadmap for upcoming version - https://github.com/gephi/gephi/milestones/0.9 but the fix is not committed yet. You can try Java 6.

**Comment by eduramiba** [comment] 2015-08-28 06:42
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-28 06:42 UTC
