### ISSUE TITLE
Gephi 0.9.7 gets stuck when opening with MacOS Ventura

### ISSUE THREAD

**Issue by mirkohu** [gephi/gephi#2685] opened 2022-11-05 11:29 UTC
## Steps to Reproduce

1. Install Gephi 0.9.7
2. Update to MacOS Ventura

## Context

 I was trying to open the application, but it opens and gets stuck showing "Initializing..."
## Your Environment

* Version used: Gephi 0.9.7
* Operating System: MacOS Ventura

**Comment by webphile94** [comment] 2022-11-21 15:15
Same here :(

**Comment by maximelat** [comment] 2022-11-21 21:41
same here :/

**Comment by gslanzon** [comment] 2022-11-23 20:55
Same here

**Comment by abuzar-rasool** [comment] 2022-11-30 23:26
same here :(

**Comment by mbastian** [comment] 2022-12-01 19:49
Duplicate of #2546, and please fill this [questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSfBzLAiebu8hVISiWJ1SlAza3TNlO96EEArWD1uVhCIipytiQ/viewform?usp=sf_link) about this issue. We need your help.

**Closed by mbastian** 2022-12-01 19:49 UTC
Labels: To review
