### ISSUE TITLE
New Gephi does not recognize Java 1.8

### ISSUE THREAD

**Issue by hunsabr** [gephi/gephi#1922] opened 2018-03-04 18:04 UTC
## Expected Behavior
Update of the latest Gephi recognizes Java 1.8
## Current Behavior
Update of the latest Gephi does not recognize Java 1.8 that is installed on my machine
## Possible Solution

Please fix the latest Gephi to recognized Java 1.8.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Gephi will not open. It just bleats at me that I do not have Java 1.8 installed. Java 1.8 is installed.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: Windows 10

**Comment by eduramiba** [comment] 2018-03-04 18:09
Duplicate of #1787

**Closed by eduramiba** 2018-03-04 18:09 UTC
