### ISSUE TITLE
Gephi 0.9.1 freezes when opening on Windows

### ISSUE THREAD

**Issue by jeffreyb23** [gephi/gephi#1483] opened 2016-05-10 13:25 UTC
I have similar issues as #1241 & #1250 but instead my freeze is happening on windows. I've reinstalled twice but cannot get the application to load. Unlike the cited issues Gephi has never loaded for me but freezes at "Starting Modules..."

 Any guidance is appreciated:)

Also tried solutions posted in #748 / #1110 but did not work for me. Downloaded Java 1.7 for 64 & 86 and switched path for each in the gephi.conf file but same issue persisted.

**Comment by jlwaid** [comment] 2016-06-05 09:36
I have the same issue when using the attribute tab.  I was using Gephi 0.8 and that would not open so I upgraded to 0.9.1 yesterday.

**Comment by GabrielFerrari** [comment] 2017-06-29 18:57
Any solution on this question?

**Comment by eduramiba** [comment] 2017-06-29 20:27
Duplicate of 1631

**Closed by eduramiba** 2017-06-29 20:27 UTC
