### ISSUE TITLE
Image Preview plugin not available in v 0.10.1

### ISSUE THREAD

**Issue by careerhops** [gephi/gephi#2777] opened 2023-03-21 07:50 UTC
## Context

I can't display images on the nodes.

## Your Environment

* Version used: Gephi 0.10.1
* Operating System: MacOs Ventura 13.2.1

**Comment by totetmatt** [comment] 2023-03-21 07:52
Duplicate of https://github.com/gephi/gephi/issues/2764

**Closed by totetmatt** 2023-03-21 07:52 UTC
Labels: To review
