### ISSUE TITLE
Problems in creating dynamic network in Python and importing into Gephi

### ISSUE THREAD

**Issue by kbaltakys** [gephi/gephi#1425] opened 2016-03-14 15:09 UTC
I want to make a simple dynamic network in Python and open it for use in Gephi.
I need the network edges to have time varying weights.

I figured to write the dynamics of the edges into edge attributes:
```
import networkx as nx
import pandas as pd

df = pd.DataFrame()
df['From'] = [0,1,2,3,4,5,6,7,8,9]
df['To'] = [1,2,3,4,5,6,7,8,9,0]
# For now all the dynamics are the same fot all edges:
df['Attributes'] ='<[1990-01-01,1];[1990-03-01,2];[1990-04-30,6]>'

Graph = nx.from_pandas_dataframe(df, 'From', 'To', 'Attributes')
nx.write_gexf(Graph,4,5, "Graph.gexf")
```

Once the file is saved I manually open it and add ``` timerepresentation="timestamp" ``` to the ```<graph ...>``` definition.

Then I open the file with Gephi, and in the Edges tab under Data Labarotory, I convert Weight column into dynamic column and Copy the data from Attributes column to Weight. Then I enable the Timeline and up to this point everything seems to be OK.

But if I try to export everything to *.gexf file the file cuts in the middle of defining the first edge:

```
...
     </node>
   </nodes>
   <edges>
      <edge id="0" source="0" target="1"
```
And I get an Unexpected exception.
![image](https://cloud.githubusercontent.com/assets/12213184/13748793/022f9bc8-ea07-11e5-9a4e-78c9a5682eac.png)

Also Gephi becomes unresponsive, especially if I try to adjust the boundaries of the timeline.

Any ideas what the problem could be?

Perhaps there's another way to build a network with time varying edge weights in Python?

**Comment by eduramiba** [comment] 2016-03-30 10:46
Closing as duplicate of #1426

**Closed by eduramiba** 2016-03-30 10:46 UTC
