### ISSUE TITLE
Gephi cannot find Java 1.8 after install.

### ISSUE THREAD

**Issue by RoyRoebuckHM** [gephi/gephi#1987] opened 2018-06-30 18:27 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by RoyRoebuckHM** [comment] 2018-06-30 18:28
Win 10, 64bit
Using Java 8.

**Comment by eduramiba** [comment] 2018-06-30 18:35
Duplicate of #1787

**Closed by eduramiba** 2018-06-30 18:35 UTC
