### ISSUE TITLE
Gephi won't start up on Windows 10

### ISSUE THREAD

**Issue by 50stuck** [gephi/gephi#1111] opened 2015-08-31 14:13 UTC

**Comment by eduramiba** [comment] 2015-08-31 14:16
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-31 14:16 UTC

**Comment by LinhZZ** [comment] 2015-11-10 17:06
Gephi don't work with Jdk 8, download jdk 7 
And add this to config C:\Program Files (x86)\Gephi-0.8.2\etc\gephi.conf
# default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
jdkhome="C:\Program Files\Java\jdk1.7.0_79"

Hope this help
