### ISSUE TITLE
Doesn't open properly on Mac OSX Yosemite

### ISSUE THREAD

**Issue by dallas-techz** [gephi/gephi#1071] opened 2015-06-29 06:48 UTC
When I open Gephi, it simply opens the Splash Screen and says "loading cached objects" for a few seconds then it quits. That's it. Tried re-downloading it a couple times, tried putting it in my Applications folder, on my desktop, and I also tried just opening it from the mounted dmg. Nothing. Just the splash screen for a few seconds and then it quits.

**Comment by phines** [comment] 2015-06-30 16:56
Here is the workaround for this:
https://lbartkowski.wordpress.com/2014/11/28/gephi-0-8-2-on-apple-osx-yosemite/

The key is to install java 1.6, and then set gephi to use v1.6.  Gephi needs to be upgraded to work with newer versions of java...

**Comment by evolvedmicrobe** [comment] 2015-07-09 08:34
Yes, had same issue.  Fixed by following:

edit the file:
    /Applications/Gephi.app//Contents/Resources/gephi/etc/gephi.conf

To change the relevant line to: 
   jdkhome="$(/usr/libexec/java_home -v 1.6)"

In case someone else has the same issue (the step above was also mentioned in the wordpress blog, though they did several other things I didn't need to)

**Comment by eduramiba** [comment] 2015-08-26 15:53
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:53 UTC
