### ISSUE TITLE
Gephi failed importing the project java.util.zip.ZipException: zip file is empty

### ISSUE THREAD

**Issue by Ludette** [gephi/gephi#1825] opened 2017-10-22 05:25 UTC
## Expected Behavior
Previously saved Gephi project expected to import on file>open command. 
## Current Behavior
Import fails with the following error messages:
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:99)
Caused: org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: ZipException : zip file is empty
File: java.util.zip.ZipFile
Line : -2
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
## Possible Solution
Project had a filter on node degrees applied when saved and the error is replicated if this is repeated (details below).

## Steps to Reproduce

1. Add a filter to a graph project filters>topology>degree range>1 to 27>filter
2. Save the project (with a new file name).
3. Attempt to open the project: import fails.
4.

## Context
Unfortunately my graph project has become unopenable and further work on this project is not currently possible!

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: Windows

**Comment by eduramiba** [comment] 2017-10-22 17:51
Thanks for the bug report!

**Comment by Marmeladenbrot** [comment] 2020-03-25 13:34
Error seems to be still appear within temp files from gephi.

**Comment by jknightg1** [comment] 2021-11-11 09:46
I am also getting this message.
How can I resolve it please?

**Comment by mbastian** [comment] 2022-03-08 19:52
Hi, I was not able to reproduce this issue on the latest [0.9.3 nightly build](https://github.com/gephi/gephi#nightly-builds). We have made some improvements in the Gephi IO part so maybe this fixed this issue as well. I'm closing but feel free to reopen if the problem persists once you get to try the new version. Thx!

**Closed by mbastian** 2022-03-08 19:52 UTC
Labels: High, Import, Export

**Comment by zlashie** [comment] 2022-11-17 10:15
Hi. I have this same issue. Have a gephi file with a network I used for my master thesis in 2019 and now I cannot open it on my fresh install computer. I get 

"Gephi Failed importing the project
Exception: ZipException : Zip file is empty
File: java.util.zip.ZipFile$Source
Line: -1"

Please help me, I dont want to lose access to my master thesis data :-)
