### ISSUE TITLE
Not able to find the neo4j plugin in gephi 0.9.2

### ISSUE THREAD

**Issue by rameshthangam1** [gephi/gephi#1800] opened 2017-09-28 23:56 UTC
## Steps to Reproduce

1.Click for plugins under tools and select available plugins
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2017-09-29 07:16
Duplicate of #1404

**Closed by eduramiba** 2017-09-29 07:16 UTC

**Comment by syntheticperson** [comment] 2018-07-07 17:55
Will there be a neo4j plugin for gephi?
