### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by yunjhyunjh** [gephi/gephi#1874] opened 2017-12-13 11:22 UTC
## Expected Behavior
ㅇ I have downloaded gephi-0.9.2-windows sucessfully today but Gephi would not open main page !!

## Current Behavior
**ㅇ error message : "Cannot find java 1.8 or higher " 

enen though my notebook have already  Java8.0

please help me...^^**

![error msg](https://user-images.githubusercontent.com/34508017/33936467-eb82b250-e042-11e7-9ad7-cbdce751ef35.PNG)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java8.0
* Operating System: Windows 10 Enterprise

**Comment by eduramiba** [comment] 2017-12-13 11:23
Duplicate of #1787

**Closed by eduramiba** 2017-12-13 11:23 UTC

**Comment by yunjhyunjh** [comment] 2017-12-13 12:16
After installing Java 64bit version, error massage disappeared after all !!
