### ISSUE TITLE
Gephi graph background and scrolling issues

### ISSUE THREAD

**Issue by Gephifix** [gephi/gephi#2130] opened 2019-08-19 03:54 UTC
## Expected Behavior
Graph loads with white background.  Scrolling mouse wheel zooms in and out of groaph 

## Current Behavior
Graph loads with a black background.  The color change does not work.  Scrolling will zoom in on graph, but when zooming out the zoomed-in image remains with a zoomed out graph superimposed. 

## Steps to Reproduce

1. Open Gephi (Black background displays)
2. Open Les Miserables.gefx. (Displays graph on a black background)
3. Try to change the background color (Dims graph and does not change color)
4. Scroll in (graph gets larger and blinks)
5. Scroll out (graph scrolls out, but larger version remains)

## Context

I'm just trying to do my homework.

## Your Environment

Gephi Version: 0.9.2
OS: MS Windows Home 10 (64-bit)
Graphic card vendor: Intel
Graphic card model: Intel HD Graphics 520
Graphic card driver version: 22.20.16.4691   
Java version: jre1.8.0_221
OpenGl version: 4.4

**Comment by chasemc** [comment] 2019-09-06 20:26
Someone in our lab is having the same issue. I've used Gephi for several years, and helped others; I haven't encountered this issue before and am at a loss as to how to fix it.

**Comment by chasemc** [comment] 2019-09-06 20:26
Same as:
https://github.com/gephi/gephi/issues/2126

**Comment by Gephifix** [comment] 2019-09-06 20:49
chasemc.  My son let me borrow the gaming laptop I bought him last Christmas. It worked just fine.  I believe the problem was due to the low budget graphics processor on my old laptop.  It was more than enough for Excel and PowerPoint.  I got a new laptop with a dedicated card and Gephi is golden.  Good luck.

**Comment by eduramiba** [comment] 2019-09-07 10:09
Closing as duplicate of #2126 Hoping to be able to finish the new visualization engine to solve many of these problems.

**Closed by eduramiba** 2019-09-07 10:09 UTC
