### ISSUE TITLE
Trouble Exporting Animated, Dynamic Timeline

### ISSUE THREAD

**Issue by jrnewm001** [gephi/gephi#2153] opened 2019-11-13 16:22 UTC
## Expected Behavior
An ability to export a working short-to-medium length animation (.GIF, for example) file of a dynamic, changing network as illustrated via Gephi's timeline.

## Current Behavior
I cannot find an ability to do this- does it exist?

## Possible Solution
Is there any open-source software that can produce animations of any of the types of GRAPH files (.graphml, .gefx, .vna, etc.) exportable via GEPHI? Any help would be greatly appreciated.

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: MAC OSC

**Comment by eduramiba** [comment] 2019-11-14 09:13
Hi, This is not implemented yet.

**Comment by eduramiba** [comment] 2019-11-14 09:13
Marking as duplicate of #558

**Closed by eduramiba** 2019-11-14 09:13 UTC
Labels: Wishlist
