### ISSUE TITLE
most peripherical nodes get cut off when doing an svg export

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#534] opened 2012-02-27 11:38 UTC
When in the preview mode,
- do an svg export
=> in my case (a network laid out with Force Atlas, 200 nodes), the nodes situated near the periphery of the graph get cutoff at the export: They fall out of the scene in my svg file.

See this discussion in the forum for a user who experienced the same issue:
https://forum.gephi.org/viewtopic.php?f=4&t=1566&p=5708#p5708

Thx,

Clement

**Comment by mbastian** [comment] 2015-12-15 10:36
Duplicate of #572, fixed in #1209

**Closed by mbastian** 2015-12-15 10:36 UTC

**Comment by DataNinjaKUL** [comment] 2017-10-23 12:41
Hi,

A colleague of mine and I are still experiencing more or less the same problem. When generating an svg, the labels of the outer nodes are cut off. The options button to adjust the size of the image only works when selecting png as a file format (when selecting svg, all we get under 'options' is: 'scale stroke-width').
My colleague has version 0.9.1 and I have 0.9.2. 

I took a screenshot of the file in Gimp, because Github doesn't support svg files for upload...

Best,
Yanne

![test](https://user-images.githubusercontent.com/10865604/31889482-4b9e12f8-b800-11e7-865c-91f58394f69c.jpg)

**Comment by eduramiba** [comment] 2017-10-23 13:00
@DataNinjaKUL This is a known bug, but it can be easily adjusted in inkscape. It has an option to adjust canvas size to contain all elements.
