### ISSUE TITLE
Can't boot Gephi (OpenGl ES error) on 32bit and no detection of Java on 64bit

### ISSUE THREAD

**Issue by GabrielVarela** [gephi/gephi#1712] opened 2017-05-06 20:50 UTC
As mentioned in the title, can't seem to boot Gephi in either 32bit or 64bit on a windows 10 OS; The 32bit give me a OpenGL ES error: tried forcing it to use both integrated graphics (Intel 530) and dedicated gpu (Nvidia 960M) with the same result. 

On the other hand booting the 64bit version simply doesn't find java and asks me to install 1.7 or higher (I have Java 8 update 141 running)

Any ideas?

**Comment by JulesBuh** [comment] 2017-10-12 09:01
I have the same issue with on Window 7 Edition. I've tried reproducing the fixes mentioned in https://github.com/gephi/gephi/issues/1779 and https://github.com/gephi/gephi/issues/1724

**Comment by eduramiba** [comment] 2017-10-12 09:16
You can try to install a 64 bit version of Java if your OS is 64 bit

**Comment by JulesBuh** [comment] 2017-10-12 09:53
Yeah, I've done that and I've set the jdkhome parameter in the relevant .conf files. Still not working. I see the initial gephi splash screen and do notice a difference in the pixellation of the text when pointing it to the java directory. I was wondering if it is something to do with the system configuration of it maybe using the onboard graphics card rather than the Intel?

**Comment by JulesBuh** [comment] 2017-10-12 09:55
E.g when I disable the onboard graphics chip in the device manager, the screen resolution goes very low as if the intel card isn't configured to be  the primary graphics card.

**Comment by eduramiba** [comment] 2017-10-12 10:46
Well, it's always preferable that you use the the high performance graphics card instead of the intel one. Also make sure to update both graphics cards drivers. Also please attach any log files you can find in the gephi user directory https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by mbastian** [comment] 2022-05-15 18:30
Closing as since [version 0.9.5](https://github.com/gephi/gephi/releases/tag/v0.9.5) we're providing both a x64 and a x32 version of Gephi. That should solve this issue.

**Closed by mbastian** 2022-05-15 18:30 UTC
Labels: OpenGL, Java compatibility, Startup
