### ISSUE TITLE
Import wizard list is empty

### ISSUE THREAD

**Issue by slashdev0** [gephi/gephi#1531] opened 2016-07-05 10:59 UTC
Hello,
Right after downloading and installing Delphi 0.91 on windows 7 
![capturegephi](https://cloud.githubusercontent.com/assets/20298369/16582637/5b0bb518-42b0-11e6-8396-23714b37cff0.PNG)
; the import wizard list is empty.

**Comment by eduramiba** [comment] 2016-07-05 20:39
Duplicate of #1477 Please check that issue.

**Closed by eduramiba** 2016-07-05 20:39 UTC
