### ISSUE TITLE
Java 1.8

### ISSUE THREAD

**Issue by csb66emba17** [gephi/gephi#1835] opened 2017-11-07 05:26 UTC
1. Having problem opening Gephi 9.2. It is looking for the Java 1.8 although it is loaded already.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2017-11-07 07:40
Duplicate of #1787

**Closed by eduramiba** 2017-11-07 07:40 UTC
