### ISSUE TITLE
0.9.2 not recognizing Java install on Windows 10: returning error of Java 1.8 or later

### ISSUE THREAD

**Issue by codis1234** [gephi/gephi#1856] opened 2017-11-24 14:34 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2017-11-24 15:58
Duplicate of #1787

**Closed by eduramiba** 2017-11-24 15:58 UTC
