### ISSUE TITLE
Filter by partition has no effect

### ISSUE THREAD

**Issue by rmhorne** [gephi/gephi#1570] opened 2016-09-19 02:37 UTC
The Filter by partition does not seem to have any effect (Gephi remains responsive, however). I am Using 0.9.1 and the Les Miserables data. 

To replicate:
I added a column with random values (+, -) titled "relationship" on the edges table. The attribute "relationship" does show in the appearance dialog, as well as Filters -> Attributes -> Partition. However, clicking on either value does not change the appearance of the graph whatsoever (see images).
<img width="1552" alt="image1" src="https://cloud.githubusercontent.com/assets/3486040/18621353/f5de3c58-7def-11e6-9d79-7fd543d41dff.png">
<img width="1552" alt="image2" src="https://cloud.githubusercontent.com/assets/3486040/18621354/fbf33cce-7def-11e6-95b8-4426d0d16b31.png">

This may be peripherally related to #1309, as it is an issue with partitions.

**Comment by mbastian** [comment] 2016-10-24 21:26
Hi, this issue is a duplicate of #1564, should now be fixed (Check for updates)

**Closed by mbastian** 2016-10-24 21:26 UTC
Labels: Filters

**Comment by LittleRabbitHole** [comment] 2017-03-17 19:10
It doesn't work if export the filtered graph into new workspace
