### ISSUE TITLE
IllegalArgumentException: Node id=-1 is invalid / Caused: org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

### ISSUE THREAD

**Issue by ning1no** [gephi/gephi#2148] opened 2019-10-30 05:29 UTC
## Expected Behavior

Gephi to open the project.

## Current Behavior

Gephi doesn't open the project and I get this error:

java.lang.IllegalArgumentException: Node id=-1 is invalid
 at org.gephi.graph.impl.NodeStore.checkValidId(NodeStore.java:511)
 at org.gephi.graph.impl.NodeStore.get(NodeStore.java:117)
 at org.gephi.graph.impl.Serialization.deserializeEdge(Serialization.java:407)
 at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2050)
 at org.gephi.graph.impl.Serialization.deserializeGraphStore(Serialization.java:345)
 at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2062)
 at org.gephi.graph.impl.Serialization.deserializeGraphModel(Serialization.java:245)
 at org.gephi.graph.api.GraphModel$Serialization.read(GraphModel.java:135)
 at org.gephi.graph.GraphPersistenceProvider.readBytes(GraphPersistenceProvider.java:88)
 at org.gephi.project.io.LoadTask.readWorkspaceChildrenBytes(LoadTask.java:327)
 at org.gephi.project.io.LoadTask.run(LoadTask.java:130)
Caused: org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: IllegalArgumentException : Node id=-1 is invalid
File: org.gephi.graph.impl.NodeStore
Line : 511
 at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
 at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

## Possible Solution

No solution yet, have not found a way to open the project or at least to recover the data.

## Steps to Reproduce

1. I was using the Twitter Streaming Importer Plugin, had a database of around 14K nodes and 39K edges.
2. Copied the data from the lab to a new Workspace.
3. Gephi freezes and I force quit
4. The project got corrupted

## Context

I was graphing while I was using the Twitter Streaming Importer, Gephi crashed and couldn't open the project later. (I saved before making any new changes so the file was sould be a version prior to the crash)

Here is the file in case someone can help me recover the data: http://oahacka.mx/nube/index.php/s/KT9Nacx4PQaemzo 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java 8 Update 221
* Operating System: Mac OSX 10.13.6

**Comment by wetneb** [comment] 2021-12-02 10:41
Duplicate of #1982.

**Closed by wetneb** 2021-12-02 10:41 UTC
Labels: To review
