### ISSUE TITLE
Cannot find Java 1.8 or higher

### ISSUE THREAD

**Issue by Philippe153** [gephi/gephi#1880] opened 2017-12-18 15:21 UTC
## My Environment:
* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: Windows 10 64 bits

## I have read solutions to this problem. However none seems dedicated to basic users like me. Could you please explain from A to Z what to do to solve the issue?
Thank you

**Comment by eduramiba** [comment] 2017-12-18 15:22
Duplicate of #1787

**Closed by eduramiba** 2017-12-18 15:22 UTC

**Comment by Philippe153** [comment] 2017-12-18 15:24
Thank you Eduramiba, but this is precisley what I do not understand. What is netbeans etc... how to get there... sorry for my ignorance.

**Comment by eduramiba** [comment] 2017-12-18 15:27
Gephi is based on the Netbeans platform, but you should not care about that. Just follow the suggested fixes at #1787 by making sure the correct java version is installed, or locating the gephi.conf file in the Gephi installation directory and making the changes.

You should try the Java change first (latest Java 8, Java 64 bit version for 64 bit OS, etc).

**Comment by Philippe153** [comment] 2017-12-18 15:33
Thank you, I will look for this directory (where?) (Java 8 is installed, but I will verify)

**Comment by eduramiba** [comment] 2017-12-18 15:34
Gephi is usually shows you the install directory when running the installer (do you use Windows?).
It should probably by ```C:\Program Files\Gephi``` or similar

**Comment by Philippe153** [comment] 2017-12-18 15:39
Found it. Thank you

**Comment by Philippe153** [comment] 2017-12-18 15:48
I have found the gephi.conf file, opened it, ... what should I do next?

**Comment by eduramiba** [comment] 2017-12-18 15:51
Did you first make sure you have Java 8 (not 7 or 9) and it's 64 bit?

If still not working, open gephi.conf file and point jdkhome to where your java is installed just as explained in #1787

**Comment by Philippe153** [comment] 2017-12-18 16:04
Thanks again. I will do my home work!

**Comment by vamsikrishnasabbisetty** [comment] 2018-04-12 19:28
The following resolved my Issue:

1) uninstall older versions of java
2) Installed Java 8
3) Updated jdk path to jdkhome="C:\Program Files\Java\jre1.8.0_161"  in gephi.conf (etc folder)

**Comment by Elwinlhq** [comment] 2018-04-30 18:42
I resolved doing this:
- Updated  jdk path to jdkhome="C:\Program Files\Java\jre-10.0.1" in gephi.conf (etc folder)

**Comment by namjoo** [comment] 2020-10-02 09:41
My gre was old and install new version
