### ISSUE TITLE
NOT operator in filters doesn´t seem to work

### ISSUE THREAD

**Issue by fescalantel** [gephi/gephi#998] opened 2015-01-14 11:35 UTC

**Comment by zemlyanskiy** [comment] 2015-09-25 11:57
![img-2015-09-25-20-55-23](https://cloud.githubusercontent.com/assets/10767123/10099775/6ad83d16-63bf-11e5-90a3-9c99eee0806b.png)
Confirm, filter doesn't work

**Comment by mbastian** [comment] 2015-11-21 16:54
Duplicate of issue #750

**Closed by mbastian** 2015-11-21 16:54 UTC
