### ISSUE TITLE
I downloaded Gephi to my computer which is running Windows 7.  When I try to open Gephi it is showing the intial load screen and states "loading cached objects", however after that the program never opens...

### ISSUE THREAD

**Issue by dish084** [gephi/gephi#1009] opened 2015-02-09 01:56 UTC
I downloaded Gephi to my computer which is running Windows 7.  When I try to open Gephi it is showing the intial load screen and states "loading cached objects", however after that the program never opens

**Comment by srdyal** [comment] 2015-02-09 19:01
I am having the same problem, Gephi used to run on my windows 7 computer and now I can only get the "loading cached objects" screen. I cannot get the program to open. I tried uninstalling and re-installing it, and updated java, but it will not run.

**Comment by Who8MyLunch** [comment] 2015-02-12 22:09
I too have seen the same problem.  Windows 8.1 x64.

**Comment by williballenthin** [comment] 2015-02-16 20:59
Have you upgraded to Java 8? I see the same issue when using Java 8, but when reverting to Java 7, Gephi starts up just fine.

See #997

**Comment by jackiekazil** [comment] 2015-03-08 21:05
More help with how to do the reverting... https://medium.com/coder-snorts/gephi-is-broken-on-mac-os-97fbaef4305e

**Comment by eduramiba** [comment] 2015-08-26 16:07
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:07 UTC
