### ISSUE TITLE
Gephi does not run 0 Cannot Find Java 1.8 or higher

### ISSUE THREAD

**Issue by IanMcCrabb** [gephi/gephi#1961] opened 2018-05-02 06:19 UTC
## Expected Behavior
Run Gephi

## Current Behavior
Doesn't run 
Get Error message Cannot Find Java 1.8 or higher

## Steps to Reproduce

1.  Install Gephi
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 171
* Operating System: Windows 10

**Comment by eduramiba** [comment] 2018-05-02 08:47
Duplicate of #1787

**Closed by eduramiba** 2018-05-02 08:47 UTC
