### ISSUE TITLE
Activating Labels gephi crashes

### ISSUE THREAD

**Issue by alexpGH** [gephi/gephi#1574] opened 2016-09-25 10:57 UTC
start gephi, open lesMiserables sample (or others), expand visulaisation details, select table Label, check Node -> gephi crashes

precompiled 0.9.1, 0.9.2-Snapshot and locally compiled 0.9.1 from sources with OpenJDK Runtime Environment (7.0_111-b01) or oracle jdk1.8.0_20 and oracle 1.8.0_20.

[hs_err_pid25676log.txt](https://github.com/gephi/gephi/files/491595/hs_err_pid25676log.txt)

[INFO] # JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
[INFO] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
[INFO] # Problematic frame:
[INFO] # C  [libc.so.6+0x123305]

on debian wheezy

**Comment by eduramiba** [comment] 2016-09-26 08:10
Hi,
Please try to use Oracle JDK and/or update your graphic card drivers.
If that does not help, try to run gephi with `LIBGL_ALWAYS_SOFTWARE=1 ./gephi`

**Comment by eduramiba** [comment] 2016-10-23 10:47
Dit it work?

**Comment by alexpGH** [comment] 2016-12-19 07:16
Sorry for the late response.
No it didn't. I switched to a new machine with a newer debian on it. It seems to be an issue with the graphics card drivers...

**Comment by eduramiba** [comment] 2016-12-19 08:48
Great! I am closing this one as there are many other issues caused by bad graphic drivers.

**Closed** 2016-12-19 08:49 UTC

**Comment by 7beggars** [comment] 2022-01-02 20:24
> Dit it work?

making `LIBGL_ALWAYS_SOFTWARE=1 gephi` rather of the `LIBGL_ALWAYS_SOFTWARE=1 ./gephi` works to me on my two laptop's with OS arch linux. rhanks!
