### ISSUE TITLE
Not running at all

### ISSUE THREAD

**Issue by shaneburger** [gephi/gephi#1139] opened 2015-09-30 20:15 UTC
I have installed it on both Win7 and OSX. The splash screen launches, but then nothing.
Is there something I am missing?

**Comment by eduramiba** [comment] 2015-09-30 22:30
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac

For Windows check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Closed by eduramiba** 2015-09-30 22:30 UTC
