### ISSUE TITLE
Not starting at all on MAC OSx 10.10.3

### ISSUE THREAD

**Issue by neptun2000** [gephi/gephi#1054] opened 2015-05-15 09:37 UTC
I see the logo and "Loading Cached objects"
and next thing app closing(crashing)

**Comment by eduramiba** [comment] 2015-08-26 16:03
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:03 UTC
