### ISSUE TITLE
MacOS Java Version Issues

### ISSUE THREAD

**Issue by daidong** [gephi/gephi#912] opened 2014-05-01 21:31 UTC
Hi, It seems to me that Gephi can not run properly with Java 1.7 on Mac OS 10.9. There is a solution that downgrade the java version, which i did and worked. However, the neo4j plugin requires Java 1.7 to run. This puts me in a dilemma. :) 

Is there anyway i can both use Gephi and Neo4j on my laptop? Thanks very much!

**Comment by eduramiba** [comment] 2015-08-26 15:57
Duplicate of #748 

Sorry, the problem with neo4j and mac os is really bad since it requires Java7.

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:57 UTC
