### ISSUE TITLE
Unable to launch Gephi

### ISSUE THREAD

**Issue by annecc** [gephi/gephi#910] opened 2014-04-24 21:20 UTC
I tried to increase my Gephi memory in gephi.conf, but realized that I needed to switch my gephi to operate on 64-bit. This lead to me not being able to load gephi. 

I have tried uninstalling and deleting all the hidden files but it is still not launching.

**Comment by eduramiba** [comment] 2015-08-26 17:00
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:00 UTC
