### ISSUE TITLE
Gephi won't close on OS X

### ISSUE THREAD

**Issue by nalice** [gephi/gephi#728] opened 2013-01-24 20:10 UTC
Any time I quit Gephi (whether explicitly or as part of an automatic restart after a plugin update), all of the windows close, but the program never terminates. Eventually it shows up as "not responding" in the Activity Monitor. It doesn't appear to be using any CPU cycles or reading from or writing to the disk. This behavior just started after updating to 0.8.2.

OS: OS X 10.8.2
Java Version: 1.7.0_09, 64-bit
Gephi: 0.8.2

**Comment by eduramiba** [comment] 2015-08-26 16:22
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:22 UTC

**Comment by KarAnalytics** [comment] 2020-04-03 08:44
A temporary fix in case you want to reopen the Gephi software. Just go to /Applications/gephi.app/Contents/MacOS/gephi 
This opens for some reason. You can do your analysis as usual even if the other gephi program is unresponsive. Restarting the system resolves it, but there should be a better way to resolve this issue.
