### ISSUE TITLE
Unable to find Java 1.8 or higher

### ISSUE THREAD

**Issue by 4uatgithub** [gephi/gephi#1918] opened 2018-02-28 04:33 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2018-02-28 07:45
Duplicate of #1787

**Closed by eduramiba** 2018-02-28 07:45 UTC
