### ISSUE TITLE
[Feature request ?] Label wordwrap OR Label multiline support

### ISSUE THREAD

**Issue by DirectuX** [gephi/gephi#1368] opened 2016-02-10 08:19 UTC
Hello, 

would these features be available ?

- **sizing and word-wrapping the text** of a label to fit the shape of the node (one can choose the words separator)

-  **word-wrapping the text** of a label to mimic the shape of the node and **size the node** to box the amount of text inside

OR

at least take in consideration a way to have carriage returns in labels

Thanks

**Comment by mbastian** [comment] 2016-02-18 22:24
Duplicate of #787

**Closed by mbastian** 2016-02-18 22:24 UTC
