### ISSUE TITLE
Selecting the Data Laboratory freezes up Gephi

### ISSUE THREAD

**Issue by acer9997** [gephi/gephi#882] opened 2014-01-28 09:38 UTC
Whenever I click the Data Laboratory, Gephi freezes up. 

I'm not sure how to troubleshoot the software. 

My machine is running OS X 10.9.1, and the java -version output is: 
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by eduramiba** [comment] 2015-08-26 17:07
Probable duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:07 UTC
