### ISSUE TITLE
Gephi for OS X

### ISSUE THREAD

**Issue by Kyurkchieva** [gephi/gephi#875] opened 2014-01-10 12:22 UTC
Hello, 

I just decided to try gephi on my Mac, but for some reason after I download the dmg file it open the gephi icon and nothing happens upon further clicks, no issues appear and I cannot think of anything that might cause the problem ( all my software is up to date)

Any ideas?
Thanks!
Borislava

**Comment by eduramiba** [comment] 2015-08-26 17:09
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:09 UTC
