### ISSUE TITLE
Gephi 0.9 hangs when filtering by Partition > Modularity Class

### ISSUE THREAD

**Issue by Snurb** [gephi/gephi#1309] opened 2016-01-21 07:08 UTC
Hi,

Gephi 0.9 becomes unresponsive after dragging the Attributes > Partition > Modularity Class (Node) filter onto the 'Drag filter here' target. I'm not getting any Java errors - it simply stops responding, while Java continues to generate CPU load.

This is for a reasonably large network (294k nodes, 534k edges), on a fairly powerful Windows machine (Intel i7, 16GB RAM), so I don't think it's simply a lack of processing power.

I can provide the .gephi or .gexf file (.gexf doesn't seem to preserve partition information fully, though) - but not publicly, given the nature of the underlying data.

Many thanks in advance,

Axel Bruns

**Comment by mbastian** [comment] 2016-01-21 07:37
Hi, thanks for the report. That might be a bug that reveals itself only with large networks indeed. Would love to try on my own if you don't mind sending me your ..gephi file at mathieu.bastian [at] gephi.org

Thanks

**Comment by mbastian** [comment] 2016-02-03 10:32
I haven't succeeded to reproduce this issue so far. We've made updates available that fixed some appearance issues that might be related. Can you try again after updating (Help > Check for Updates)? Thanks!

**Comment by 3ruce** [comment] 2016-02-07 10:57
Likewise, I have this problem in 0.9.0 but using partitions in 0.8.2 is fine. I've tried Windows with the latest version of Java and on Ubuntu I've tried Oracle Java 7 and 8, along with OpenJDK 7 and Gephi always hangs when trying to partition in version 0.9.0. The network has c. 200 nodes and 20,000 edges.

**Comment by 3ruce** [comment] 2016-02-09 09:33
I wonder if this bug is related to this workaround I have to use to get Gephi to run either 0.8.2 or 0.9.0?

https://github.com/gephi/gephi/issues/1192#issuecomment-179088499

**Comment by 3ruce** [comment] 2016-02-29 08:44
Here are the first few lines of the error message in the logs that I get when trying to partition a graph via node attributes. I can send the full log file too if that helps?

```
INFO [DefaultProcessor]: # Nodes loaded: 229
INFO [DefaultProcessor]: # Edges loaded: 14,319
INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled
SEVERE [global]
java.lang.NullPointerException
	at org.gephi.ui.filters.plugin.partition.PartitionPanel$PartWrapper.toString(PartitionPanel.java:203)
	at javax.swing.DefaultListCellRenderer.getListCellRendererComponent(DefaultListCellRenderer.java:151)
	at org.gephi.ui.filters.plugin.partition.PartitionPanel$1.getListCellRendererComponent(PartitionPanel.java:92)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
```

**Comment by tw41** [comment] 2016-05-03 19:23
Hi - I'm also experiencing this issue.  I have all of the updates, and when I try to run the modularity gephi (0.9.1) hangs.  Has there been an update since late february?

**Comment by 3ruce** [comment] 2016-05-04 06:29
I've tried running 0.9.2 SNAPSHOT and had the same problem... what format is the data you're importing and how big is your graph?

**Comment by kbesserud** [comment] 2016-07-17 15:21
I have a graph with about 1900 nodes and 60,000 edges. Hangs when I try to run Modularity.

**Comment by mbastian** [comment] 2016-08-28 13:19
Hi, @tw41 and @kbesserud if your issue is modularity hanging please open another issue as this issue is related to filtering with partiiton.

**Comment by mbastian** [comment] 2022-05-15 18:25
Closing as the 0.9.3 version came with many core changes in the Appearance core module, with a focus on reliability. So most likely this is fixed. If not, feel free to reopen.

**Closed by mbastian** 2022-05-15 18:25 UTC
Labels: Appearance
