### ISSUE TITLE
Won't load in Ubuntu 15, jre1.8.0_60

### ISSUE THREAD

**Issue by Geof23** [gephi/gephi#1109] opened 2015-08-28 23:50 UTC
sawaya@bihexal:~/software/gephi/bin$ ./gephi --help --jdkhome ~/software/jre1.8.0_60/
Usage: ./../platform/lib/nbexec {options} arguments

General options:
  --help                show this help 
  --jdkhome <path>      path to Java(TM) 2 SDK, Standard Edition
  -J<jvm_option>        pass <jvm_option> to JVM

  --cp:p <classpath>    prepend <classpath> to classpath
  --cp:a <classpath>    append <classpath> to classpath
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:423)
	at org.openide.util.WeakListenerImpl.create(WeakListenerImpl.java:164)
	at org.openide.util.WeakListeners.create(WeakListeners.java:271)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:125)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:142)
	at org.openide.filesystems.MultiFileSystem.getMultiRoot(MultiFileSystem.java:267)
	at org.openide.filesystems.MultiFileSystem.findResource(MultiFileSystem.java:355)
	at org.openide.filesystems.FileUtil.getConfigFile(FileUtil.java:2276)
	at org.openide.filesystems.FileUtil.getConfigRoot(FileUtil.java:2306)
	at org.netbeans.core.startup.CLICoreBridge.usage(CLICoreBridge.java:107)
	at org.netbeans.CLIHandler.showHelp(CLIHandler.java:162)
	at org.netbeans.CLIHandler.checkHelp(CLIHandler.java:216)
	at org.netbeans.CLIHandler.initialize(CLIHandler.java:567)
	at org.netbeans.CLIHandler.initialize(CLIHandler.java:383)
	at org.netbeans.MainImpl.execute(MainImpl.java:190)
	at org.netbeans.MainImpl.main(MainImpl.java:85)
	at org.netbeans.Main.main(Main.java:78)
Caused by: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:412)
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:413)
	... 16 more

**Comment by Geof23** [comment] 2015-08-29 00:03
Sorry, this is with gephi 0.8.2.  Probably due to the Java version

**Comment by eduramiba** [comment] 2015-08-29 09:32
Duplicate of #748

**Closed by eduramiba** 2015-08-29 09:32 UTC

**Comment by Geof23** [comment] 2015-08-29 17:32
Eduardo, how is this the same as '... Broken in OS X 10...
 w/ Java 7?

It does work with Java 7-64 on my system. Which is no longer supported!

Are you guys not supporting Java 8?

**Comment by eduramiba** [comment] 2015-08-30 11:19
Hi,

The Windows and OSX bugs are caused by similar reasons (changes in recent java versions that break Gephi), so we are grouping both in #748 for reference.

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Comment by Geof23** [comment] 2015-09-03 21:22
Ok thanks for the explanation. Eduardo

Best regards
