### ISSUE TITLE
Nobody can register at Gephi official forum

### ISSUE THREAD

**Issue by asvc** [gephi/gephi#1038] opened 2015-03-30 07:14 UTC
Because everyone is marked as spammer due to this: http://www.ahbl.org/content/last-notice-wildcarding-services-jan-1st

**Comment by drevicko** [comment] 2015-05-31 08:43
This is duplicated in #1047

**Comment by mbastian** [comment] 2016-02-18 22:16
Closing as duplicate of #1047

**Closed by mbastian** 2016-02-18 22:16 UTC
