### ISSUE TITLE
I can't get Gephi to work on my Mac

### ISSUE THREAD

**Issue by ekmmurphy** [gephi/gephi#1068] opened 2015-06-22 17:27 UTC
Hi,

I have tried downloading both 0.8.2 and 0.8.1 versions of Gephi and although it appears to download and the app is in my Applications folder, every time I double click it, it immediately closes down. No windows open, and nothing happens. 
So hopefully to clarify - the following window opens (see screenshot) but then the app immediately shuts down after I press 'open'? 
Any advice gratefully received - am quite new to apple and not particularly tech savvy.
![screen shot 2015-06-22 at 18 26 02](https://cloud.githubusercontent.com/assets/10853650/8288149/3c8d166e-190c-11e5-892e-f40189fb177f.png)

**Comment by queenBNE** [comment] 2015-06-26 04:11
I had the same issue, see https://github.com/gephi/gephi/issues/997

**Comment by eduramiba** [comment] 2015-08-26 15:56
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:56 UTC
