### ISSUE TITLE
I layout a graph manually ,the graph does not display.

### ISSUE THREAD

**Issue by aoyuanbo** [gephi/gephi#1785] opened 2017-09-19 07:45 UTC
## Expected Behavior
 **I layout a graph manually, the graph does not display**.

ForceAtlasLayout layout=new ForceAtlasLayout(null);
       
 layout.setGraphModel(graphModel);
        
layout.setSpeed(50D);
        
layout.setGravity(10.0d);
       
 layout.initAlgo();
        
for (int i = 0; i < 200 && layout.canAlgo(); i++) {
           
 layout.goAlgo();
       
 }
       
 layout.endAlgo();
## Possible Solution
**I layout a graph automatically,it`s ok**.

`        
AutoLayout autoLayout = new AutoLayout(20, TimeUnit.SECONDS);
       
 autoLayout.setGraphModel(graphModel);
       
 ForceAtlasLayout secondLayout = new ForceAtlasLayout(null);
       
 AutoLayout.DynamicProperty adjustBySizeProperty = AutoLayout.createDynamicProperty("forceAtlas.adjustSizes.name", Boolean.TRUE, 0.1f);//True after 10% of layout time
       
 AutoLayout.DynamicProperty repulsionProperty = AutoLayout.createDynamicProperty("forceAtlas.repulsionStrength.name", new Double(500.), 0f);//500 for the complete period
        
autoLayout.addLayout(secondLayout, 1f, new AutoLayout.DynamicProperty[]{adjustBySizeProperty, repulsionProperty});
       
 autoLayout.execute();`

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:windows 7

**Comment by eduramiba** [comment] 2017-09-19 09:18
I think this might be bug https://github.com/gephi/gephi/issues/603

**Comment by eduramiba** [comment] 2017-09-19 09:18
Please test setting random positions or use 0.9.2-SNAPSHOT

**Comment by aoyuanbo** [comment] 2017-09-20 01:05
ok,I will have a try.

**Comment by eduramiba** [comment] 2017-09-20 07:56
Great, please report results

**Comment by aoyuanbo** [comment] 2017-09-21 02:27
I have tried  with 0.9.2-SNAPSHOT ,it does not still display.

**Comment by eduramiba** [comment] 2017-09-24 09:28
What's the rest of your code? Can you provide the full code and data to reproduce?

**Comment by eduramiba** [comment] 2017-10-25 21:12
Did it work with 0.9.2 release?

**Comment by aoyuanbo** [comment] 2017-10-26 00:38
font{
        line-height: 1.7;
    }


    
With 0.9.2 toolkit, it still does not work.



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 10/26/2017 05:12，Eduardo Ramos<notifications@github.com> wrote： 


Did it work with 0.9.2 release?

**Comment by sfc-gh-gmullen** [comment] 2021-11-09 20:35
I am seeing this same issue. Seems like the RandomLayout works, but YifanHuLayout, FruchtermanReingold and others don't manipulate the underlying X/Y values. Even when manually running the RandomLayout first to force non-zeros, the other Layouts don't change the X/Ys.

**Comment by sfc-gh-gmullen** [comment] 2021-11-09 21:07
`package NetworkBuilder;

import org.gephi.graph.api.*;
import org.gephi.layout.plugin.force.StepDisplacement;
import org.gephi.layout.plugin.force.yifanHu.YifanHuLayout;
import org.gephi.project.api.ProjectController;
import org.gephi.project.api.Workspace;
import org.openide.util.Lookup;


public class buildNetwork {


 public static void main(String[] args) {
     //Init a project - and therefore a workspace
     ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
     pc.newProject();
     Workspace workspace = pc.getCurrentWorkspace();

     //Get a graph model - it exists because we have a workspace
     GraphModel graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel(workspace);

     //Create three nodes
     Node n0 = graphModel.factory().newNode("n0");
     n0.setLabel("Node 0");
     Node n1 = graphModel.factory().newNode("n1");
     n1.setLabel("Node 1");
     Node n2 = graphModel.factory().newNode("n2");
     n2.setLabel("Node 2");

     //Create three edges
     Edge e1 = graphModel.factory().newEdge(n1, n2, 0, 1.0, true);
     Edge e2 = graphModel.factory().newEdge(n0, n2, 0, 2.0, true);
     Edge e3 = graphModel.factory().newEdge(n2, n0, 0, 2.0, true);   //This is e2's mutual edge

     //Append as a Directed Graph
     DirectedGraph directedGraph = graphModel.getDirectedGraph();
     directedGraph.addNode(n0);
     directedGraph.addNode(n1);
     directedGraph.addNode(n2);
     directedGraph.addEdge(e1);
     directedGraph.addEdge(e2);
     directedGraph.addEdge(e3);

     //Count nodes and edges
     System.out.println("Nodes: " + directedGraph.getNodeCount() + " Edges: " + directedGraph.getEdgeCount());

     //Get a UndirectedGraph now and count edges
     UndirectedGraph undirectedGraph = graphModel.getUndirectedGraph();
     System.out.println("Edges: " + undirectedGraph.getEdgeCount());   //The mutual edge is automatically merged

     //Iterate over nodes
     for (Node n : directedGraph.getNodes()) {
         Node[] neighbors = directedGraph.getNeighbors(n).toArray();
         System.out.println(n.getLabel() + " has " + neighbors.length + " neighbors");
     }

     //Iterate over edges
     for (Edge e : directedGraph.getEdges()) {
         System.out.println(e.getSource().getId() + " -> " + e.getTarget().getId());
     }

     //Find node by id
     Node node2 = directedGraph.getNode("n2");

     //Get degree
     System.out.println("Node2 degree: " + directedGraph.getDegree(node2));

     YifanHuLayout layout = new YifanHuLayout(null, new StepDisplacement(1f));
     layout.setGraphModel(graphModel);
     layout.resetPropertiesValues();
     layout.initAlgo();
     for (int i = 0; i < 100 && layout.canAlgo(); i++) {
         layout.goAlgo();
     }
     layout.endAlgo();

     for (Node n : directedGraph.getNodes()) {
         //Note that X/Y values do not change after layout has been run
         System.out.println(n.x() + "," +n.y());
     }
 }
}
`

**Comment by mbastian** [comment] 2022-12-30 13:57
There are two issues referred in this thread:
- For the original request from @aoyuanbo I think the root cause of this issue is not calling the `layout.resetPropertiesValues()` method upon initialisation. For some layouts like Force Atlas, some properties are only get assigned by this method. For instance, if not defined a `cooling` of zero will produce NaN (division by zero)
- For @sfc-gh-gmullen's issue the root cause is most likely not having initial random positions. Some layouts deal with that but some others might not. If all positions are zero it can create an edge case in how the layouts work so I would recommend assigning first a random X/Y position.

Closing the thread but please reopen if it doesn't solve it.

**Closed by mbastian** 2022-12-30 13:57 UTC
Labels: Layouts
