### ISSUE TITLE
Gephi 0.8.2 doesn't start correctly on Mac 10.9.5

### ISSUE THREAD

**Issue by mvanwely** [gephi/gephi#973] opened 2014-11-06 05:19 UTC
Gephi 0.8.2 doesn't start properly on my Mac.  I had to switch the JDK to Java6 and it still fails.  Reverting to Gephi 0.8 allows the app to start.

Windows says "Opening Main Window" then does nothing.  Also, many of the file menu options are missing.

**Comment by jackiekazil** [comment] 2015-03-04 03:43
Java 1.6 fixed it for me: https://medium.com/notes-from-computational-social-science/gephi-is-broken-on-mac-os-97fbaef4305e

**Comment by eduramiba** [comment] 2015-08-26 16:10
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:10 UTC
