### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by GrimPixel** [gephi/gephi#2433] opened 2022-02-26 09:09 UTC
## Expected Behavior

Starts like normal.

## Current Behavior

Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

## Steps to Reproduce

1. Download from the website or install from Arch repository
2. Open it from terminal

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 13
* Operating System: Arch Linux

**Comment by navalinovian** [comment] 2022-03-04 12:48
duplicate of https://github.com/gephi/gephi/issues/2242

**Closed** 2022-11-08 21:00 UTC
Labels: To review
