### ISSUE TITLE
Crach when loadin Gephi

### ISSUE THREAD

**Issue by astucieuxzephyr** [gephi/gephi#1034] opened 2015-03-18 18:34 UTC
hi,
I got a crash when loading Gephi 0.8.2-beta (last version).
The beginning image appears then disappears, and it seems Gephi crashes..
I don't know what to do to make it working.

I'm under Windows 7 Family Premium 64 bits 
Intel Core i7 CPU @2.1 GHz with 8Mo RAM
Video Card : NVidia GeForce GT 640M with last drivers (347.88)

On the Windows Command Line (cmd) when I type **java -version** I get :

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) Client VM (build 25.40-b25, mixed mode)

Thank you for your help.

**Comment by eduramiba** [comment] 2015-08-26 16:51
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:51 UTC
