### ISSUE TITLE
A java.lang.RuntimeException exception has occurred

### ISSUE THREAD

**Issue by koko12131** [gephi/gephi#2199] opened 2020-07-08 03:20 UTC
## Context
when i try to open a file.graphml ,  gephi raise an error like this
![image](https://user-images.githubusercontent.com/32886492/86870961-ee989700-c10b-11ea-8d48-ee377b1cae8b.png)
i've tried to modify the etc\gephi.conf   default_options="--branding gephi -J-Xms1024m -J-Xmx1300m -J-Xverify".... to give gephi more space to run, but i still cannot open the file.graphml. i checked the file.graphml which was created properly. the file like this
[mobile_ic.zip](https://github.com/gephi/gephi/files/4888236/mobile_ic.zip)

so what can i do next?

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_241
* Operating System: windows10_x64

**Comment by mbastian** [comment] 2021-12-23 13:29
Hi, unfortunately I can't open this ZIP file it says corrupted. Could you please provide the file again - otherwise I can't reproduce the issue. Thank you

**Comment by mbastian** [comment] 2022-03-01 19:38
As I didn't hear back I'll close this one. Feel free to reopen when needed.

**Closed by mbastian** 2022-03-01 19:38 UTC
Labels: Awaiting for response, Import
