### ISSUE TITLE
Size ranking by Betweeness Centrality not possible

### ISSUE THREAD

**Issue by kennell** [gephi/gephi#1549] opened 2016-07-30 15:19 UTC
Gephi version: 0.9.1 on OSX, installed via Homebrew

After importing my CSV file with Edge data and running the Network Diameter statistics on the Graph, i want to rank the Nodes in size depending on their Betweeness Centrality, however the Attribute is not available in the Size tab. It is however available in the Color Raking tab.

Available in Color Tab:
![Available in Color Tab](http://i.imgur.com/NxRD3OI.png) 

Not available in Size tab:
![Not available in Size tab](http://i.imgur.com/V2lQHf1.png)

**Comment by eduramiba** [comment] 2016-07-30 15:21
Please check issue #1459 for a workaround.
I close this as a duplicate of #1459

**Closed by eduramiba** 2016-07-30 15:21 UTC
