### ISSUE TITLE
Unable to filter by edge attributes

### ISSUE THREAD

**Issue by olgabaranov** [gephi/gephi#2096] opened 2019-04-04 14:01 UTC
## Expected Behavior
Ability to filter the network by node and edge attributes alike (pretty sure that worked once)

## Current Behavior
Only node attributes are displayed in Attributes -> Partition 
![Selection_093](https://user-images.githubusercontent.com/8818141/55561559-a7df1480-56f2-11e9-8f6e-0ac19196f411.png)

even though the edge attributes are sown in the data table
![Selection_094](https://user-images.githubusercontent.com/8818141/55561622-c0e7c580-56f2-11e9-8fea-7eff9da7add6.png)

## Steps to Reproduce

1. Load a (4000 nodes, 25000 edges) network into gephi
2. Go to the Filters sub-window
3. Go to attributes -> Partition 
4. No edge attributes are available for filtering

## Context
I am pretty sure that I have seen edge filters on fist start of Ghphi. But after I reloaded the graph, those options were gone. They aren't there in the 0.9.2 version as well as the nightly build

## Your Environment

* Version used: Gephi 0.9.3 Snapshot
[messages.log](https://github.com/gephi/gephi/files/3043791/messages.log)

Any help is very appreciated!

**Comment by Jennie1021** [comment] 2019-12-09 07:50
struggling with the same problem right now.. did you solve it ?

**Comment by olgabaranov** [comment] 2019-12-09 10:48
No, sorry. Gave up on it. Eventually I filtered edges in python and created a new network.

**Comment by Jennie1021** [comment] 2019-12-10 00:13
Thanks for the quick responding! I actually somehow solved the problem by closing gephi program itself and opened it again. And the edge attributes popped up, maybe you can try it later :)

**Comment by gfgadvisory** [comment] 2020-12-30 13:01
I'm having trouble with this same issue.  Is there a way to filter edges in the overview tab based on attributes?  Any help would be really appreciated.  Thanks!

**Comment by Jennie1021** [comment] 2021-01-04 02:41
> I'm having trouble with this same issue. Is there a way to filter edges in the overview tab based on attributes? Any help would be really appreciated. Thanks!

I think it depends on the edge attribute type, go Window - Filter - Library - Attributes - Choose any filter function (Range or Equal or Partition etc..) and there should be attributes you import

**Comment by paulgirard** [comment] 2021-08-04 10:45
From my experience, the issue exist when you opened a graph file like a gexf for instance.
If you save you network as a gephi file and then reopen it, the filters on edge attribute appears.
Hope this can help others.

**Comment by mbastian** [comment] 2022-03-08 19:47
Hi, I was not able to reproduce this issue on the latest [0.9.3 nightly build](https://github.com/gephi/gephi#nightly-builds). We've made some improvements to both the filter and the appearance engines so maybe this issue was also fixed. I'm closing the issue but feel free to reopen if it still occurs.

**Closed by mbastian** 2022-03-08 19:47 UTC
Labels: Filters, IO
