### ISSUE TITLE
No custom node labels visible in preview/ exported visualizations (Gephi 0.9)

### ISSUE THREAD

**Issue by kooelo** [gephi/gephi#1333] opened 2016-02-03 08:35 UTC
Hi!

I have a graph using custom columns for node labels. I have selected the correct columns and they are visible in the graph window. However, if I switch to Preview (or try to export) my visualizations, no node labels are visible. The only way to get the custom labels shown in Preview/ exported graphs is to copy the values to 'Label' column.

I use Gephi 0.9 on different Linux machines. All used Linux systems (Ubuntu, opensSuSE) are affected by this bug.

Can anyone confirm this?

**Comment by mbastian** [comment] 2016-02-03 16:26
Hum curious I can't reproduce this issue. Does it happen with specific graphs? Does it work with the samples graphs?

**Comment by hpiedcoq** [comment] 2016-02-06 18:28
Same issue for me on Mac.

**Comment by kooelo** [comment] 2016-02-19 12:34
Hi!

Tested with "Les mirables" from the Gephi homepage and with it custom labels worked just fine. When tried again with different own Gephi projects - no custom labels visible in preview/export. Odd... As soon as custom labels are copied to "Label" field, they appear in the preview.

And yes: I have checked the right fields in "Label text settings" :)

**Comment by kooelo** [comment] 2016-03-20 09:30
The problem still persists. Any ideas from the developers??

**Comment by mbastian** [comment] 2016-04-16 07:54
Hi @kooelo Could you attach or send me (mathieu.bastian [at] gephi.org) a file that doesn't work for you? Thanks.

**Comment by jeffalstott** [comment] 2016-06-01 09:03
+1 This is also happening to me.

**Comment by JJ** [comment] 2017-02-13 12:40
Here too

**Comment by priyankauppu** [comment] 2017-02-15 21:52
+1 Happening on Mac as well!

**Comment by Zachary-Diemer21** [comment] 2017-03-30 05:11
This is actually happening to me as well. Additionally, my preview page will not show up!

**Comment by petitchevalroux** [comment] 2017-04-21 09:11
Same thing for me here with Gephi 0.9.1 on Mac OSX Sierra 10.12.3 (16D32)

Join to this post, sample project and screenshots
![capture d ecran 2017-04-21 11 02 53](https://cloud.githubusercontent.com/assets/1106867/25271074/2b450d22-2683-11e7-8742-1156f9f0e20b.png)
![capture d ecran 2017-04-21 11 02 35](https://cloud.githubusercontent.com/assets/1106867/25271075/2b4660be-2683-11e7-94db-4c7a074cb3e1.png)

[sample.gephi.zip](https://github.com/gephi/gephi/files/946584/sample.gephi.zip)

**Comment by axnsantana** [comment] 2017-04-24 13:25
Hi @petitchevalroux, I tried your sample.
Your Label column is empty, the graphic tab is showing the id values.
Preview tab uses the Label column, just copy the values from id to Label column and you will see the labels in preview.

**Comment by pcraum** [comment] 2017-05-03 15:04
@axnsantana Ok so the "Id as Label" option in "Vue d'ensemble" does not affect the graph in preview. My bad ;-)

**Comment by petitchevalroux** [comment] 2017-05-03 15:05
@axnsantana Ok so the "Id as Label" option in "Vue d'ensemble" does not affect the graph in preview. My bad ;-)

**Comment by LadyCharlotte** [comment] 2018-02-16 08:10
Hi guys, I'm joining the conversation! I've got a similar problem. My node labels are shown in preview, but when I export, my modifications don't show on the pdf/svg/png. The colours of the nodes are the ones selected by me, but the labels don't show, and neither does my option of not showing the edges. Any ideas why?

**Comment by LadyCharlotte** [comment] 2018-02-16 11:27
Just found out why... Forget my question.

**Comment by v1nsai** [comment] 2018-03-05 21:01
Check the preview tab guys, there is an option to show labels that was off by default when I looked.  Turned it on, clicked Refresh at the bottom, et voila!

**Comment by Playgephi** [comment] 2018-04-08 04:25
I had the same problem and my mistake was importing csv files for nodes and edges in different workspaces. When importing these files there is a choice in a dialogue system: import to the same workspace or use new workspace. Click "the same workspace".

**Comment by dharif23** [comment] 2018-08-30 11:16
I would suggest importing the nodes table and edges table at the same workspace and then create your graph. After finishing the modification with the graph while exporting go to preview tab and change the setting in "presets" and choose a preset and tweak the setting to your liking and save that preset. I recommend changing the default preset and save it with your preferred setting. This will give you the desired output.

**Comment by racingkoala** [comment] 2018-09-07 11:35
so if I understand, in overview you can specify custom labels, but not in preview?

**Comment by SushilShrestha** [comment] 2019-09-10 07:33
Having same issue. I want to export my graph with labels different that default column "Label" column. Is that possible without manually copying the custom column to "Label" column?

**Comment by Ji4chenLi** [comment] 2019-10-21 20:25
> Just found out why... Forget my question.

Can I know how you fixed this problem?

**Comment by kallewesterling** [comment] 2020-01-14 17:50
1. Go to Data Laboratory

2. Click "Copy data to other column"
![image](https://user-images.githubusercontent.com/7298727/72368529-4067e380-36cc-11ea-83cb-e07e51c7624e.png)

3. Select "ID"
![image](https://user-images.githubusercontent.com/7298727/72368553-4e1d6900-36cc-11ea-85d5-70833899c60e.png)

4. Make sure "Label" is selected as your "to" field. Then press "OK"
![image](https://user-images.githubusercontent.com/7298727/72368565-55dd0d80-36cc-11ea-9379-08c7959aabec.png)

Now, reload your Preview and it should all be good.

**Comment by kooelo** [comment] 2020-01-15 07:35
Thanks to "kallewesterling". Yes, copying the correct label to the variable "Label" works (as already suggested in this thread). But this is NO solution! Think about the situation that you would like to use different labels in different versions of the same graph!!!!?!

The only solution is to fix Gephi to work as expected: what you do in the graph view should be what you see in the preview.

**Comment by kallewesterling** [comment] 2020-01-21 20:36
Wouldn't you do that work in the dataset though?

**Comment by flavienbwk** [comment] 2020-02-19 21:16
I agree gephi should give the option to choose the label column to display in preview. 

But thank you for the workaround @kallewesterling, it was helpful for me

**Comment by proteusGIT** [comment] 2020-09-17 12:24
I have no node labels for the example [gephi-dot-example](https://gephi.org/users/supported-graph-formats/graphviz-dot-format/).
I am importing the file but there are only black circles instead of labels.
I turned on `Preview->Node Label->Show Labels` but that did not change anything.
Any ideas?

**Comment by FrancescoQ** [comment] 2020-12-30 09:24
Hi! so, correct me if i'm wrong but currently i cannot do something like that in the overview

![15c683beabcd50c79f6234031cd1ba77](https://user-images.githubusercontent.com/7304072/103342166-1815f800-4a89-11eb-8659-6366e85e0746.png)

and use the same labels in the preview/exported graph, as i can only chose "show labels" and if i do so, in any case it picks them from the "labels"column, is that right?

![d41d3bc510cada626cba584d0af29d37](https://user-images.githubusercontent.com/7304072/103342177-1fd59c80-4a89-11eb-865b-6e302ffeda2c.png)

**Comment by ThijmenDam** [comment] 2022-02-06 14:15
@FrancescoQ is right - this is confusing behavior. Why is it available in the overview, but not in the preview? This makes little sense.

**Comment by mbastian** [comment] 2022-03-02 20:56
Duplicate of #1877. This is now fixed and will be included in the upcoming 0.9.3 release. Thanks for the reports!

**Closed by mbastian** 2022-03-02 20:56 UTC
