### ISSUE TITLE
Can´t open files from "Documents" after 0.9.3

### ISSUE THREAD

**Issue by Haavardeh** [gephi/gephi#2486] opened 2022-04-15 10:00 UTC
I will consider this as a crucial bug. After the update I have been unable to open certain folders including the "documents" folder. This bug makes Gephi impossible to work with because I can't import spreadsheets anymore. Hope this bug gets fixed soon.

**Comment by mbastian** [comment] 2022-04-17 19:56
Duplicate of #2467

**Closed by mbastian** 2022-04-17 19:56 UTC
