### ISSUE TITLE
getting error "cannot find java 1.8 or higher". I have downloaded JAVA latest version, reinstalled gephi, error persists

### ISSUE THREAD

**Issue by smaragirl** [gephi/gephi#1953] opened 2018-04-11 18:42 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2018-04-11 18:43
Duplicate of #1787

**Closed by eduramiba** 2018-04-11 18:43 UTC
