### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by huoyushi** [gephi/gephi#1427] opened 2016-03-19 10:55 UTC
when I import csv file the weight cannot add while the row is same ，the new version is 0.9.2。But when I open the same file  the wight can add

**Comment by eduramiba** [comment] 2016-04-12 16:16
Not sure I understand, is this the same issue as https://github.com/gephi/gephi/issues/1251#issuecomment-190250518 ?

**Comment by eduramiba** [comment] 2016-10-26 19:54
Closing as duplicate of #1251

**Closed by eduramiba** 2016-10-26 19:54 UTC
