### ISSUE TITLE
"Set Label color to be of same color of the Object" in Overview does not work

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#1315] opened 2016-01-25 14:01 UTC
Using the buttons in the bottom panel, see screenshot
![clipboard01_new](https://cloud.githubusercontent.com/assets/1244100/12552857/7271bb96-c374-11e5-8833-7c7dff415eb5.png)

**Comment by mbastian** [comment] 2016-01-25 17:34
It works for me :/ Can you specify steps to reproduce? Thanks.

**Comment by seinecle** [comment] 2016-02-01 17:32
It happened again but can't reproduce it, then it works each time :-/

**Comment by HLavoix** [comment] 2016-02-08 17:01
Similar problem here with all updates made, up to 8 Feb, on Mac OsX 10.9.5

**Comment by mbastian** [comment] 2016-02-09 10:21
Ok, I know what is going on. The reason for that is because labels can either have no color (which is the default when you import a graph through "Open") or a default black color (which is the default when you manually create a node from Tool or "Import Spreadsheet"). The "Object" mode will take the custom color (if any) in account and only use the object color if there isn't a custom color. You can "erase" the custom color using the "Reset Label Color" button at the bottom of the vertical toolbar on the left of the visualization. Nevertheless this is very confusing and I hope to clarify this by:
- The Import Spreadsheet shouldn't set a default color and match the behaviour of "Open"
- Add a new "Text" color mode which would use the label custom color and fallback on the "Unique" color if missing. Make that the default mode so setting a label color in Appearance works immediately.
- Remove the custom color override in "Object" so it's always the object color

**Comment by mbastian** [comment] 2016-02-09 10:22
Oh, and I'm also adding the ability to edit label properties (color, size and visibility) from the Edit window, details at #1355.

**Comment by seinecle** [comment] 2016-02-09 10:23
Interesting! I experienced issues with filters on some graphs (Partition filters not working / not visible in the available filters), I wonder if they happen when "Import Spreadsheet" is used...

**Comment by mbastian** [comment] 2016-02-09 10:27
@seinecle Probably not, but please open another issue for that. Closing this one as fixed.

**Closed by mbastian** 2016-02-09 10:27 UTC
Labels: Visualization
