### ISSUE TITLE
Gephi.Export Table of SCV on Mac big sur freezes the application

### ISSUE THREAD

**Issue by schwagjo** [gephi/gephi#2232] opened 2021-01-10 13:58 UTC
Gephi 092: Export Table on Mac big sur freezes the application, restart is required.

**Comment by UTH-Tuan** [comment] 2021-01-14 16:11
I had the same issue with the the previous version of macos (there might be open ticket of this posted already). The workaround is changing the UI (i.e. to Nimbus or anything other than the native look and feel).

**Comment by mbastian** [comment] 2021-12-23 09:18
Hi, I can't reproduce this issue yet. Maybe it's specific to the data you're trying to export. Would you mind attaching a sample or a project file so that I can try to reproduce it. Thank you!

**Comment by mbastian** [comment] 2022-03-01 19:35
As I didn't hear back I'll close this one. Feel free to reopen when needed.

**Closed by mbastian** 2022-03-01 19:35 UTC
Labels: MacOS, UI
