### ISSUE TITLE
"No suitable driver found for jdbc:mysql://localhost:3306/sys"

### ISSUE THREAD

**Issue by ShobhitSaxena29** [gephi/gephi#1522] opened 2016-06-23 10:13 UTC
Hi I am also facing same problem, getting "No suitable driver found for jdbc:mysql://localhost:3306/sys"

I have tried following: 
1. Help -> check for updates 
2. tools -> plugin -> check for updates 
3. Running Gephi with administrator rights (Run as Administrator)

I am using Gephi 0.9.1

Steps: 
1. File -> Import database -> edge list
2. Host: localhost
3. Port: 3306
4. database: sys
5. username/pswd: root/root 
6. hit on Test Connection

and getting the error that driver not supported. 
Please help urgently...

**Comment by eduramiba** [comment] 2016-06-23 11:05
Duplicate of #1317

**Closed by eduramiba** 2016-06-23 11:05 UTC

**Comment by ShobhitSaxena29** [comment] 2016-06-23 11:52
But there is no solution for this in the #1317 
Please help with the solution...
