### ISSUE TITLE
forum.gephi.org does not allow new user registration

### ISSUE THREAD

**Issue by dennisobrien** [gephi/gephi#996] opened 2015-01-08 01:08 UTC
I tried to create an account on forum.gephi.org in order to comment on a problem but the process failed saying my IP is blacklisted.  I tried the same registration from my phone and got a similar result.

    Your IP [ip_address] has been blocked because it is blacklisted. For details please see http://www.ahbl.org/lktool?lookup=[ip_address].
    An entry on the blacklist may have several reasons:
    1. You are a well-known spammer.
    2. Last time a well-known spammer was using the dynamic IP address which you got from your ISP (Internet Service Provider), your e-mail address or the username you have choosen.
    3. Your ISP is well-known for a lot of spamming customers and is not fighting against spammers enough.

I only tested from two ip addresses (my laptop and my phone) but I suspect this is a general problem.

To verify, follow the steps to register here:  https://forum.gephi.org/ucp.php?mode=register

**Comment by jockeyyan** [comment] 2015-01-14 03:17
Yes, I have the same problem. Does anyone could help us?

**Comment by drevicko** [comment] 2015-05-31 08:44
This is duplicated in #1047

**Comment by mbastian** [comment] 2016-02-18 22:13
Closing as duplicate of #1047

**Closed by mbastian** 2016-02-18 22:13 UTC
