### ISSUE TITLE
[Ubuntu 14.04, Java 7, Gephi 0.8.2] Main window doesn't load Gephi

### ISSUE THREAD

**Issue by wmay** [gephi/gephi#958] opened 2014-10-11 21:32 UTC
I'm running Linux Mint 17 (based on Ubuntu 14.04).

`java -version` returns:

```
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```

When I start Gephi, it gets to the main window, but the actual Gephi utilities don't load, and the window is titled "Netbeans Platform 7.2.1" instead of Gephi.

Changing the Java path in my etc/gephi.conf file didn't help. Gephi 0.9 seems to run fine.

Gephi 0.8.2 Looks like this:

![screenshot from 2014-10-11 17 14 07](https://cloud.githubusercontent.com/assets/4205859/4604194/9c67feda-518b-11e4-8b83-0a20533e1671.png)

This is the error:

```
java.lang.NullPointerException
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings.getSuperIdentity(AutoupdateSettings.java:435)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings.generateIdentity(AutoupdateSettings.java:136)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler.signOn(AutoupdateCheckScheduler.java:110)
	at org.netbeans.modules.autoupdate.ui.actions.Installer.restored(Installer.java:63)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:469)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:392)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:103)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:344)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:619)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:607)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:603)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:623)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:341)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1179)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1002)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:296)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:169)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Slater-Victoroff** [comment] 2015-01-24 19:18
+1, Same issue running Yosemite though.

**Comment by Tas-sos** [comment] 2015-03-21 21:07
and I have the same problem :(

**Comment by eduramiba** [comment] 2015-08-26 16:15
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:15 UTC
