### ISSUE TITLE
gephi-0.8.2-beta.dmg crashes when opening for the first time

### ISSUE THREAD

**Issue by whitschrader** [gephi/gephi#1122] opened 2015-09-14 20:38 UTC
I've downloaded gephi-0.8.2-beta.dmg for mac, am running Yosemite, and go to open the program for the first time when I see it 'loading cached objects' and then it crashes.

Can anyone recommend a solution?

<img width="475" alt="screenshot 2015-09-14 13 37 26" src="https://cloud.githubusercontent.com/assets/1051246/9861207/c60908ba-5ae5-11e5-8829-7c29881e71bc.png">

**Comment by eduramiba** [comment] 2015-09-14 20:50
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac

**Closed by eduramiba** 2015-09-14 20:50 UTC
