### ISSUE TITLE
Gephi not open in Mac OS X El Capitan

### ISSUE THREAD

**Issue by AlbertLizard** [gephi/gephi#1141] opened 2015-10-02 15:09 UTC
I downloaded the beta of Gephi version my iMac 21.5-inch with 8 GB of RAM and 500 GB hard drive with an Intel Core i5 processor with Mac OS X El Capitan and as I open the DMG package and installs the application, everything goes smoothly. The problem arises when opening Gephi. That the application does not open and do not know why. Could you help me?

Thank you!

Alberto.

**Comment by duncdrum** [comment] 2015-10-02 16:33
After the upgrade to el capital you need to redownload and install Apples latest Java release (Java6) Gephi on mac won't work on Java7 or 8.

**Comment by sergei-kalugin** [comment] 2015-10-02 18:12
@AlbertLizard , Gephi requires Java 6 or 7. Apple provides Java 6 for OS X for supporting legacy code: https://support.apple.com/kb/DL1572?locale=en_US

Don't forget to override jdkhome in gephi.conf so it knows that you want to use Java that is different from the one that system uses.

**Comment by rll307** [comment] 2015-10-03 14:04
Great instructions

But I am a kind of newbie. How shoul I modify this jdkhome path?

thanks

**Comment by AlbertLizard** [comment] 2015-10-03 15:49
Thank you for your help! Gephi then I installed worked Java6

**Comment by eduramiba** [comment] 2015-10-05 21:31
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac

**Closed by eduramiba** 2015-10-05 21:31 UTC

**Comment by lyondhur** [comment] 2015-11-03 10:30
Hi lads, 

Is there any ETA for Gephi to support Java 8?

**Comment by eduramiba** [comment] 2015-11-03 14:11
Yes, see
https://gephi.wordpress.com/2015/11/02/announcing-gephi-0-9-release-date/

**Comment by lyondhur** [comment] 2015-11-03 14:15
Ultra exciting Eduardo. 
Cheers for the prompt follow up. 
Much appreciated. 

San Picciarelli
Senior Project Manager, Designer

mob: +64 027 747 8916
twitter/telegram/whatsapp: lyondhur  

website <http://yellowberry.com.br/> | twitter <http://twitter.com/lyondhur> | facebook <https://www.facebook.com/profile.php?id=1067186067> | linkedin <https://nz.linkedin.com/in/lyondhur> | about.me <http://about.me/lyondhur> 

DISCLAIMER - 'This email and its attachments may contain privileged and/or confidential information. Use, disclosure, copying or distribution of this message by anyone other than the intended recipient is strictly prohibited. If you have received this email in error, please notify the sender by reply email and destroy all copies of this message.'

**Comment by duncdrum** [comment] 2015-11-04 16:00
@eduramiba  ...this sounds exciting, 
guess my hierarchical graphs will be pining for the fjords then
