### ISSUE TITLE
Filter Parameter column changes are reloading saved file

### ISSUE THREAD

**Issue by kb2010** [gephi/gephi#2519] opened 2022-05-04 09:42 UTC
## Expected Behavior
the parameter column should stay the same.

## Current Behavior
after closing and reloading the file. for the filters set up the parameter changes to a different field. In Partition is shows the correct and so does the Parts. But the column is different and in the settings the values are from the different column.

## Possible Solution

Most likely the code is not looking up the correct column and defaulting to one of the other existing columns Or when the file is saved it is not saving the correct column in the save file.

## Steps to Reproduce

1. click on filters
2. add a attribute filter to the queries section
3. select in the partition section two filters i.e. two values
4. run the filter. stop. and save the file.
5. reopen the file
6. check the filter parameters and you will see column set to something different

## Context

need to reset up the filters after re-opening a save file.

## Your Environment

* Version used: Gephi 0.9.5
* Operating System: Windows 10

**Comment by mbastian** [comment] 2022-05-08 15:23
Thanks, I can confirm there is definitely something not right here.

**Comment by mbastian** [comment] 2022-06-15 19:51
The issue is fixed and will be part of the upcoming 0.9.6 release. Thanks a lot for the report.

**Closed** 2022-06-15 19:50 UTC
Labels: Confirmed, Filters
