### ISSUE TITLE
Modularity bug

### ISSUE THREAD

**Issue by nateraluis** [gephi/gephi#1412] opened 2016-03-03 18:26 UTC
I was working with a network file constructed from CSVs that had been imported using the data laboratory, when I run Modularity I got a java.lang.NullPointerException.

Here's the log file.
[messages.txt](https://github.com/gephi/gephi/files/157410/messages.txt)

**Comment by cdgoodwin** [comment] 2016-03-24 19:02
Do you have any duplicate edges in your CSV? I found one and deleted it in mine, then the modularity functioned normally again..

**Comment by eduramiba** [comment] 2016-04-01 12:39
Closing as duplicate of #1419

**Closed by eduramiba** 2016-04-01 12:39 UTC
