### ISSUE TITLE
Gephi software does not start on a Mac. 

### ISSUE THREAD

**Issue by RRKLRRKL** [gephi/gephi#2929] opened 2024-07-11 08:26 UTC
Gephi software does not start on a Mac. I regularly try to use this software, but it is incompatible with MacOS. I am not going to try anymore and the software will be removed. Maybe voor other users of this software to develop a version that will work on a Mac.

**Comment by nabsiddiqui** [comment] 2024-07-23 18:24
@RRKLRRKL Have you tried closing any of your utilities in the background, especially any related to window management (Contexts, Rectangle, Magnet, AltTab, etc.?). The issue is widely discussed in #2546. 

In addition, please be respectful of the developers/community. This is open-source software that is provided to the community. No one is working on it full-time (from what I know) and no one is paid to develop it.

**Comment by mbastian** [comment] 2024-08-25 09:37
Thanks @nabsiddiqui, yes you are correct no-one is paid.

@RRKLRRKL The software IS compatible with Mac OS. If you have some specific issues, please ellaborate.

**Closed by mbastian** 2024-08-25 09:37 UTC
