### ISSUE TITLE
Unable to Open Gpehi in Macbook Pro

### ISSUE THREAD

**Issue by JETrimble** [gephi/gephi#821] opened 2013-09-17 17:13 UTC
Good day. When I attempt to open up Gephi in my Macbook Pro it freezes with a gray screen that is not able to be edited. Here is my configuration: MacBook Pro, 2.66 GHz Intel Core i7, OSX 10.8.4(12E55), OWCMercury EXTREME Pro 6G SSD(240.06 GB).

**Comment by eduramiba** [comment] 2015-08-26 15:59
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:59 UTC
