### ISSUE TITLE
Gephi 0.9: launches on M1 Mac running macOS Ventura 13.1, but stalls and not responding, spinning beachball of death

### ISSUE THREAD

**Issue by kunau** [gephi/gephi#2714] opened 2022-12-15 17:54 UTC
**Gephi 0.9**: launches on M1 Mac running macOS Ventura 13.1 but stalls and not responding, spinning beachball of death. Need to Force Quit to exit.

Any ideas?

**Comment by mbastian** [comment] 2022-12-30 12:36
Duplicate of #2546

**Closed by mbastian** 2022-12-30 12:36 UTC
