### ISSUE TITLE
Node size by attribute not working: please help

### ISSUE THREAD

**Issue by Somebody-stumbled** [gephi/gephi#1495] opened 2016-05-25 20:48 UTC
I suppose this is not Q&A.

**Comment by eduramiba** [comment] 2016-05-25 20:58
We are sorry this is indeed an important issue that we need to fix, and has high priority. Please check https://github.com/gephi/gephi/issues/1459

**Comment by Somebody-stumbled** [comment] 2016-05-25 21:40
A reply! Thanks, I actually stumbled across this answer 10 minutes after posting this comment. But some indication in the GUI about this workaround would have been a godsend. This is, to a user like myself, essentially a random clicking of buttons (and I did some random clicking, but didn't hit on the winning formula). Just a message in the dropdown pointing to #1459 would have been great!

**Comment by eduramiba** [comment] 2016-05-26 15:57
Closing as duplicate of #1459

**Closed by eduramiba** 2016-05-26 15:57 UTC
Labels: Appearance
