### ISSUE TITLE
Gephi 0.9 crashes on Mac (Yosemite)

### ISSUE THREAD

**Issue by alblaine** [gephi/gephi#1327] opened 2016-02-01 02:34 UTC
Gephi crashes every time I try to tab between views (Overview, Data Laboratory and Preview). Usually it happens when I am trying to go back to Overview from another tab.

**Comment by mbastian** [comment] 2016-02-01 10:46
Duplicate of #1241

**Closed by mbastian** 2016-02-01 10:46 UTC
