### ISSUE TITLE
Labels are not showing up in the Preview. Icon for Ranking result table is missing 

### ISSUE THREAD

**Issue by Saravanakumar19** [gephi/gephi#2227] opened 2020-12-18 09:09 UTC
[

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by Saravanakumar19** [comment] 2020-12-18 09:26
Please suggest necessary actions as early as possible. It is an urgent situation. Kindly guide me
[Issue in Gephi.docx](https://github.com/gephi/gephi/files/5714801/Issue.in.Gephi.docx)

**Comment by wetneb** [comment] 2021-12-02 08:46
Hello @Saravanakumar19,
Thank you for your report! Would you be able to provide a sample file which lets us reproduce the issue on our side?

**Comment by mbastian** [comment] 2021-12-23 09:26
Closing as we can't reproduce the issue. Please open again when you can provide a sample file, thank you!

**Closed** 2021-12-23 09:26 UTC
