### ISSUE TITLE
not visualising on MacOS High Sierra

### ISSUE THREAD

**Issue by ghirigori** [gephi/gephi#2123] opened 2019-07-18 08:20 UTC
## Expected Behavior
When I upload my gefx files from CorText, they should be visualised in Gephi.

## Current Behavior
They are not visualised. I have had this problem with Gephi on my Mac ever since I first tried to use it in 2015.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by wetneb** [comment] 2021-12-02 09:43
Thank you for this report! It is unlikely we can reproduce this bug without a sample file. I am tentatively closing this because of that, but if you can provide a sample graph file where the bug can be reproduced, we can reopen it.

**Closed by wetneb** 2021-12-02 09:43 UTC
