### ISSUE TITLE
Cannot find Java 1.8 but I have java 1.8 and the gephi do not open in my computer

### ISSUE THREAD

**Issue by marcoscrie** [gephi/gephi#1888] opened 2018-01-05 13:03 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2018-01-05 13:26
Duplicate of #1787

**Closed by eduramiba** 2018-01-05 13:26 UTC
