### ISSUE TITLE
Loading graphviz dot files exception if attributes empty

### ISSUE THREAD

**Issue by skelter** [gephi/gephi#2028] opened 2018-09-14 13:19 UTC
I searched for empty attributes.

## Expected Behavior
Gephi should open the graph in the graphviz dot file.

## Current Behavior
Gephi gives an exception parsing the graphviz dot file.  Upon digging you find the cryptic message
"ID can't be empty".    Upon debugging, you find that if a graph, subgraph or node have an attribute that is empty  [... lhead="", ..]  , the parser will have this problem.  That is a bug as "" is a legitimate value (see https://www.graphviz.org/doc/info/attrs.html).

## Possible Solution

Fix the internal graphviz parser.  Provide an alternative graphviz parser plugin.

## Steps to Reproduce

1.  Export a graph in graphviz dot format from SciTools Understand or create a graphviz dot file with many empty attributes specified such as  lhead="".
2.  Import into gephi.
3.  Note exception available in subtle red icon in bottom right.
4.

## Context

I spent several hours downloading source and debugging the problem.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: java version "1.8.0_172"
* Operating System: Windows 10

**Comment by eduramiba** [comment] 2018-09-14 13:50
Thanks for the report!

**Comment by wetneb** [comment] 2021-12-01 10:00
It is not reproducible for me. I can successfully import this file:
```
graph {
  a -- b [color=""]
  b -- c [color=blue,lhead=""]
}
```
It would be helpful to have a sample file for which the exception manifests itself.

**Comment by wetneb** [comment] 2021-12-01 10:44
I am not sure why #2362 did not close this, probably because I am not in the org?

**Closed** 2021-12-01 12:32 UTC
Labels: Medium, Import
