### ISSUE TITLE
Loading file list looks empty

### ISSUE THREAD

**Issue by pducrot** [gephi/gephi#2490] opened 2022-04-16 10:04 UTC
## Expected Behavior
Visualize the list of files upon loading

## Current Behavior
List of file looks empty although it contains the cdv file I'd like to read (~/Downloads/edges.csv)
## Steps to Reproduce

1. Open..
2. Browse to Users > home directory > Downloads
3.
4.

## Context
Wand to start a project by reading the csv containing edges

Can't use Gephi

## Your Environment
MacBook Pro (16 pouces, 2019) 2,3 GHz Intel Core i9 8 cores

* Version used: Gephi 0.9.3
* Operating System: Mac OS X 12.0.1 (21A559) Monterey

**Comment by mbastian** [comment] 2022-04-17 19:56
Duplicate of #2467

**Closed by mbastian** 2022-04-17 19:56 UTC
Labels: To review
