### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by boaibr** [gephi/gephi#1822] opened 2017-10-18 05:51 UTC
Hi I have been using Gephi to visualize some of my graphs at works and I would much appreciate it if an Undo button is provided. 

Sometimes I deleted a group of nodes but then took a while to regret it and wanting them back. But there is no way I can get them back unless I made a copy of the files beforehand. The confirmation for node deletion is there but still an Undo button would be very helpful in any case (accidental deletion, accidentally moving node to other place or other workspace, etc). 

**Just a suggestion for the future because currently I am still using Gephi version 0.8.2 since I needed the clustering plugins which are absent in Gephi latest version.

**Comment by eduramiba** [comment] 2017-10-18 06:32
Closing as duplicate of #1175

**Closed by eduramiba** 2017-10-18 06:32 UTC
