### ISSUE TITLE
Graph window never stops initializing, never renders

### ISSUE THREAD

**Issue by Bortseb** [gephi/gephi#1374] opened 2016-02-12 07:12 UTC
I was recently using version 0.8.2, but I started getting errors after installing some new plugins to try and do the advanced tutorial here: https://gephi.org/tutorials/gephi-tutorial-layouts.pdf

To try and fix the problems, I uninstalled, and re-installed version 0.9.0... but now my graph window never renders. It just keep saying "initializing....". I can see the graph in the preview section however.

I am using Windows 10 (64-bit.)

I am also getting this exception on startup. (I tried sending this report through the Gephi application itself, but there a was a problem sending that report it said)

java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:174)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:66)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:304)
	at org.gephi.visualization.VizController.initInstances(VizController.java:127)
	at org.gephi.visualization.VizController.getInstance(VizController.java:90)
	at org.gephi.visualization.component.VizBarController.createDefaultGroups(VizBarController.java:99)
	at org.gephi.visualization.component.VizBarController.<init>(VizBarController.java:88)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:118)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mbastian** [comment] 2016-02-12 07:15
That might be a duplicate of #1356? If not, please try to apply all updates (Help > Check for updates) as we've deployed a few fixes since the 0.9.0 release.

**Comment by Bortseb** [comment] 2016-02-12 07:23
Yep! that fixed it. My problem was Avira antivirus too. Thank you!

**Comment by mbastian** [comment] 2016-02-12 07:24
Nice!

**Closed by mbastian** 2016-02-12 07:24 UTC

**Comment by yairogen** [comment] 2017-08-31 14:14
@mbastian I have the same issue and I am fully updated

**Comment by Andershalt** [comment] 2017-09-13 09:39
Same here... fully updated with Win7Pro 64bit

**Comment by smehta12** [comment] 2017-09-17 18:17
I  have also ran into the same issue. Gephi is updated to latest. I am seeing following error in exception window. My platform is Ubuntu 14.04.

com.jogamp.opengl.GLException: Profile GL2 is not available on X11GraphicsDevice[type .x11, connection :1.0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x6e7f0b55, isOwner false, <2adf1208, 76675dcf>[count 0, qsz 0, owner <NULL>]]], but: [GLProfile[GLES1/GLES1.sw], GLProfile[GLES2/GLES3.sw], GLProfile[GL2ES1/GLES1.sw], GLProfile[GL4ES3/GLES3.sw], GLProfile[GL2ES2/GLES3.sw], GLProfile[GLES3/GLES3.sw], GLProfile[GLES3/GLES3.sw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:174)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:66)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:302)
	at org.gephi.visualization.VizController.initInstances(VizController.java:125)
	at org.gephi.visualization.VizController.getInstance(VizController.java:88)
	at org.gephi.visualization.component.VizBarController.createDefaultGroups(VizBarController.java:99)
	at org.gephi.visualization.component.VizBarController.<init>(VizBarController.java:88)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:118)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mittenchops** [comment] 2019-02-19 22:56
I have this issue as well, brand new, up-to-date installation.

```
[SEVERE] null 
java.lang.NullPointerException
	at org.gephi.visualization.component.VizBarController$1.propertyChange(VizBarController.java:105)
	at org.gephi.visualization.VizModel$1.run(VizModel.java:116)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[INFO] External Changes Refresh on focus gain disabled 
```

**Comment by thelittlebug** [comment] 2019-10-24 02:34
same problem, ubuntu 19.04, oracle java 13

**Comment by hpan67** [comment] 2019-10-30 17:37
same problem, window, 0.9.02, java 1.8.0_231

**Comment by jcaballero** [comment] 2020-06-30 18:58
I have the same error. I am usin ubuntu 18.03 and gephi 0.9.2.  I am using this command to start: .
/gephi-0.9.2/bin/gephi --jdkhome /usr/lib/jvm/java-8-openjdk-amd64/

**Comment by kblinichkin** [comment] 2022-06-30 06:25
Hi!

I've got exactly the same issue on macOS Monterey, M1 processor.
0.9.6, OpenJDK 11.0.15.
Please, reopen this ticket.
