### ISSUE TITLE
Gephi has stopped working

### ISSUE THREAD

**Issue by nickjorg** [gephi/gephi#956] opened 2014-10-09 17:20 UTC
I've used Gephi extensively the past three years or so and haven't had any issues on either Windows or OSX platforms. I'm currently running OSX Mavericks. Tried starting Gephi this morning and I get the startup icon but then the program closes and disappears. I tried deleting and reinstalling–nothing. I deleted the Gephi folder from application support (which I heard was a possible fix)–nothing. I installed a Java update from the Apple site–no result. Any other ideas on how to address this? Thanks for any help.

**Comment by eduramiba** [comment] 2015-08-26 16:15
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:15 UTC
