### ISSUE TITLE
Add edge issue: node id not displayed in the GUI

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#782] opened 2013-05-30 16:36 UTC
![capture dcran 13](https://f.cloud.github.com/assets/177962/586163/c87e1a8c-c946-11e2-9e5b-543f5c40c9ea.png)

Way to reproduce:
- Import an edge list from the DataLab Spreadsheet import, where node ids are strings
- Add edge and...you don't know why you see numbers to select the nodes. In result you don't know which nodes to select.

**Comment by mbastian** [comment] 2015-12-10 10:57
@eduramiba I believe this is fixed, right?

**Comment by eduramiba** [comment] 2015-12-10 11:03
I will try this, but I have not seen this happen in my latests tests. The combobox shows "Id - Label" of the source/target node.
In the attached image, node ids seem to be text instead of numbers though, yet the combobox shows numbers.

**Comment by mbastian** [comment] 2015-12-10 11:08
Yes, I' can't reproduce it, closing

**Closed by mbastian** 2015-12-10 11:08 UTC
Labels: Data Laboratory, Medium
