### ISSUE TITLE
can not install on mac

### ISSUE THREAD

**Issue by RH-xu** [gephi/gephi#995] opened 2015-01-06 13:16 UTC
Enviroment:
Mac OS X, version 10.9.5, 4GB memory
Java version, 1.6

Problem:
After installing, click the "Gephi" icon, the start page opens but does not response and then exits without any message issued.

**Comment by jackiekazil** [comment] 2015-03-04 03:41
I had the same problem. I documented the solution here: https://medium.com/notes-from-computational-social-science/gephi-is-broken-on-mac-os-97fbaef4305e --- Let me know if that worked for you.

**Comment by eduramiba** [comment] 2015-08-26 16:09
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:09 UTC
