### ISSUE TITLE
Can not find Java 1.8 or higher

### ISSUE THREAD

**Issue by Hadi-RJ** [gephi/gephi#1858] opened 2017-11-28 07:30 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2017-11-28 07:37
Duplicate of #1787

**Closed by eduramiba** 2017-11-28 07:37 UTC
