### ISSUE TITLE
Avarage weighted degree not added to Appearence

### ISSUE THREAD

**Issue by bornakke** [gephi/gephi#1398] opened 2016-02-26 10:04 UTC
Mac 10.11.3, Gephi 9.1

Bug: When calculating Avg. weighted degree in statistics it only becomes available as a color, not as a size mechanismen.

**Comment by sigmundcj** [comment] 2016-03-16 19:21
bornakke, 

Can you please give an example of a size mechanism? I do not understand what you are looking for it to do.

**Comment by bornakke** [comment] 2016-03-16 19:28
Hi Sigmundcj,

Basicly I open a gexf file, then I calculate avarage weighted degree. I then go to the left menu 'size' -> attribute but weighted degree have not appeared. However I have just rerun and the same bug doesn't seem to appear when using the built in Les Misserables dataset. 

<img width="561" alt="gephi_0_9_1_-_gephi_graph_gephi_and_avarage_weighted_degree_not_added_to_appearence_ _issue__1398_ _gephi_gephi" src="https://cloud.githubusercontent.com/assets/745051/13825944/54620fde-ebb5-11e5-81df-37216e8d29ff.png">


<img width="325" alt="gephi_0_9_1_-_gephi_graph_gephi" src="https://cloud.githubusercontent.com/assets/745051/13825913/3168bb68-ebb5-11e5-91dd-8e2e87ae6c7e.png">

**Comment by mbastian** [comment] 2016-10-23 14:45
Duplicate of #1459

**Closed by mbastian** 2016-10-23 14:45 UTC
