### ISSUE TITLE
appearance window not opening correctly

### ISSUE THREAD

**Issue by GregOldham** [gephi/gephi#1886] opened 2018-01-04 17:18 UTC
## Expected Behavior
the  appearance window should be visible with the formatting, and size tools available when the program opens.
## Current Behavior
the layout section is the only window on the lest of the graph area when in overview mode.  Selecting appearance from the window menu will only open the appearance window if a data file is not open.  If the window menu is used to open the appearance window sometimes the selections to the right of the tab do no show so that no setting can be set.  Sometimes the program opens correctly, but not if opening the program by double clicking a data file.
[visitation CJC Links.zip](https://github.com/gephi/gephi/files/1604075/visitation.CJC.Links.zip)

## Steps to Reproduce

1.intermittent.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java 8 update 151
* Operating System: windows 10, mac os x 10.13.2

**Comment by mbastian** [comment] 2022-11-26 19:32
Duplicate of https://github.com/gephi/gephi/issues/2520, closing.

**Closed by mbastian** 2022-11-26 19:32 UTC
