### ISSUE TITLE
Partition color key does not match displayed colors 

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#458] opened 2011-11-06 02:21 UTC
Once one has generated a coloring of the graph based on a partition, one can't later recover the key, as it always generates a new color mapping. For example, we colored a large graph using Modularity Class but forgot to take a screen dump of the color key.  Later, reselecting Modularity Class, a new key is generated not matching what is displayed. 
 
Note that this is different from recently reported bug "Colors in partition filter inconsistent with real partition colors" by sheymann, as it involves  the partition color key upper left, not the filters lower right. 

OS X 10.6.8 (on MacPro, MacBookPro, and MacBook). 
Gephi 0.8 Beta

**Comment by mbastian** [comment] 2015-12-04 12:59
Closing as duplicate of #453

**Closed by mbastian** 2015-12-04 12:59 UTC
Labels: Partition
