### ISSUE TITLE
Unable to import a large file (?)

### ISSUE THREAD

**Issue by Manaswwm** [gephi/gephi#1841] opened 2017-11-14 23:43 UTC
I have imported a large network in python (1000+ nodes and about 10000+ edges), I have processed it with networkx package and have exported the data in a '.graphml' file (file size ~4 MB). This file also contains information on color of nodes that are present in my network(as it is absolutely essential for me to be able to distinguish between some nodes).

When I try to open this file using Gephi, the screen does not show anything after I select the file i.e File -> Open -> My_Graphml_file.graphml , following which I do not get a thing in all the three tabs.

Surprisingly, even if I try to import some other file which does not have any color information and about the same size as the one I described above, it still does not show a thing in all the three tabs. But, if I try to import file with small size, I get something on my screen to work with.

So is it the size problem and if it is then how do I solve it?

**Comment by eduramiba** [comment] 2017-11-15 08:42
Can you share your file (or a minimal example file) for reproducing the problem?

**Comment by Manaswwm** [comment] 2017-11-15 09:59
I think the editor does not support uploading file formats .graphml and .gexf (?)

I am sharing the Dropbox links for those files : 
https://www.dropbox.com/s/jryrxy9fz4pjl1u/networkx_graphml.graphml?dl=0 -- this would be the file containing no node color information, but still would not open

https://www.dropbox.com/s/lhztjls2o5tusnd/networkx_gexf.gexf?dl=0  -- this would be the file containing the node color information and would not open

Thanks in advance for help!

**Comment by eduramiba** [comment] 2017-11-15 13:41
Thanks, I will check them when possible. Uploading the files as zip here
[files.zip](https://github.com/gephi/gephi/files/1474868/files.zip)

**Comment by Manaswwm** [comment] 2017-11-15 13:47
If it helps: I get the following exception thrown when I try to upload the large network -

_java.lang.IllegalArgumentException: The id can't be empty
	at org.gephi.io.importer.impl.ImportContainerImpl.checkId(ImportContainerImpl.java:1035)
	at org.gephi.io.importer.impl.ImportContainerImpl.nodeExists(ImportContainerImpl.java:209)
	at org.gephi.io.importer.plugin.file.ImporterGEXF.readNode(ImporterGEXF.java:364)
	at org.gephi.io.importer.plugin.file.ImporterGEXF.execute(ImporterGEXF.java:153)
	at org.gephi.io.importer.impl.ImportControllerImpl.importFile(ImportControllerImpl.java:199)
	at org.gephi.io.importer.impl.ImportControllerImpl.importFile(ImportControllerImpl.java:169)
	at org.gephi.desktop.importer.DesktopImportControllerUI$4.run(DesktopImportControllerUI.java:341)
Caused: java.lang.RuntimeException
	at org.gephi.desktop.importer.DesktopImportControllerUI$4.run(DesktopImportControllerUI.java:349)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)_

**Comment by Manaswwm** [comment] 2017-11-15 16:11
Short update:
I dropped the idea of coloring nodes, I just wanted to visualize the large network (which has 1226 nodes and 50976 edges). I constructed a .graphml file using python(networkx) for the same and now I try opening it with Gephi (and it does not open). As a control to check whether my network has some error, I try opening the same .graphml file in Cytoscape and it works.
The only reason why I want to open network in Gephi instead of Cytoscape is that the layout options in former are better than the later.

**Comment by Manaswwm** [comment] 2017-11-18 17:25
I figured out the solution to this problem:

I opened the _.graphml_ file that I obtained from _python_ in _Cytoscape_, then without modifying I exported ._graphml_ from _Cytoscape_ to _Gephi_ and now I am able to visualize the network.

**Comment by BonnieSchrack** [comment] 2017-12-14 18:30
I don't think the large file size is so much the problem, as the file type. I import CSV files of thousands of nodes and over 100000 edges, not that Gephi is happy about excessive numbers of edges, but CSV seems to be a Gephi-friendly file type.

**Comment by graemediack** [comment] 2018-12-13 11:50
You could try to use networkx.write_gml instead of .write_graphml, this worked for me after I was having a similiar problem!

**Comment by Manaswwm** [comment] 2018-12-13 13:56
So let me once again explain my problem and a strange solution that seemed
to work:

Problem: I construct a network in python using networkx. Store the network
and export in graphml format (say py.graphml). This file does not open in
Gephi.

Solution: I open the file (py.graphml) in cytoscape, export the file again
from cytoscape in a graphml format(new file, say cy.graphml) and then open
it in Gephi.
Voila! It works!

**Comment by mbastian** [comment] 2022-01-22 20:31
This issue has been fixed and will be included in the upcoming 0.9.3 release. Thank you for the report!

The root cause was because of a node id being a whitespace " " in your file example. As long as the id is not empty it should work but we had a bug that was trimming the id and therefore it would be empty.

**Closed by mbastian** 2022-01-22 20:31 UTC
Labels: GraphML, Import
