### ISSUE TITLE
Nodes size: a very strange problem

### ISSUE THREAD

**Issue by DenisOlivera** [gephi/gephi#1443] opened 2016-03-31 01:39 UTC
Hi,

I’m trying to create a very simple graph on Gephi, but there’s a very strange thing happening.

I’m importing a csv file for the nodes, with only 3 columns: id (string), label (string) and relevance (integer, with numbers varying just from 1 to 3).

My goal is to have the nodes size matching the values from the 'relevance' column of the csv file, just picking this attribute in appearance > nodes > size > attribute.

When I import a csv file like this

**id, label, relevance
1, red, 1
2, green, 2
3, blue, 1
4, yellow, 3
5, grey, 3
6, pink, 2
7, black, 1
8, white, 3
9, orange, 2**

everything is fine.

But, when I add just one more line in the csv file, like

**10, brown, 3**

the attribute ‘relevance’ doesn’t appear anymore in appearance > nodes > size > attribute.

If I put this 10th line manually on the Data Laboratory, it’s OK. But I really need that this values can come directly from the csv file.

Can anyone tell me why this is happening?

I'm using the Gephi version 0.9.1.

Thank you!

**Comment by AtomBoy** [comment] 2016-04-11 21:28
I'm having similar problems where a float field in a gexf file I've created doesn't appear in nodes > size > attribute. It does appear in nodes > color > attribute.

**Comment by jfurfey** [comment] 2016-04-13 16:55
I'm having the same issue

**Comment by cladelpino** [comment] 2016-09-08 13:32
I can confirm this bug for my setup, tried all different import formats for the attribute (which is an integer in my case), 

Gephi won't recognize this attribute for node sizing / text label sizing. 
It is correctly recognized in Node Color, and in the filters. 

I tried importing to different types, and forcing "create new nodes..." but behaviour remains. My test graph has 235 nodes. 

addit info:
Java: 1.8.0_73; Java HotSpot(TM) 64-Bit Server VM 25.73-b02
System: Windows 10 versión 10.0 que se ejecuta en amd64; Cp1252; es_AR (gephi)

**Comment by cladelpino** [comment] 2016-09-08 13:34
PS: title on this issue should be changed to better reflect the issue after two more tests in my view
1.does this only happen for csv ? 
2.when nodes >10 ?

**Comment by eduramiba** [comment] 2016-09-08 13:34
This is bug https://github.com/gephi/gephi/issues/1459

Explanation: Gephi now tries to auto-detect wether the column should be ranking or pratition

**Comment by cladelpino** [comment] 2016-09-08 14:12
semi OT: that should be very hard to "auto-detect" consistently. 

Why not ask the user with a tooltip explaining diff between rank/partition (which anyone serious with networks should know) during import ?

**Comment by eduramiba** [comment] 2016-09-08 14:13
Yeah that will be changed/fixed in 0.9.2, it should be possible to use any column with both modes in appeareance.

**Comment by mbastian** [comment] 2016-10-23 10:59
Duplicate of #1459 - we'll fix this auto-detect issue and make the choices more explicit in 0.9.2

**Closed by mbastian** 2016-10-23 10:59 UTC
