### ISSUE TITLE
Can not load java in gephi 0.9.2 in win 10

### ISSUE THREAD

**Issue by kimyoungjin06** [gephi/gephi#1792] opened 2017-09-28 05:20 UTC
## Steps to Reproduce

1. Install with official release version 0.9.2 from https://gephi.org/users/download/
2. Install java 8 update 144 in Win 10
3. cannot load java information
4.

## Context

I start the gephi but gephi just output error message "java 1.8 or higher is not installed"? or text like that.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 144
* Operating System: Win 10

**Comment by eduramiba** [comment] 2017-09-28 06:40
Duplicate of https://github.com/gephi/gephi/issues/1787

**Closed** 2017-09-28 06:40 UTC
