### ISSUE TITLE
Cannot launch gephi on windows 8 after reinstalling java

### ISSUE THREAD

**Issue by rarezhang** [gephi/gephi#911] opened 2014-05-01 20:39 UTC
Hi, 
I cannot launch gephi on windows 8.1 after I reinstalled java. (I have been using gephi for a year, it worked great before I reinstalled java )

Here is the information from gephi:
C:\Program Files (x86)\Gephi-0.8.2\bin>
The launcher has determined that the parent process has a console and will reuse
it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.

Here is my Java version:
C:\Program Files (x86)\Gephi-0.8.2\bin>java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) Client VM (build 25.5-b02, mixed mode, sharing)

I have modified "gephi.conf", doesn't work:
# default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
jdkhome="C:/Program Files (x86)/Java/jdk1.8.0_05"
rarezhang
 
Posts: 2
Joined: 01 May 2014 18:59
Location: United States

**Comment by eduramiba** [comment] 2015-08-26 17:00
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:00 UTC
