### ISSUE TITLE
Gephi can not open a file: nothing happens.

### ISSUE THREAD

**Issue by RRKLRRKL** [gephi/gephi#1990] opened 2018-07-03 13:25 UTC
## Expected Behavior
Open file.

## Current Behavior
Empty views.

## Possible Solution
Rewrite Gephi code and add the feature to open a Gephi file.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by aldou** [comment] 2018-08-03 15:01
Duplicate of issue #1997 
Check the workaround explained over there.

**Comment by wetneb** [comment] 2021-12-02 10:33
Closing as duplicate of #1997 then.

**Closed by wetneb** 2021-12-02 10:33 UTC
