### ISSUE TITLE
Unable to change the size of a node depending on different attributes #1330 Fix not working

### ISSUE THREAD

**Issue by rbsam** [gephi/gephi#1479] opened 2016-05-03 15:09 UTC
I have seen posts about the issue saying the problem has been solved with updates. However the issue remains on Mac OS El Capitain and on Windows 8 even after I run check for updates.
The only option to change the size of nodes from Appearence/Attribute is with the original Degree size. Even after I change the degree of the nodes the new size is not reproduced on the graph.

**Comment by rbsam** [comment] 2016-05-03 16:02
I just found out that it works with type "float" to adjust the attribute but not with type "integer".
You have to duplicate the column and set to type float and it will appear on the Appearence/Attribute list.

**Comment by rbsam** [comment] 2016-05-03 16:19
Just found something else. On Appearence/Attributes by color you can set the attribute to Partitioning to Ranking on the botton left of the window. If the attribute is set to Partitioning it will not appear on Size attribute. If it is set to Ranking it will appear on Size attribute.

**Comment by eduramiba** [comment] 2016-06-01 09:46
This seems a duplicate of #1459

**Comment by mbastian** [comment] 2016-10-23 10:52
Duplicate of #1459 - closing

**Closed by mbastian** 2016-10-23 10:52 UTC
Labels: Appearance
