### ISSUE TITLE
layout selection "expansion" and "contraction" don't stick

### ISSUE THREAD

**Issue by duncdrum** [gephi/gephi#1750] opened 2017-07-05 07:42 UTC
## Expected Behavior
expansion layout should expand the graph, contraction should do the opposite. 

## Current Behavior
whichever layout is selected first, its opposite will perform the same operation. 

## workaround
restart gephi

## Steps to Reproduce
1. Open les miserable
2. run expansion layout on graph (so far so good)
3. now run contraction (the graph will keep expanding)

## Context
Came up during a small workshop, identical bug accross different OS. If you first run expansion you cannot contract, if you first select contract you can no longer expand. 

## Your Environment
* Version used: Gephi 0.9.1
* Operating System: macOS 10.12.5, and multiple win7, or win10 configs
* Java 1.8.131

**Comment by eduramiba** [comment] 2017-07-05 08:05
Duplicate of #860 Fixed for 0.9.2

**Closed by eduramiba** 2017-07-05 08:05 UTC
