### ISSUE TITLE
Impossible to install it on my MacBook Air

### ISSUE THREAD

**Issue by plemonnier** [gephi/gephi#946] opened 2014-09-03 20:17 UTC
I downloaded the ".dmg" fil to install Gephi on my Mac.
The download went well. But when I try top open the final file, it doesn't work.

**Comment by jackiekazil** [comment] 2015-03-04 03:44
I had the same problem. I documented the solution here: https://medium.com/notes-from-computational-social-science/gephi-is-broken-on-mac-os-97fbaef4305e --- Let me know if that worked for you.

**Comment by eduramiba** [comment] 2015-08-26 16:56
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:56 UTC
