### ISSUE TITLE
all of sudden gephi stop working

### ISSUE THREAD

**Issue by Dvijesh88** [gephi/gephi#932] opened 2014-06-21 07:02 UTC
I am using window 7 64 bits OS. i installed the gephi and it is works really good. but all of sudden it stop working and now only initializing screen start and then all process is stop working. here i am also write the log file please provide me solution.

-------------------------------------------------------------------------------
>Log Session: Saturday, June 21, 2014 11:37:01 AM IST
>System Info: 
  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Windows 7 version 6.1 running on x86
  Java; VM; Vendor        = 1.8.0; Java HotSpot(TM) Server VM 25.0-b70; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0-b132
  Java Home               = C:\Program Files (x86)\Java\jdk1.8.0\jre
  System Locale; Encoding = en_IN (gephi); Cp1252
  Home Directory          = C:\Users\DB
  Current Directory       = C:\Program Files (x86)\Gephi-0.8.2
  User Directory          = C:\Users\DB\AppData\Roaming\.gephi\0.8.2\dev
  Cache Directory         = C:\Users\DB\AppData\Roaming\.gephi\0.8.2\dev\var\cache
  Installation            = C:\Program Files (x86)\Gephi-0.8.2\gephi
                            C:\Program Files (x86)\Gephi-0.8.2\platform
                            C:\Program Files (x86)\Gephi-0.8.2\platform
  Boot & Ext. Classpath   = C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\rt.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\classes;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0\jre\lib\ext\zipfs.jar
  Application Classpath   = C:\Program Files (x86)\Gephi-0.8.2\platform\lib\boot.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\org-openide-modules.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\org-openide-util-lookup.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\org-openide-util.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_ar_SA.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_bg.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_ca.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_cs.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_de.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_es.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_fr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_gl_ES.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_in_ID.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_it.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_ja.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_ko.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_nl_NL.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_pl.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_pt_BR.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_pt_PT.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_ro.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_ru.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_si.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_sq.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_sv.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_tr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_zh_CN.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\boot_zh_TW.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_ar_SA.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_bg.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_ca.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_cs.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_de.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_es.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_fr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_gl_ES.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_in_ID.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_it.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_ja.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_ko.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_nl_NL.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_pl.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_pt_BR.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_pt_PT.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_ro.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_ru.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_si.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_sq.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_sv.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_tr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_zh_CN.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-modules_zh_TW.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_bg.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_ca.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_cs.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_de.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_es.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_fr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_gl_ES.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_in_ID.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_it.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_ja.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_ko.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_nl_NL.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_pl.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_pt_BR.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_ro.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_ru.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_si.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_sv.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_tr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util-lookup_zh_CN.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_ar_SA.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_bg.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_ca.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_cs.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_de.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_es.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_fr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_gl_ES.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_in_ID.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_it.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_ja.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_ko.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_nl_NL.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_pl.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_pt_BR.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_pt_PT.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_ro.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_ru.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_si.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_sq.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_sv.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_tr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_zh_CN.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\lib\locale\org-openide-util_zh_TW.jar;C:\Program Files (x86)\Java\jdk1.8.0\lib\dt.jar;C:\Program Files (x86)\Java\jdk1.8.0\lib\tools.jar
  Startup Classpath       = C:\Program Files (x86)\Gephi-0.8.2\platform\core\core.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\org-openide-filesystems.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_ar_SA.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_bg.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_ca.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_cs.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_de.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_es.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_fr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_gl_ES.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_in_ID.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_it.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_ja.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_ko.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_nl_NL.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_pl.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_pt_BR.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_pt_PT.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_ro.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_ru.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_si.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_sq.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_sv.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_tr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_zh_CN.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\core_zh_TW.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_ar_SA.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_bg.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_ca.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_cs.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_de.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_es.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_fr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_gl_ES.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_in_ID.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_it.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_ja.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_ko.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_nl_NL.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_pl.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_pt_BR.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_pt_PT.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_ro.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_ru.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_si.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_sq.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_sv.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_tr.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_zh_CN.jar;C:\Program Files (x86)\Gephi-0.8.2\platform\core\locale\org-openide-filesystems_zh_TW.jar;C:\Program Files (x86)\Gephi-0.8.2\gephi\core\locale\core_gephi.jar
-------------------------------------------------------------------------------
java.lang.IllegalStateException: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:423)
	at org.openide.util.WeakListenerImpl.create(WeakListenerImpl.java:164)
	at org.openide.util.WeakListeners.create(WeakListeners.java:271)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:125)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:142)
	at org.openide.filesystems.MultiFileSystem.getMultiRoot(MultiFileSystem.java:267)
	at org.openide.filesystems.MultiFileSystem.findResource(MultiFileSystem.java:355)
	at org.openide.filesystems.FileUtil.getConfigFile(FileUtil.java:2276)
	at org.openide.filesystems.FileUtil.getConfigRoot(FileUtil.java:2306)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:158)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:398)
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:413)
	... 12 more

**Comment by eduramiba** [comment] 2015-08-26 16:16
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:16 UTC
