### ISSUE TITLE
cannot find java 1.8 or higher

### ISSUE THREAD

**Issue by Julietsketch** [gephi/gephi#2180] opened 2020-04-02 20:26 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2020-04-03 10:20
Hi,
Gephi 0.9.2 is only compatible with Java 8, and not Java 9 or later. Please make sure that it's in the `JAVA_HOME` variable, or set `jdkhome` in `gephi.conf`file if you need other java versions in your system.

See https://github.com/gephi/gephi/wiki/Troubleshooting to configure `gephi.conf`.

**Comment by Julietsketch** [comment] 2020-04-03 12:40
thank you Eduardo
I`ll take it from there and see  if I can fix it. Gephi was running
perfectly well, I hope I can fix it

regards J

**Comment by joshpowlison** [comment] 2020-04-22 14:08
Running into the same error. I didn't have Java installed on my system, but based on [this comment](https://github.com/gephi/gephi/issues/748#issuecomment-164172828) it seems like this shouldn't be an issue for me or Julietsketch.

It sounds like starting with 0.9.0 Java was (or was intended) to be included with the installation.

Happened to me with Gephi 0.9.2 as well. I'll try installing an older version of Gephi and see if that works.

**Comment by joshpowlison** [comment] 2020-04-22 14:11
Update: Gephi 0.9.1 succeeded. It looks like this is a problem with 0.9.2 specifically.

@Julietsketch , revert to [Gephi 0.9.1](https://github.com/gephi/gephi/releases/tag/v0.9.1) and you should be good for now.

**Comment by Julietsketch** [comment] 2020-04-24 15:37
Hi, I solved it by going back to 0.9.1  and its working fine now.

thank you J

**Comment by wetneb** [comment] 2021-12-02 09:13
Duplicate of #2160.

**Closed by wetneb** 2021-12-02 09:13 UTC
Labels: Java compatibility
