### ISSUE TITLE
locks up repeatedly on os x 10.9.2 

### ISSUE THREAD

**Issue by williamsEye** [gephi/gephi#896] opened 2014-03-10 03:25 UTC
MacBook Pro, retina, 15-inch, early 2013 laptop

**Comment by eduramiba** [comment] 2015-08-26 17:04
Possible duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:04 UTC
