### ISSUE TITLE
Facing Issues while loading csv file to gephi 

### ISSUE THREAD

**Issue by JDharminSiddesh** [gephi/gephi#1339] opened 2016-02-04 11:00 UTC
Hi i am a new user to gephi . I am not able to view a graph while loading through csv.

I got two table one for edges and other for nodes

i first loaded the node table

node table
Id,Label,SquareFootage
1,Office,224
2,Kitchen,230

then loaded the edge table

edge  table
Source,Target,Type,Id,Weight,Average Degree
1,3,Undirected,1,1.0,1.0
2,10,Undirected,8,1.0,1.0

then 

on clicking the overview the screen seems to be blank 
on clicking the preview i am getting the below screenshot

![image](https://cloud.githubusercontent.com/assets/12684041/12813175/66499506-cb5c-11e5-9a0b-d1d703d15034.png)

**Comment by eduramiba** [comment] 2016-02-04 11:02
Duplicate of #1247 
Update your installation with Tools - Plugins to fix this.

**Closed by eduramiba** 2016-02-04 11:02 UTC

**Comment by JDharminSiddesh** [comment] 2016-02-04 12:39
Thank you so much it worked
