### ISSUE TITLE
Website registration blocks a WRONG IP !!!

### ISSUE THREAD

**Issue by rjalexa** [gephi/gephi#1449] opened 2016-04-02 13:16 UTC
Dear friends,
I just tried joining the Forums but my registration was blocked with the following message:

"Your IP 188.114.102.118 has been blocked "

This is very strange since I have a public routable static IP address which is 2.236.244.225 (given by my ISP Fastweb here in Rome - Italy).

Can you please check and tell me if there's anything I can to to avoid this ?

Thank you in advance

**Comment by eduramiba** [comment] 2016-04-04 08:12
Duplicate of #1047

**Closed by eduramiba** 2016-04-04 08:12 UTC
