### ISSUE TITLE
Not good on Windows 10 x64

### ISSUE THREAD

**Issue by port513** [gephi/gephi#1185] opened 2015-11-12 18:52 UTC
It doesn't start on my Windows 10 x64.
After splash screen it just not start up the software :(

Would really like to use this but as for now I can't make it start.

**Comment by duncdrum** [comment] 2015-11-12 22:50
what is your java version? just type the following in command client:
````
java -version
````

**Comment by port513** [comment] 2015-11-13 05:14
Hi,

Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

But I don't have it in my path but all other software finds it and use it.





Med vänliga hälsningar

Henrik Holmberg

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Mailvelope v0.13.2
Comment: https://www.mailvelope.com

xsFNBFOhVV0BEADxG58KkqZJNjSIN3YSUwU/XkCcj+yv55EGZ8RwedUmrRtW
JKCSjo1Kh8aNe2MpydJGa1MyR8DAM5ybRB16PxYgouktW+Ao/m1hbYgm7nRT
wh50oSJ4guAIbs+dBpiSA6jxRrtCm6QVA6xxKT8rw5ykV8G/bLMac/PzUBrj
c3uL/YrwDtMs6wP4Q84ZLBbPJPA4aCdD9uncl54Wh1GoVnB1o3y/lMvooDk/
+NqFgaGgzUTSQB9kJO//E4+wx5+aAziwXxsiLRVGGD34ZMZLEDMYmIGDqp4Q
1lT1Ek6VAESToSVrU+bBki6zFFi3WRfNuSA3lJH9n6J5IDaxZM34MCR/uXkF
03onyv1L+1vWXdfNbSRvWDlcs/fR3OFdA4BQOtqRn8WjqQJcyW0/rNhDF0iT
I2VKuw1GD5azfx77vZb8qVqzbbC7xOSqKMcGyBeQOslsOWS8Zrn95C8GDatS
dwly6KWqGggQvixpYA7/H48darIICMn7OnYnqk/XdWkQy2J/VgD6bNbBVzdK
u/XHF/SOStsgm09RG14ocGM9qwt+XMpOjJ32crkP9nft3A9ffjj6wdO4zkCQ
OuykecIHa/Q9927kmQuRM8wSBgaG0gr1uN6krdhI+cUskYCUOFetxJWcXzBF
H4UnojahouIgWeaZ0nx1LFXdSDjbF0sikcnbKQARAQABzSNIZW5yaWsgSG9s
bWJlcmcgPHBvbXptNjdAZ21haWwuY29tPsLBeQQTAQIAIwUCU6FVXQIbAwcL
CQgHAwIBBhUIAgkKCwQWAgMBAh4BAheAAAoJEL0WGnWDRLQqzNkQANybYczc
4F5TbHEid75T/rTdUDxVQS4Rgc2zrZvj2179sUZ+7QYQIsmTUgB3jpjzWcE4
1g/Kq5oRK+47ESbB7t7LFPijgRhn7SVEoDlEKdeSm/mNEtxlK/JdIK5AXYnv
F796Chex6uYVYDob5H+ZWMtPb52jIF0nVEwcSZm0aBTBwM3ptmdDqvNo/KXw
pATTN74vRP2ZYVSfZBXxfeB1hstwMXeH2Y46E8QPf5gMajh2IpIfA6Nk1Qhv
La1XEONu2oIvs7y8vNlVXZh0xEeT4yfa+9t0EWWJaXWslvoHQjooBN6j5s95
LVK8I2CrXHjBEfBurGnu/IWuF8TL+CgDA5C/pAnNaE2BYapQI32KoGmkV065
dnwGA7ep8ekPvxZ9jura7kHktm7DfBfM36NgDBt0POwXFrnxa5m+dY2hCTor
vpW2u9CCS42Knx/z/xWlMs32MXRG0rUyP3y3U5aSp30ekq1VxuMKBkNZPisG
0hq51vViIznphADRrvqJlhBccBbLrzj0XbnuMCdmUcl+gPZ2AeP/Pe0IHkGF
y0m++CSOgmON+UhH42R3L7S7NbR6UK5ulw64CUEGbD8q5oDHzo8Q21iRiCet
UxjfuUZr6CBJaUxPPHGB4tzZQ0YdWjyYNGLWwx52x3LVLog64v1jcxrzw7aQ
42hHbk0XtA6sR9g/zsFNBFOhVV0BEADFOY1x2OeNTFPJ1sqPxgjDkXGJ5agR
E+rF8sD7UOx5Ybqc44mGLgUfvuyGUMYHjawRmI+ouny3lM8CXJACkL0GosHt
ZJX3Vm1G8DDcGne2F3Ma3gkewtB7nW7LqAgYlRPAjkM+GPMZw4ZI03MTc5yY
7z80HqKkPw9TLXuXvSFioBXbvit3n5jLmI9IDrZ8aK23UNhBRNI0x0tYvCun
6Q1+DHDsvy+QmfMqK/1yvl01TCHTX7iBxC9gAjyFREKtVWS7AqPUQqU53k/K
06PaS1YXEwAXuOnO6hogjDXcfgimFjhsXy56jD9NBbJboO/uJrfOZwTe7teo
9PvJEKmjjCSihO+41Kfm+RDSRr4meqm9Mj+uLjZ6XrUIuDwfrvSH+GDYIm/i
LtppxPtzAB5lEHLELh9J18518ZiiMNXFJevd/1X6ZgUgsF+ArakdGWvIYL41
+Jkozg4N8e/MWHjWGzWPG+0RPFs2EiMuV8WdFkNIwWGPUAilBharrD97yBmn
LApo4QSVPf6F57PrZMV/jGaSgHA5s+pIrLU2UqdLaTXQk3jPG+1mmjdb+QHj
QnrFsThj6hI1+6dCHz+SOnYBEDNetwo/lqk6+P6xZNmkPH3qYTI7iaL8hSgV
RYLoYxUh/RaBOd5MskqVi5DjcmL7uk3QcG5XX3/W2cVo8bLC7Cz1JQARAQAB
wsFfBBgBAgAJBQJToVVdAhsMAAoJEL0WGnWDRLQq+soP/iqWX5CWoOafkQNd
i+mBzm5pHmWSzxuD8yfUvgIwLpmCYcJ6TeJUSXWoAVeW0Y94rjspGFLJ1l9Z
+6nzFt202L0H2kGn6esK/hC+ZhEVgcmdXKZ0JLk41PWHzXHdY44QHXLmtFaH
CeCbO/vahc2obJPIiI97+Sn4uh+LtZfqKMtVghSBCdQ4+Q/xSM5vYKWAJqOB
r8ZWByPo5TQsNYw8w5K4cQPP0fP1antUV1uLnO8kZ/smIO1P+iETnukeoqFi
qunCDC4pko7odOTmY0VE/YiTJ2N1l63mOWaoA3fe7zgAoGJBcfr42BAgh5hz
hnQ+YSv/nR4xt0W5ZBSnmRlkOEWXIxqHYaIxBY8yoEEhaMQwxzOoMVZpfvPf
P7S53EKuo5WUpl0Xs0Jc7OCKWGx1ngzgnKMUuzN8DnQUKasp/nEyIbzfJ/UD
KVzNRdd3rKlPGU8LUCDuieNXQFFFc/m8fhwhlPJEOJk06I7he2SxvLs10S+0
WkWng6DsbcA0JKXgj7Hl0gIxIpatz0bP8hv1l688lhzlcuPdZGGLAhuvhl1z
woMaxSq5cyaPO9fQO9/f8zHRTebnn5DAOwsp/XMnY8W5o8y9AkZfD6pDVm35
yWvqgRd7fJLB8cd1ROS3Ndn8VptlfqKHB76pn/E7wugWD+a0Lh1cF48Eb8/S
AXIkMxBU
=i9TW
-----END PGP PUBLIC KEY BLOCK-----

2015-11-12 23:50 GMT+01:00 Duncan Paterson <notifications@github.com>:

**Comment by duncdrum** [comment] 2015-11-13 09:43
looks like java8  (two lines above the line you quoted) try installing java7 and point gephi to it.

**Comment by port513** [comment] 2015-11-13 11:01
Hi,

It's Java 8 and I can't use 7...
Is there a new version on it's way?


/Henrik Holmberg



Med vänliga hälsningar

Henrik Holmberg

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Mailvelope v0.13.2
Comment: https://www.mailvelope.com

xsFNBFOhVV0BEADxG58KkqZJNjSIN3YSUwU/XkCcj+yv55EGZ8RwedUmrRtW
JKCSjo1Kh8aNe2MpydJGa1MyR8DAM5ybRB16PxYgouktW+Ao/m1hbYgm7nRT
wh50oSJ4guAIbs+dBpiSA6jxRrtCm6QVA6xxKT8rw5ykV8G/bLMac/PzUBrj
c3uL/YrwDtMs6wP4Q84ZLBbPJPA4aCdD9uncl54Wh1GoVnB1o3y/lMvooDk/
+NqFgaGgzUTSQB9kJO//E4+wx5+aAziwXxsiLRVGGD34ZMZLEDMYmIGDqp4Q
1lT1Ek6VAESToSVrU+bBki6zFFi3WRfNuSA3lJH9n6J5IDaxZM34MCR/uXkF
03onyv1L+1vWXdfNbSRvWDlcs/fR3OFdA4BQOtqRn8WjqQJcyW0/rNhDF0iT
I2VKuw1GD5azfx77vZb8qVqzbbC7xOSqKMcGyBeQOslsOWS8Zrn95C8GDatS
dwly6KWqGggQvixpYA7/H48darIICMn7OnYnqk/XdWkQy2J/VgD6bNbBVzdK
u/XHF/SOStsgm09RG14ocGM9qwt+XMpOjJ32crkP9nft3A9ffjj6wdO4zkCQ
OuykecIHa/Q9927kmQuRM8wSBgaG0gr1uN6krdhI+cUskYCUOFetxJWcXzBF
H4UnojahouIgWeaZ0nx1LFXdSDjbF0sikcnbKQARAQABzSNIZW5yaWsgSG9s
bWJlcmcgPHBvbXptNjdAZ21haWwuY29tPsLBeQQTAQIAIwUCU6FVXQIbAwcL
CQgHAwIBBhUIAgkKCwQWAgMBAh4BAheAAAoJEL0WGnWDRLQqzNkQANybYczc
4F5TbHEid75T/rTdUDxVQS4Rgc2zrZvj2179sUZ+7QYQIsmTUgB3jpjzWcE4
1g/Kq5oRK+47ESbB7t7LFPijgRhn7SVEoDlEKdeSm/mNEtxlK/JdIK5AXYnv
F796Chex6uYVYDob5H+ZWMtPb52jIF0nVEwcSZm0aBTBwM3ptmdDqvNo/KXw
pATTN74vRP2ZYVSfZBXxfeB1hstwMXeH2Y46E8QPf5gMajh2IpIfA6Nk1Qhv
La1XEONu2oIvs7y8vNlVXZh0xEeT4yfa+9t0EWWJaXWslvoHQjooBN6j5s95
LVK8I2CrXHjBEfBurGnu/IWuF8TL+CgDA5C/pAnNaE2BYapQI32KoGmkV065
dnwGA7ep8ekPvxZ9jura7kHktm7DfBfM36NgDBt0POwXFrnxa5m+dY2hCTor
vpW2u9CCS42Knx/z/xWlMs32MXRG0rUyP3y3U5aSp30ekq1VxuMKBkNZPisG
0hq51vViIznphADRrvqJlhBccBbLrzj0XbnuMCdmUcl+gPZ2AeP/Pe0IHkGF
y0m++CSOgmON+UhH42R3L7S7NbR6UK5ulw64CUEGbD8q5oDHzo8Q21iRiCet
UxjfuUZr6CBJaUxPPHGB4tzZQ0YdWjyYNGLWwx52x3LVLog64v1jcxrzw7aQ
42hHbk0XtA6sR9g/zsFNBFOhVV0BEADFOY1x2OeNTFPJ1sqPxgjDkXGJ5agR
E+rF8sD7UOx5Ybqc44mGLgUfvuyGUMYHjawRmI+ouny3lM8CXJACkL0GosHt
ZJX3Vm1G8DDcGne2F3Ma3gkewtB7nW7LqAgYlRPAjkM+GPMZw4ZI03MTc5yY
7z80HqKkPw9TLXuXvSFioBXbvit3n5jLmI9IDrZ8aK23UNhBRNI0x0tYvCun
6Q1+DHDsvy+QmfMqK/1yvl01TCHTX7iBxC9gAjyFREKtVWS7AqPUQqU53k/K
06PaS1YXEwAXuOnO6hogjDXcfgimFjhsXy56jD9NBbJboO/uJrfOZwTe7teo
9PvJEKmjjCSihO+41Kfm+RDSRr4meqm9Mj+uLjZ6XrUIuDwfrvSH+GDYIm/i
LtppxPtzAB5lEHLELh9J18518ZiiMNXFJevd/1X6ZgUgsF+ArakdGWvIYL41
+Jkozg4N8e/MWHjWGzWPG+0RPFs2EiMuV8WdFkNIwWGPUAilBharrD97yBmn
LApo4QSVPf6F57PrZMV/jGaSgHA5s+pIrLU2UqdLaTXQk3jPG+1mmjdb+QHj
QnrFsThj6hI1+6dCHz+SOnYBEDNetwo/lqk6+P6xZNmkPH3qYTI7iaL8hSgV
RYLoYxUh/RaBOd5MskqVi5DjcmL7uk3QcG5XX3/W2cVo8bLC7Cz1JQARAQAB
wsFfBBgBAgAJBQJToVVdAhsMAAoJEL0WGnWDRLQq+soP/iqWX5CWoOafkQNd
i+mBzm5pHmWSzxuD8yfUvgIwLpmCYcJ6TeJUSXWoAVeW0Y94rjspGFLJ1l9Z
+6nzFt202L0H2kGn6esK/hC+ZhEVgcmdXKZ0JLk41PWHzXHdY44QHXLmtFaH
CeCbO/vahc2obJPIiI97+Sn4uh+LtZfqKMtVghSBCdQ4+Q/xSM5vYKWAJqOB
r8ZWByPo5TQsNYw8w5K4cQPP0fP1antUV1uLnO8kZ/smIO1P+iETnukeoqFi
qunCDC4pko7odOTmY0VE/YiTJ2N1l63mOWaoA3fe7zgAoGJBcfr42BAgh5hz
hnQ+YSv/nR4xt0W5ZBSnmRlkOEWXIxqHYaIxBY8yoEEhaMQwxzOoMVZpfvPf
P7S53EKuo5WUpl0Xs0Jc7OCKWGx1ngzgnKMUuzN8DnQUKasp/nEyIbzfJ/UD
KVzNRdd3rKlPGU8LUCDuieNXQFFFc/m8fhwhlPJEOJk06I7he2SxvLs10S+0
WkWng6DsbcA0JKXgj7Hl0gIxIpatz0bP8hv1l688lhzlcuPdZGGLAhuvhl1z
woMaxSq5cyaPO9fQO9/f8zHRTebnn5DAOwsp/XMnY8W5o8y9AkZfD6pDVm35
yWvqgRd7fJLB8cd1ROS3Ndn8VptlfqKHB76pn/E7wugWD+a0Lh1cF48Eb8/S
AXIkMxBU
=i9TW
-----END PGP PUBLIC KEY BLOCK-----

2015-11-13 10:43 GMT+01:00 Duncan Paterson <notifications@github.com>:

**Comment by duncdrum** [comment] 2015-11-13 11:17
@port513 for now its Java7 or no joy, new version is coming  [soon™](https://gephi.wordpress.com/2015/11/02/announcing-gephi-0-9-release-date/) though.
I think this can be closed.

**Comment by eduramiba** [comment] 2015-11-13 11:25
Thanks for giving help to Henrik.
Closing as duplicate of #748

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-11-13 11:25 UTC
