### ISSUE TITLE
Gephi on OSX does not display any graph

### ISSUE THREAD

**Issue by estefano** [gephi/gephi#817] opened 2013-09-04 19:40 UTC
Gephi 0.82 for Mac OSX hangs after loading a graph (also all three sample graphs). The main (graph) screen remains empty/grey and not further action is possible. Sometimes even closing is not possible any more. Only a kill helps.  Mac OSX 10.7.5, 1.8Ghz i7 with 4GB Ram. Gephi 0.81 works smoothly.

**Comment by eduramiba** [comment] 2015-08-26 19:22
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 19:22 UTC
