### ISSUE TITLE
Bug Report - OSX Splash Screen Crash Version 0.8.2-beta

### ISSUE THREAD

**Issue by ddesmarais58** [gephi/gephi#1070] opened 2015-06-28 10:29 UTC
Hi:
Sorry to report that a new installation of Version 0.8.2-beta on my Macbook Pro running OSX 10.10.3 and Java version * (update 45) crashes. It gets as far as the "splash screen" showing "loadking cached elements" in the lower left corner of the "splash" graphic or screen.

Perhaps I am doing something wrong?
Thanks, Dennis Desmarais
ddesmarais58@me.com

**Comment by eduramiba** [comment] 2015-08-26 15:53
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:53 UTC
