### ISSUE TITLE
Upddate 0.9.0.4

### ISSUE THREAD

**Issue by rbsam** [gephi/gephi#1377] opened 2016-02-13 15:38 UTC
After install updates (19 of them) filters not showing parameters to change in the botton of the page.
I am using MAC OS 10.9.4 and Gephi 0.9.
Details:
java.lang.AbstractMethodError
	at org.gephi.filters.FilterLibraryImpl.buildBuildersMap(FilterLibraryImpl.java:92)
	at org.gephi.filters.FilterLibraryImpl.getBuilder(FilterLibraryImpl.java:137)
	at org.gephi.desktop.filters.FilterPanelPanel$1.run(FilterPanelPanel.java:119)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by eduramiba** [comment] 2016-02-13 22:06
Duplicate of #1370

**Closed by eduramiba** 2016-02-13 22:06 UTC
