### ISSUE TITLE
Gephi freezing during "Starting modules...

### ISSUE THREAD

**Issue by GabrielFerrari** [gephi/gephi#1745] opened 2017-06-29 19:22 UTC
## Expected Behavior
The Gephi will normally. Gephi working well

## Current Behavior
Gephi freezes "Starting modules..."

## Steps to Reproduce

My Windows environment:
https://drive.google.com/a/ciasc.sc.gov.br/file/d/0B0z3OumsONnueU4wbnNfeWd4WlE/view?usp=sharing

1. C:\Users\username\AppData\Roaming\gephi\dev\var\log
-------------------------------------------------------------------------------
>Log Session: Thursday, June 29, 2017 3:27:47 PM BRT
>System Info: 
  Product Version         = Gephi 0.9.1 201510222201
  Operating System        = Windows 7 version 6.1 running on x86
  Java; VM; Vendor        = 1.8.0_131; Java HotSpot(TM) Server VM 25.131-b11; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_131-b11
  Java Home               = C:\Program Files (x86)\Java\jdk1.8.0_131\jre
  System Locale; Encoding = pt_BR (gephi); Cp1252
  Home Directory          = C:\Users\gabrielf
  Current Directory       = C:\Program Files (x86)\Gephi-0.9.1
  User Directory          = C:\Users\gabrielf\AppData\Roaming\.gephi\0.9.1\dev
  Cache Directory         = C:\Users\gabrielf\AppData\Roaming\.gephi\0.9.1\dev\var\cache
  Installation            = C:\Program Files (x86)\Gephi-0.9.1\platform
                            C:\Program Files (x86)\Gephi-0.9.1\gephi
                            C:\Program Files (x86)\Gephi-0.9.1\platform
  Boot & Ext. Classpath   = C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\rt.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\classes;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar
  Application Classpath   = C:\Program Files (x86)\Gephi-0.9.1\platform\lib\boot.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-modules.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-util-lookup.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-util-ui.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-util.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_zh_TW.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\lib\dt.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\lib\tools.jar
  Startup Classpath       = C:\Program Files (x86)\Gephi-0.9.1\platform\core\asm-all-5.0.1.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\core-base.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\core.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\org-netbeans-libs-asm.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\org-openide-filesystems-compat8.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\org-openide-filesystems.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\gephi\core\locale\core_gephi.jar
-------------------------------------------------------------------------------

2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment] 2017-06-29 20:27
Duplicate of #1631

**Closed by eduramiba** 2017-06-29 20:27 UTC
