### ISSUE TITLE
Using a non-english version of windows 7 may corrupt Gephi 0.8.2-beta files

### ISSUE THREAD

**Issue by cherehn** [gephi/gephi#830] opened 2013-09-25 09:07 UTC
We have been having problems with opening saved Gephi-projects getting rather strange error messages. We now think we have discovered why.

We are using Swedish language settings in Windows 7. This seems to lead to some parameters in the gephi file PreviewModel section being replaced with the corresponding swedish words.

For example:
<previewproperty name="edge.show">true</previewproperty>
becomes
<previewproperty name="edge.show">sant</previewproperty>

and 

<previewproperty name="edge.label.show">false</previewproperty>
becomes
<previewproperty name="edge.label.show">falskt</previewproperty>

It would be great if this issue could be addressed!

**Comment by mbastian** [comment] 2016-02-09 10:37
Can you please try again with Gephi 0.9.0, I'm curious if this happens. Thanks!

**Comment by cherehn** [comment] 2016-02-10 15:59
I'm afraid the error seems to persist in 0.9. In the file Workspace_1_previewmodel_xml I find the following parameter if I use a Swedish Windows 7 operating system:
<previewproperty name="edge.show">sant</previewproperty>
<previewproperty name="node.label.box">falskt</previewproperty>

**Comment by mbastian** [comment] 2022-11-11 18:52
I can't reproduce this with more recent versions. Closing the issue, please reopen if it still occurs.

**Closed by mbastian** 2022-11-11 18:52 UTC
