### ISSUE TITLE
Closes on startup

### ISSUE THREAD

**Issue by outofmachina** [gephi/gephi#1016] opened 2015-03-01 18:59 UTC
I'm using Windows 8, but other than that, nothing is different. It has no error message.

**Comment by jackiekazil** [comment] 2015-03-08 21:04
See if this helps: https://medium.com/coder-snorts/gephi-is-broken-on-mac-os-97fbaef4305e

**Comment by outofmachina** [comment] 2015-03-09 00:13
I said it was windows.



—

**Comment by jackiekazil** [comment] 2015-03-09 00:34
Did u read the post?

**Comment by outofmachina** [comment] 2015-03-09 23:51
Yes. It was mac. Windows is not mac.



—

**Comment by jackiekazil** [comment] 2015-03-10 00:29
So.... the post covers both.

Jacqueline Kazil | @jackiekazil

**Comment by outofmachina** [comment] 2015-03-10 15:34
I must have misread then. My mistake. 



—

**Comment by mynewjob** [comment] 2015-03-13 17:37
It works, thanks a lot :)

**Comment by outofmachina** [comment] 2015-03-15 00:36
I followed the instructions to the letter for Windows. Now I can't launch ANYTHING that uses Java.

**Comment by jackiekazil** [comment] 2015-03-15 02:16
@mynewjob -- glad it worked for you. 
@outofmachina -- in this particular case, my recommendation is trace back your steps and undo what what the instructions said to do. The case that is outlined in the post resolved the issue for 20+ people.  For some reason, your case might be different than the case outline in the post. Without sitting directly in front of computer, I can't help you an further.

**Comment by mynewjob** [comment] 2015-03-16 22:34
try this outofmachina
https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Comment by eduramiba** [comment] 2015-08-26 16:34
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:34 UTC
