### ISSUE TITLE
i can not load up Gephi

### ISSUE THREAD

**Issue by 5474103** [gephi/gephi#1029] opened 2015-03-12 07:21 UTC

**Comment by Tas-sos** [comment] 2015-03-25 11:44
Are you on Ubuntu 14.04 32-bit like me?

**Comment by eduramiba** [comment] 2015-08-26 16:51
Possible duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:51 UTC
