### ISSUE TITLE
how to add the value on weight

### ISSUE THREAD

**Issue by weiyangugent** [gephi/gephi#1294] opened 2016-01-14 17:05 UTC
I am a new Gephi learner, and I update the version of Gephi to 0.9. However when I add the data through csv, the value of weight is replaced by '1'. I have tried many times in different data, the problem always happen. But the previous version did not have the issue, so I wander if there is a bug or other possibilities?

**Comment by eduramiba** [comment] 2016-01-14 19:14
Duplicate of #1254 This should be fixed when you install updates (Tools - Plugins - Check for updates).

**Closed by eduramiba** 2016-01-14 19:14 UTC

**Comment by weiyangugent** [comment] 2016-01-15 13:43
yes, it works now, thanks very much, Eduardo

2016-01-14 20:14 GMT+01:00 Eduardo Ramos <notifications@github.com>:
