### ISSUE TITLE
string column not shown in 0.9.0 while opening .gephi file saved by 0.8.2

### ISSUE THREAD

**Issue by songjinghe** [gephi/gephi#1323] opened 2016-01-28 11:51 UTC
I'm just open a .gephi file saved by gephi 0.8.2, I'm using gephi-0.9.0, 
I found all custom string type column in DataLaboratory not show its content(empty content, but headers shown),
although you can use the lost column to color nodes in Overview.

**Comment by mbastian** [comment] 2016-01-28 12:18
Duplicate of #1320

**Closed by mbastian** 2016-01-28 12:18 UTC
