### ISSUE TITLE
Gephi 0.82 won't start; libjogl problem. Again.

### ISSUE THREAD

**Issue by bradjcox** [gephi/gephi#754] opened 2013-03-03 22:57 UTC
Fails during startup with unable to load libjogl.awt.jnilib. Brand new download today. MacOSX latest. There's no libjogl in the extensions folder.

Issue was closed a year ago, incorrectly it seems. What now?

**Comment by eduramiba** [comment] 2015-08-26 16:29
Probable duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:29 UTC
