### ISSUE TITLE
Can't install GEPHI

### ISSUE THREAD

**Issue by Brigitte54** [gephi/gephi#1124] opened 2015-09-15 09:02 UTC
I try to download GEPHI version 8.0.2 
My windows version is 6.1
I cannot succeed 
Could you help ? 
thanks 
Brigitte

**Comment by techtonik** [comment] 2015-09-15 14:51
Try nightly/beta 0.9

**Comment by eduramiba** [comment] 2015-09-15 15:24
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

Don't try nightly 0.9 since it's not usable yet

**Closed by eduramiba** 2015-09-15 15:24 UTC
