### ISSUE TITLE
cant open Gephi 0.8.2 after installation

### ISSUE THREAD

**Issue by MichelleHeart** [gephi/gephi#886] opened 2014-02-08 03:57 UTC
I cant open Gephi 0.8.2 after installation. No error message. Once I launch the application it will  open but after a few seconds it will close automatically. Any resolution please??

**Comment by eduramiba** [comment] 2015-08-26 17:05
Possible duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:05 UTC
