### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by carlosgp2** [gephi/gephi#887] opened 2014-02-10 07:45 UTC
I installed java, downloaded the application, drag into application folder and when I click on it nothing happens. 
Any ideas

**Comment by eduramiba** [comment] 2015-08-26 17:04
Possible duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:04 UTC
