### ISSUE TITLE
New installation 0.8.2 Beta won't start

### ISSUE THREAD

**Issue by allbrancake** [gephi/gephi#1191] opened 2015-11-23 13:14 UTC
Hi  - just installed Gephi on Win10 machine and I can get no further than the startup screen (displays "loading cached" objects" in bottom left - see attached
![gephi startup screen](https://cloud.githubusercontent.com/assets/15981111/11337319/00fe11ce-91e4-11e5-99fe-6fab7e15f1b7.PNG)
). I have restarted computer since download. The screen disappears and nothing opens. 

Initially Gephi said that I didn't have Java installed - have done this now (then restarted) but still no luck.

many thanks

**Comment by computermacgyver** [comment] 2015-11-23 13:15
You will either need to install Java 7 or wait until the new version of Gephi is released in December. See #1185 for more details.

You could also try out the nightly build of the new version that is listed at:
https://github.com/gephi/gephi

Note, however, that the nightly build is under active development and hence may have some issues.

**Comment by eduramiba** [comment] 2015-11-23 13:27
Thanks for the help Scott
Closing as duplicate of #748

**Closed by eduramiba** 2015-11-23 13:27 UTC
