### ISSUE TITLE
Mac OS 10.8 seems to cause crashes

### ISSUE THREAD

**Issue by richtera** [gephi/gephi#842] opened 2013-10-16 19:55 UTC
The latest SNAPSHOT doesn't hang but only imports a single vertex even if the file has a whole network.
The 0.8.2 build just hangs after the import successfully shows the network being loaded.
I am not quite sure what to look at to get you more information, but I'd love to use the product.

**Comment by eduramiba** [comment] 2015-08-26 15:57
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:57 UTC
