### ISSUE TITLE
Nodes do not appear when exporting to PDF and SVG files

### ISSUE THREAD

**Issue by annmclark** [gephi/gephi#1760] opened 2017-07-26 00:10 UTC
Nodes should appear when I export to any format.

I only see them when I export PNG files.

I'm using the following:

Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_141; Java HotSpot(TM) Client VM 25.141-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_141-b15
System: Windows 10 version 10.0 running on x86; Cp1252; en_US (gephi)
User directory: C:\Users\aclark\AppData\Roaming.gephi\0.9.1\dev
Cache directory: C:\Users\aclark\AppData\Roaming.gephi\0.9.1\dev\var\cache

Many thanks for any help you can give me.

[test12.pdf](https://github.com/gephi/gephi/files/1175118/test12.pdf)
![test10](https://user-images.githubusercontent.com/25087960/28598985-0b9078f8-715c-11e7-86e7-cf87fd7dfbc0.png)

**Comment by duncdrum** [comment] 2017-07-26 08:01
duplicate of #1759 ?

**Comment by JLOlivares** [comment] 2017-07-30 13:09
See my post on #1759. If you are using the Polygon shaped nodes plugin, uninstall it and see if the nodes appear.

**Comment by eduramiba** [comment] 2017-07-30 16:56
Duplicate of #1759

**Closed by eduramiba** 2017-07-30 16:56 UTC

**Comment by annmclark** [comment] 2017-08-01 16:04
Oh thank you!!!  That did the trick.  Much appreciated.
