### ISSUE TITLE
Saying that it cannot detect java 1.8, but I download it and it till does not work

### ISSUE THREAD

**Issue by tloganwest** [gephi/gephi#1960] opened 2018-04-29 22:28 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2018-04-30 07:15
Duplicate of #1787 
Make sure to have java 8 not 9 or 10, and try to use a 64 bit Java 8 build.

**Closed by eduramiba** 2018-04-30 07:15 UTC
