### ISSUE TITLE
Gephi and W10

### ISSUE THREAD

**Issue by Zelinkai** [gephi/gephi#1188] opened 2015-11-21 12:19 UTC
Hi, Gephi 0.8.2 does not work at Windows 10. After welcome screen it imply vanish.
Please advice.
thnx
Ivan

**Comment by computermacgyver** [comment] 2015-11-21 12:27
Hi Ivan, You will either need to install Java 7 or wait until the new version of Gephi is released next month.

See #1185 for more details.

**Comment by computermacgyver** [comment] 2015-11-21 12:29
You could also try out the nightly build of the new version that is listed at:
https://github.com/gephi/gephi

Note, however, that the nightly build is under active development and hence may have some issues.

**Comment by eduramiba** [comment] 2015-11-23 13:28
Thanks for the help Scott.
Closing as duplicate of #748

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6 on Windows.

**Closed by eduramiba** 2015-11-23 13:28 UTC
