### ISSUE TITLE
FilterModelPersistenceProvider Error when opening Gephi file 

### ISSUE THREAD

**Issue by swiss00** [gephi/gephi#2000] opened 2018-07-24 08:25 UTC
## Current Behavior
When I open the file, nothing happens except the error message here below.

## Possible Solution

I suspect the fact that I have saved some filters (and I didn't do that before. Also I put a "** at the begininig of the name of the filter.
 

## Steps to Reproduce

1. Open file
2. Error message

## Context

Very affected. I'm losing a full week of work.
Needed for an important analysis.
Would really appreciate if a quick fix is possible.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: 

INFO] Turning on modules: 
[INFO] 	org.openide.util.lookup [8.33.1 201609300101]
	org.openide.util [9.7.1 201609300101]
	org.openide.util.ui [9.6.1 201609300101]
	org.openide.modules [7.48.1 201609300101]
	org.netbeans.api.annotations.common/1 [1.27.1 201609300101]
	org.openide.filesystems [9.10.1 201609300101]
	org.openide.awt [7.67.1 201609300101]
	org.netbeans.api.progress/1 [1.47.1 201609300101]
	org.netbeans.api.progress.nb [1.47.1 201609300101]
	org.openide.dialogs [7.42.1 201609300101]
	org.openide.nodes [7.45.1 201609300101]
	org.openide.windows [6.75.1 201609300101]
	org.netbeans.modules.editor.mimelookup/1 [1.40.1 201609300101]
	org.openide.text [6.67.1 201609300101]
	org.netbeans.swing.tabcontrol [1.56.1 201609300101]
	org.netbeans.swing.outline [1.34.1 201609300101]
	org.openide.explorer [6.62.1 201609300101]
	org.openide.actions [6.39.1 201609300101]
	org.netbeans.modules.queries/1 [1.43.1 201609300101]
	org.netbeans.api.templates [1.7.1 201609300101]
	org.openide.filesystems.nb [9.9.1 201609300101]
	org.openide.loaders [7.66.1 201609300101]
	org.netbeans.api.intent [1.2.1 201609300101]
	org.netbeans.api.io [1.3.1 201609300101]
	org.openide.io [1.49.1 201609300101]
	org.openide.filesystems.compat8 [9.9.1 201609300101]
	org.netbeans.swing.plaf [1.41.1 201609300101]
	org.netbeans.spi.quicksearch [1.27.1 201609300101]
	org.netbeans.modules.templates/1 [1.7.1 201609300101]
	org.netbeans.libs.asm [5.3.1 201609300101]
	org.netbeans.bootstrap/1 [2.76.1 201609300101]
	org.netbeans.core.startup.base [1.62.1.1 1 201609300101]
	org.netbeans.core.startup/1 [1.62.1.1 201609300101]
	org.netbeans.modules.settings/1 [1.49.1 201609300101]
	org.netbeans.modules.sendopts/2 [2.35.1 201609300101]
	org.netbeans.modules.sampler [1.14.1 201609300101]
	org.netbeans.modules.progress.ui [1.33.1 201609300101]
	org.netbeans.modules.keyring [1.24.1 201609300101]
	org.netbeans.core/2 [3.51.1 201609300101]
	org.netbeans.modules.options.api/1 [1.45.1 201609300101]
	org.netbeans.modules.options.keymap [1.37.1 201609300101]
	org.netbeans.libs.jna/1 [1.44.1 201609300101]
	org.netbeans.modules.masterfs/2 [2.55.1.2 2 201609300101]
	org.netbeans.modules.masterfs.windows [1.16.1 201609300101]
	org.netbeans.modules.masterfs.ui [2.3.1.2 201609300101]
	org.netbeans.modules.masterfs.nio2 [1.15.1 201609300101]
	org.netbeans.modules.keyring.fallback [1.8.1 201609300101]
	org.netbeans.modules.keyring.impl [1.24.1 201609300101]
	org.netbeans.modules.autoupdate.services [1.52.1 201609300101]
	org.netbeans.modules.autoupdate.ui [1.45.1 201609300101]
	org.netbeans.modules.autoupdate.cli [1.13.1 201609300101]
	org.netbeans.libs.jna.platform/1 [1.14.1 201609300101]
	org.netbeans.core.windows/2 [2.81.1 201609300101]
	org.netbeans.core.ui/1 [1.45.1 201609300101]
	org.netbeans.core.output2/1 [1.41.1 201609300101]
	org.netbeans.core.network [1.10.1 201609300101]
	org.netbeans.core.nativeaccess/1 [1.31.1 201609300101]
	org.netbeans.core.multitabs/1 [1.12.1.1 1 201609300101]
	org.netbeans.core.io.ui/1 [1.30.1 201609300101]
	org.gephi.core.library.wrapper [0.9.2 0.9.2 201709241108]
	org.gephi.utils.longtask [0.9.2 0.9.2 201709241107]
	org.gephi.project.api [0.9.2.1 0.9.2 201711180139]
	org.gephi.graph.api [0.9.2 0.9.2 201709241107]
	org.gephi.utils [0.9.2 0.9.2 201709241108]
	org.gephi.ui.library.wrapper [0.9.2 0.9.2 201709241109]
	org.gephi.lib.validation [0.9.2 0.9.2 201709241109]
	org.gephi.ui.utils [0.9.2 0.9.2 201709241110]
	org.gephi.ui.components [0.9.2 0.9.2 201709241111]
	org.gephi.db.drivers [0.9.2 0.9.2 201709241110]
	org.gephi.io.importer.api [0.9.2.2 0.9.2 201711180141]
	org.gephi.mostrecentfiles.api [0.9.2 0.9.2 201709241113]
	org.gephi.desktop.project [0.9.2 0.9.2 201709241113]
	org.gephi.welcome.screen [0.9.2 0.9.2 201709241114]
	org.gephi.datalab.api [0.9.2 0.9.2 201709241109]
	org.gephi.visualization.api [0.9.2 0.9.2 201709241109]
	org.gephi.tools.api [0.9.2 0.9.2 201709241112]
	org.gephi.gleem [0.9.2 0.9.2 201709241113]
	org.gephi.visualization [0.9.2 0.9.2 201709241113]
	org.gephi.ui.propertyeditor [0.9.2 0.9.2 201709241116]
	org.gephi.algorithms.plugin [0.9.2 0.9.2 201709241113]
	org.gephi.tools.plugin [0.9.2 0.9.2 201709241114]
	org.gephi.statistics.api [0.9.2 0.9.2 201709241111]
	org.gephi.statistics.plugin [0.9.2 0.9.2 201709241111]
	org.gephi.filters.api [0.9.2 0.9.2 201709241112]
	org.gephi.appearance.api [0.9.2 0.9.2 201709241112]
	org.gephi.filters.plugin [0.9.2.1 0.9.2 201711180143]
	org.gephi.timeline.api [0.9.2 0.9.2 201709241112]
	org.gephi.statistics.plugin.ui [0.9.2 0.9.2 201709241111]
	org.gephi.settings.upgrader [0.9.2 0.9.2 201709241111]
	org.gephi.project.ui [0.9.2 0.9.2 201709241110]
	org.gephi.io.processor.plugin [0.9.2.2 0.9.2 201711180141]
	org.gephi.processor.plugin.ui [0.9.2 0.9.2 201709241110]
	org.gephi.batik.wrapper [0.9.2 0.9.2 201709241108]
	org.gephi.preview.api [0.9.2 0.9.2 201709241108]
	org.gephi.preview.plugin [0.9.2 0.9.2 201709241109]
	org.gephi.io.exporter.api [0.9.2 0.9.2 201709241108]
	org.gephi.io.exporter.preview [0.9.2 0.9.2 201709241108]
	org.gephi.preview.export.ui [0.9.2 0.9.2 201709241109]
	org.gephi.perspective.api [0.9.2 0.9.2 201709241118]
	org.gephi.layout.api [0.9.2 0.9.2 201709241115]
	org.gephi.layout.plugin [0.9.2 0.9.2 201709241116]
	org.gephi.io.importer.plugin [0.9.2.2 0.9.2 201711180146]
	org.gephi.io.generator.api [0.9.2 0.9.2 201709241115]
	org.gephi.io.generator.plugin [0.9.2 0.9.2 201709241115]
	org.gephi.io.exporter.plugin [0.9.2.1 0.9.2 201711180145]
	org.gephi.import.plugin.ui [0.9.2.1 0.9.2 201711180147]
	org.gephi.gephi.branding [0.9.2 0.9.2 201709241107]
	org.gephi.generator.plugin.ui [0.9.2 0.9.2 201709241115]
	org.gephi.desktop.banner [0.9.2 0.9.2 201709241119]
	org.gephi.filters.plugin.ui [0.9.2 0.9.2 201709241119]
	org.gephi.filters.impl [0.9.2.1 0.9.2 201711180147]
	org.gephi.export.plugin.ui [0.9.2 0.9.2 201709241118]
	org.gephi.directory.chooser [0.9.2 0.9.2 201709241121]
	org.gephi.desktop.tools [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.timeline [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.statistics [0.9.2 0.9.2 201709241115]
	org.gephi.desktop.recent.files [0.9.2 0.9.2 201709241118]
	org.gephi.desktop.progress [0.9.2 0.9.2 201709241114]
	org.gephi.desktop.io.export [0.9.2 0.9.2 201709241116]
	org.gephi.desktop.preview [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.layout [0.9.2 0.9.2 201709241119]
	org.gephi.desktop.import [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.generate [0.9.2 0.9.2 201709241116]
	org.gephi.desktop.filters [0.9.2 0.9.2 201709241122]
	org.gephi.desktop.datalab [0.9.2 0.9.2 201709241116]
	org.gephi.desktop.context [0.9.2 0.9.2 201709241114]
	org.gephi.desktop.branding [0.9.2 0.9.2 201709241114]
	org.gephi.appearance.plugin [0.9.2 0.9.2 201709241116]
	org.gephi.appearance.plugin.ui [0.9.2 0.9.2 201709241117]
	org.gephi.desktop.appearance [0.9.2 0.9.2 201709241117]
	org.gephi.datalab.plugin [0.9.2 0.9.2 201709241119]
	nl.cloudfarming.client.lib.platform.l10n [1.1 1.1-NB80 201411231331]
 
[INFO] System network proxy resolver: Windows 
[INFO] Windows system proxy resolver: auto detect 
[INFO] System network proxy reloading succeeded. 
[INFO] System network proxy - mode: direct 
[INFO] System network proxy: fell to default (correct if direct mode went before) 
[INFO] USG_LOOK_AND_FEEL 
[WARNING] Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5. 
[WARNING] use of system property netbeans.user has been obsoleted in favor of InstalledFileLocator/Places at org.gephi.ui.upgrader.Upgrader.getCurrentVersion(Upgrader.java:123) 
[INFO] Current Version is 092 
[INFO] GL_VENDOR: Intel 
[INFO] GL_RENDERER: Intel(R) HD Graphics 5500 
[INFO] GL_VERSION: 4.3.0 - Build 10.18.14.4280 
[INFO] GL_SURFACE_SCALE: 1 
[INFO] Diagnostic information
Input arguments:
	-Xms64m
	-Xmx512m
	-Xverify:none
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-XX:MaxPermSize=384m
	-Dnetbeans.user.dir=C:\Users\mma\Desktop
	-Djdk.home=C:\Program Files\Java\jdk1.8.0_72
	-splash:C:\Users\mma\AppData\Roaming\.GEPHI\0.9.2\dev\var\cache\splash.png
	-Djdk.launcher.addexports.0=java.desktop/sun.awt=ALL-UNNAMED
	-Djdk.launcher.addexports.1=java.base/jdk.internal.jrtfs=ALL-UNNAMED
	-Djdk.launcher.addexports.2=java.desktop/java.awt.peer=ALL-UNNAMED
	-Djdk.launcher.addexports.3=java.desktop/com.sun.beans.editors=ALL-UNNAMED
	-Djdk.launcher.addexports.3=java.desktop/sun.awt.im=ALL-UNNAMED
	-Djdk.launcher.addexports.4=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
	-Djdk.launcher.addexports.5=java.management/sun.management=ALL-UNNAMED
	-Dnetbeans.home=C:\Program Files\Gephi-0.9.2\platform
	-Dnetbeans.user=C:\Users\mma\AppData\Roaming\.GEPHI\0.9.2\dev
	-Dnetbeans.default_userdir_root=
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\mma\AppData\Roaming\.GEPHI\0.9.2\dev\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Dnetbeans.dirs=C:\Program Files\Gephi-0.9.2\platform;C:\Program Files\Gephi-0.9.2\gephi
	exit
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 64.0MB maximum 455.5MB
Non heap memory usage: initial 2.4MB maximum -1b
Garbage collector: PS Scavenge (Collections=11 Total time spent=0s)
Garbage collector: PS MarkSweep (Collections=2 Total time spent=0s)
Classes: loaded=7403 total loaded=7403 unloaded 0
 
[INFO] Total memory 17'045'925'888 
[INFO] Total physical memory 17'045'925'888 
[WARNING] Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance], but some are: [ToggleFullScreenAction.shadow] 
[WARNING] Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url 
[WARNING] Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url 
[SEVERE] null 
org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: NullPointerException : null
File: org.gephi.filters.FilterModelPersistenceProvider
Line : 295
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.gephi.filters.FilterModelPersistenceProvider.readQuery(FilterModelPersistenceProvider.java:295)
	at org.gephi.filters.FilterModelPersistenceProvider.readXML(FilterModelPersistenceProvider.java:198)
	at org.gephi.filters.FilterModelPersistenceProvider.readXML(FilterModelPersistenceProvider.java:88)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenXML(LoadTask.java:298)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:128)
	... 7 more

[INFO] External Changes Refresh on focus gain disabled

**Comment by mbastian** [comment] 2022-03-08 19:48
Hi, I was not able to reproduce this issue on the latest [0.9.3 nightly build](https://github.com/gephi/gephi#nightly-builds). We have made some improvements in the Gephi IO part so maybe this fixed this issue as well. I'm closing but feel free to reopen if the problem persists once you get to try the new version. Thx!

**Closed as completed by mbastian** 2022-03-08 19:48 UTC
Labels: Filters, IO
