### ISSUE TITLE
Cannot open gephi on OS X Yosemite 10.10 (14A389)

### ISSUE THREAD

**Issue by Amelia12** [gephi/gephi#971] opened 2014-11-01 04:52 UTC
Gephi worked well before I update the operation system recently. However, after that, when I open it, I saw "Loading cached work...." and then gephi quits automatically.

**Comment by eduramiba** [comment] 2015-08-26 16:55
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:55 UTC
