### ISSUE TITLE
Gephi 0.9.2 "Graph" window stuck on "Initializing..."

### ISSUE THREAD

**Issue by penyuan** [gephi/gephi#2189] opened 2020-05-14 17:33 UTC
## Expected Behavior

Successfully load and view graphs in a workspace.

## Current Behavior

The "Graph" window in my workspace is always stuck on "Initializing..." without ever showing the graph.

## Possible Solution

I can't think of any.

## Steps to Reproduce

1. Download latest official binary of Gephi 0.9.2 from official website.
2. Start Gephi.
3. In the "Welcome" dialog, select one of the samples such as `Les Miserables.gexf` (same problem happens with other `.gexf` files).
4. The "Import report" window would successfully report the number of nodes (77) and edges (254). Click OK.
5. After clicking OK in the "Import report" window (I tried selecting both "New workspace" and "Append to existing workspace" with no difference), the "Graph" tab in the main Gephi window would show "Initializing..." without ever actually showing the graph.

(strangely, I **can** see the graph in the "Preview" tab)

Here is a screenshot of the "Graph" window stuck on "Initializing...":

![](https://wtf.roflcopter.fr/pics/vlnr31pM/BWOXjdJd)

## Context

I am simply trying to view a graph.

## Your Environment

* Version used: Gephi 0.9.2 201709241107
* Java version: OpenJDK 1.8.0_252 (`javac` version **14**)
* Operating System: [Red Hat Enterprise Linux (RHEL)](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux) 8.2 (Linux kernel 4.18.0 with Gnome 3.32.2)

**Comment by bgrt** [comment] 2020-05-29 07:24
Experiencing the same issue:

- Version used: gephi 0.9.2-2
- Java version: openjdk 10.0.2 2018-07-17
- Operating System: Linux Kernel 5.6.10-arch1-1

**Comment by eduramiba** [comment] 2020-05-29 07:31
Gephi only works with Java 8 at the moment

**Comment by bgrt** [comment] 2020-05-29 08:09
@eduramiba thanks for the quick reply!

I reinstalled java to:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

but still have the same issue...

**Comment by bgrt** [comment] 2020-05-30 08:58
`$ export LIBGL_ALWAYS_SOFTWARE=1`  solved the problem for me!

**Comment by penyuan** [comment] 2020-05-30 15:34
Glad to hear it worked for you @bgrt! Unfortunately it still doesn't for me. I also have OpenJDK 1.8.0_252 as stated in my original post.

Did you start gephi from the commandline? Here's what I tried:

1. `export LIBGL_ALWAYS_SOFTWARE=1` from the commandline, and confirmed with `echo LIBGL_ALWAYS_SOFTARE`.

2. Run `gephi` from the commanline.

3. Same problem as before.

Can anyone advise on how to continue troubleshooting this, well, troublesome problem?

**Comment by bgrt** [comment] 2020-06-01 08:21
Yes, I `export` on the command line (saved it to my `.bashrc` to load it every time I start my terminal) and start gephi from command line. 

Do you have an "one way street sign" in the right bottom corner of your gephi window?
If yes, there is an error. You must have some log output in `.gephi/0.9.2/dev/var/log`. Could you please post it here?

**Comment by penyuan** [comment] 2020-06-01 13:16
> Do you have an "one way street sign" in the right bottom corner of your gephi window?
> If yes, there is an error. You must have some log output in `.gephi/0.9.2/dev/var/log`. Could you please post it here?

Ah yes, it is there! Here is the error output:

```
java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI starting from ModuleCL@572c61fa[org.gephi.ui.utils] with possible defining loaders null and declared parents [ModuleCL@6a720964[org.gephi.utils], ModuleCL@3ef0b4e2[org.gephi.graph.api], ModuleCL@6cc08f24[org.gephi.lib.validation], org.netbeans.MainImpl$BootClassLoader@28c97a5, ModuleCL@4e334cb4[org.gephi.core.library.wrapper]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsButtonUI
	at org.gephi.ui.utils.UIUtils.fixButtonUI(UIUtils.java:385)
	at org.gephi.visualization.component.VizToolbar.add(VizToolbar.java:94)
	at org.gephi.visualization.component.VizToolbar.<init>(VizToolbar.java:65)
	at org.gephi.visualization.component.VizBarController.getToolbar(VizBarController.java:116)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:120)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by bgrt** [comment] 2020-06-02 13:40
can you please post the whole output of `$ java -version` and `$ javac -version` and
in case you're using rpm as package manager the installed java packages :)

did you installed gephi with the package manger or manually from source?

**Comment by bgrt** [comment] 2020-06-02 13:44
You could try the recommendations from this thread:

https://github.com/gephi/gephi/issues/1997#issuecomment-410280595

**Comment by penyuan** [comment] 2020-06-04 10:28
Thanks @bgrt , to be safe I've reinstalled by Java packaged so that I have the following:

`$ java -version`:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

`$ javac -version`:
```
javac 1.8.0_252
```

The RPM packages I explicitly installed were `java-1.8.0-openjdk-devel` and `java-1.8.0-openjdk`. And as I stated in my original post, I am running RHEL 8.2 with Linux kernel 4.18.0.

With the above, opening Gephi still gives me the problem I described in my original post.

**Comment by bgrt** [comment] 2020-06-05 13:31
I think you need the `openjdk-8-jre` package as well (its the Java Runtime Environment)

at least its listed as dependency for [arch linux gephi](https://www.archlinux.org/packages/community/any/gephi/)

**Comment by penyuan** [comment] 2020-06-09 21:43
Thanks @bgrt and @eduramiba for your comments. After much fiddling and re-installing all my Java related packages from my distribution's repositories, I finally solved this problem and my graph is now showing in the preview panel! I just don't know exactly which part of the process fixed my problem, and I'm afraid if I start from scratch one day the problem will re-surface. Oh well.

One more quick question: Is there a way to set the `LIBGL_ALWAYS_SOFTWARE=1` option in Gephi's own configuration *or* startup file somewhere? This way, I don't have to set this globally for my whole environment.

**Comment by tmantynen** [comment] 2020-06-24 08:42
Thank you everybody. I just wanted to let you know I had the same problem. I was able to solve it with the instructions in this thread. I did try Oracle's Java 1.8.0_251-b08 but that didn't work. What finaly worked was OpenJDK 1.8 and, very importantly, setting `LIBGL_ALWAYS_SOFTWARE=1`

Kubuntu 20.04 LTS (Focal Fossa)
Product Version: Gephi 0.9.2 201709241107
Java: 1.8.0_252; OpenJDK 64-Bit Server VM 25.252-b09
Runtime: OpenJDK Runtime Environment 1.8.0_252-8u252-b09-1ubuntu1-b09
System: Linux version 5.4.0-37-generic running on amd64; UTF-8; en_US (gephi)

**Comment by rmdes** [comment] 2020-11-22 13:11
Pheew took a while to figure this out but I had the same behavior, took me way too much time to figure out I had the wrong java version (version 11) I tried to have java 8 and 11 side by side and using ╰─ sudo update-alternatives --config java to pick one version, the problem is no matter what I did, Gephi was always operating from version 11, so finally I removed java 11 altogether and now I'm running Gephi just fine !                                                                                                                                                                                                  ─╯

**Comment by lerouxrgd** [comment] 2021-01-14 14:17
I have a SIGSEGV with `LIBGL_ALWAYS_SOFTWARE=1` and without it the window is stuck on "initializing ...".

OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.10.2-2-MANJARO

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

```
LIBGL_ALWAYS_SOFTWARE=1 bin/gephi                            

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=815256, tid=0x00007fde84efb640
#
# JRE version: OpenJDK Runtime Environment (8.0_265-b01) (build 1.8.0_265-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.265-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump written. Default location: /home/rleroux/dev/tools/gephi-0.9.2/core or core.815256
#
# An error report file with more information is saved as:
# /home/rleroux/dev/tools/gephi-0.9.2/hs_err_pid815256.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
bin/../platform/lib/nbexec: line 470: 815256 Aborted                 (core dumped)
```

**Comment by alxleroux** [comment] 2021-01-21 12:03
Same issues, same os as @lerouxrgd 

I think a recent update broke the "export" fix.

**Comment by AlfCano** [comment] 2021-01-29 05:49
Thanks!!
`export LIBGL_ALWAYS_SOFTWARE=1`
Did the trick!!!
I just added the command to the launcher script...
`xed ./gephi-0.9.2/bin/gephi`
And pasted the command right after the last comment  `#` so 
it looks like:
```
#
export LIBGL_ALWAYS_SOFTWARE=1
PRG=$0
```
And there you go, set the launcher as you like...

**Comment by pagabuc** [comment] 2021-02-23 22:17
@lerouxrgd @alxleroux and everyone who has the "Initializing" bug or the "fatal error" with `LIBGL_ALWAYS_SOFTWARE`, [this fix](https://github.com/gephi/gephi/issues/1836#issuecomment-658413204) from @packmad is what worked for me:
```
$ export MESA_LOADER_DRIVER_OVERRIDE=i965
$ ./gephi
```
Kudos to him!

**Comment by chomwitt** [comment] 2021-03-18 08:13
> > Do you have an "one way street sign" in the right bottom corner of your gephi window?
> > If yes, there is an error. You must have some log output in `.gephi/0.9.2/dev/var/log`. Could you please post it here?
> 
> Ah yes, it is there! Here is the error output:
> 
> ```
> java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	...

In Debian 10 , clicking in the 'red circle' in the lower rigth corner the same erros will be displayed. 
As  you can see in #2251 i tried older versions and export LIBGL_ALWAYS_SOFTWARE=1 but they didnt help.

**Comment by chomwitt** [comment] 2021-03-18 08:28
At last !!!!! 
./gephi --jdkhome /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/

**Comment by guibou** [comment] 2021-12-03 16:22
I do have the same problem, with java 8.

The "fix" of exporting `MESA_LOADER_DRIVER_OVERRIDE` or `LIBGL_ALWAYS_SOFTWARE` works, but they effectively disable OpenGL acceleration, leading to abysmally slow graph visualization.

**Comment by eduramiba** [comment] 2021-12-03 16:30
This will be fixed with the new visualization engine soon

**Comment by guibou** [comment] 2021-12-04 08:38
@eduramiba is there a way to test the new visualization engine? Merge request / branch?

**Comment by eduramiba** [comment] 2021-12-04 09:19
> @eduramiba is there a way to test the new visualization engine? Merge request / branch?

The viz-engine branch but It requires you to build snapshots of graphstore and viz-engine repositories.

**Comment by mgutierrezp** [comment] 2021-12-17 08:53
Hi there; any news on this? I'm still stuck with this issue. I tried several versions of java (1.8 and 1.11, basically) under win10. No error message at all but keeps on "initializing". Hopefully the new release will fix this. Thanks for your support!

**Comment by guibou** [comment] 2022-01-02 16:52
> > @eduramiba is there a way to test the new visualization engine? Merge request / branch?

Could you give me a bit of help in that task?

- I cloned the three repository (https://github.com/gephi/graphstore, https://github.com/gephi/gephi/, https://github.com/gephi/viz-engine), in `master` branch for each, except `viz-engine` for `gephi`.
-  `mvn -T4 clean install` in each. It fails only in `gephi` repository, complaining about no way to find the snapshot for `graphstore` and `vis-engine`.

I patched the `pom.xml` for `gephi` in such a way:

```diff
diff --git a/pom.xml b/pom.xml
index 8ecb337fe..9e4443611 100644
--- a/pom.xml
+++ b/pom.xml
@@ -416,6 +416,8 @@
                 <groupId>${project.groupId}</groupId>
                 <artifactId>graphstore</artifactId>
                 <version>${graphstore.version}</version>
+                <scope>system</scope>
+                <systemPath>/home/guillaume/.m2/repository/org/gephi/graphstore/0.6.1-SNAPSHOT/graphstore-0.6.1-SNAPSHOT.jar</systemPath>
             </dependency>
 
             <!-- Viz engine -->
@@ -423,6 +425,8 @@
                 <groupId>${project.groupId}</groupId>
                 <artifactId>viz-engine-core</artifactId>
                 <version>${gephi.viz-engine.version}</version>
+                <scope>system</scope>
+                <systemPath>/home/guillaume/.m2/repository/org/gephi/viz-engine-lwjgl-demo/1.0.0-SNAPSHOT/viz-engine-lwjgl-demo-1.0.0-SNAPSHOT.jar</systemPath>
             </dependency>
             <dependency>
                 <groupId>${project.groupId}</groupId>
```

As you guessed, `/home/guillaume` is my home repository. I guess the path to the `.jar` based on the output of `mvn -T4 clean install in both repositories.

Now it fails with a different error message:

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project visualization: Compilation failure: Compilation failure: 
[ERROR] /home/guillaume/srcs/gephi/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/VizEngineGraphCanvasManager.java:[14,27] error: cannot find symbol
[ERROR]   symbol:   class VizEngine
[ERROR]   location: package org.gephi.viz.engine
[ERROR] /home/guillaume/srcs/gephi/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/VizEngineGraphCanvasManager.java:[15,27] error: cannot find symbol
[ERROR]   symbol:   class VizEngineFactory
[ERROR]   location: package org.gephi.viz.engine
[ERROR] /home/guillaume/srcs/gephi/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/VizEngineGraphCanvasManager.java:[22,31] error: package org.gephi.viz.engine.spi does not exist
[ERROR] /home/guillaume/srcs/gephi/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/VizEngineGraphCanvasManager.java:[23,31] error: package org.gephi.viz.engine.spi does not exist
[ERROR] /home/guillaume/srcs/gephi/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/VizEngineGraphCanvasManager.java:[47,25] error: cannot find symbol
[ERROR]   symbol:   class WorldUpdaterExecutionMode
[ERROR]   location: class VizEngineGraphCanvasManager
....
```

Is the missing symbol because I did not checkout the correct branch for `vis-engine`?

(I'm totally noob with java build and tooling, I do apologize about that).

**Comment by eduramiba** [comment] 2022-01-03 11:14
Hi,
You should not use `scope` nor `systemPath`, just `mvn install` and the artifacts will be available in your local repository.

**Comment by guibou** [comment] 2022-01-03 18:36
> Hi, You should not use `scope` nor `systemPath`, just `mvn install` and the artifacts will be available in your local repository.

Thank you, I don't know why it was not working in the first place.

I was able to run gephi and indeed, OpenGL accelerated viewport are now working.

However I was not able to see label on edge or nodes, could you confirm that this is still not yet implemented, or again I missed something obvious ?

**Comment by eduramiba** [comment] 2022-01-04 10:05
@guibou Right, the labels are not yet implemented. Also self loops and selection animations are not implemented yet either.

**Comment by guibou** [comment] 2022-01-04 10:31
> @guibou Right, the labels are not yet implemented. Also self loops and selection animations are not implemented yet either.

Ok, that's annoying for my graph vizualisation needs ;) Good luck with the rest of the development.

**Comment by mbastian** [comment] 2022-03-01 19:50
This issue is a mixed bag of various issues in this thread, either related to Java or OpenGL. 

In the upcoming 0.9.3 release we're packaging the JRE (11) also on Linux so this should solve most of the Java issues unless you're on a different architecture than amd64 (we only offer an amd64 package at the moment). I would appreciate if you could try out the nightly build and let me know if the problem persist:
- [gephi-0.9.3-SNAPSHOT-linux.tar.gz](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.3-SNAPSHOT&c=linux&p=tar.gz) (Linux)

In addition, we also plan to offer [snapcraft package](https://snapcraft.io/gephi) to facilitate installation on Linux. You can already try it out. It's the same version as the nightly build at the moment. Again, let us know if you experience issues with it. In the meantime I'm closing this one.

**Closed by mbastian** 2022-03-01 19:50 UTC
Labels: To review, Java compatibility, Startup

**Comment by nanophilip** [comment] 2025-03-30 03:05
> Yes, I `export` on the command line (saved it to my `.bashrc` to load it every time I start my terminal) and start gephi from command line.
> 
> Do you have an "one way street sign" in the right bottom corner of your gephi window? If yes, there is an error. You must have some log output in `.gephi/0.9.2/dev/var/log`. Could you please post it here?
