### ISSUE TITLE
GEPHI does not start

### ISSUE THREAD

**Issue by lbordier** [gephi/gephi#1037] opened 2015-03-25 14:31 UTC
Environment: 
Windows 7 enterprise 64 bit service pack 1
Java 8 update 40 (64 bit)
Gephi 0.8.2

I see the very first windows "GEPHI 0.8.2 beta" with "loading cached objects". And then nothing happens. 

Am i missing anything?

**Comment by jessica-glover** [comment] 2015-03-25 20:36
I have the same problem on Mac OSX

**Comment by Tas-sos** [comment] 2015-03-28 11:26
Maybe if you install the **Java 7** correct your problem.

**Comment by artaman** [comment] 2015-03-30 07:15
Works just fine on OS X 10.9.5 w/o additional Sun JRE installation.

**Comment by eduramiba** [comment] 2015-08-26 16:04
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:04 UTC
