### ISSUE TITLE
Intel ICD OpenGL Driver erro

### ISSUE THREAD

**Issue by Kenriopelle** [gephi/gephi#1779] opened 2017-09-11 14:15 UTC
## Steps to Reproduce

1. Dowload Gephi and start on Windows 10 PC
![intel icd opengl driver](https://user-images.githubusercontent.com/7151200/30278939-c62bb25c-96d9-11e7-96c6-0d373a56bdfe.PNG)

2. Here are my settings:
Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_141; Java HotSpot(TM) Client VM 25.141-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_141-b15
System: Windows 10 version 10.0 running on x86; Cp1252; en_US (gephi)
User directory: C:\Users\riope\AppData\Roaming\.gephi\0.9.1\dev
Cache directory: C:\Users\riope\AppData\Roaming\.gephi\0.9.1\dev\var\cache

I updated my Firmware and graphics driver, rebooted, but still get the same error when Gephi starts.

4.

## Your Environment

Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_141; Java HotSpot(TM) Client VM 25.141-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_141-b15
System: Windows 10 version 10.0 running on x86; Cp1252; en_US (gephi)
User directory: C:\Users\riope\AppData\Roaming\.gephi\0.9.1\dev
Cache directory: C:\Users\riope\AppData\Roaming\.gephi\0.9.1\dev\var\cache

Any ideas how to fix?

Best,

Ken

Kenriopelle@me.com

**Comment by eduramiba** [comment] 2017-09-11 14:19
Can you test with latest 0.9.2 SNAPSHOT? https://github.com/gephi/gephi#nightly-builds

If still not working also try to use a JDK in case you use a JRE.

**Comment by Kenriopelle** [comment] 2017-09-11 14:25
Ok, will do!

Ken

**Comment by eduramiba** [comment] 2017-09-12 07:32
Did it work?

**Comment by eduramiba** [comment] 2017-09-12 07:33
Duplicate of #1724

**Closed by eduramiba** 2017-09-12 07:33 UTC
Labels: OpenGL

**Comment by Kenriopelle** [comment] 2017-09-12 11:47
Hi Eduardo,

Sorry for the delay, I was gone all day yesterday.

Yes, It works!

FYI.

I have Java 8 update 141 installed. Both 32 and 64 bit.

Thanks for your quick response and for the fix!!

Best,

Ken


On Sep 12, 2017, at 03:32 AM, Eduardo Ramos <notifications@github.com> wrote:

Did it work?

**Comment by Kenriopelle** [comment] 2017-09-12 12:00
Hi Eduardo,

FYI, I updated my Java JRE to Java 8 update 144 and it Gephi starts without any errors :-)


Again, thanks for your quick response, follow-up and fix!

Best,

Ken



On Sep 12, 2017, at 07:47 AM, KENNETH RIOPELLE <kenriopelle@me.com> wrote:

Hi Eduardo,

Sorry for the delay, I was gone all day yesterday.

Yes, It works!

FYI.

I have Java 8 update 141 installed. Both 32 and 64 bit.

Thanks for your quick response and for the fix!!

Best,

Ken


On Sep 12, 2017, at 03:32 AM, Eduardo Ramos <notifications@github.com> wrote:

Did it work?

**Comment by nube-colorada** [comment] 2017-10-24 16:45
Hi, I had the same issue. Then reinstalled Java and then Snapshot GEphi 0.9.3, and now "Cannot find Java 1.8 or higher" appears. I have Java SE Development Kit 9.0.1
I don't understand much and would very much apreciate any guidance.
Thanks!

**Comment by eduramiba** [comment] 2017-10-24 16:53
@nube-colorada try to install java 8 instead of 9

**Comment by nube-colorada** [comment] 2017-10-24 17:15
is there a specific java 8 to install?

**Comment by nube-colorada** [comment] 2017-10-24 17:21
Hi Eduardo, 
I now have: Version 8 Update 151; and same "Cannot find Java 1.8 or higher" appears.
Thanks

**Comment by eduramiba** [comment] 2017-10-24 17:25
@nube-colorada if your OS is 64 bit make sure ti install 64 bit Java too

**Comment by nube-colorada** [comment] 2017-10-24 18:08
Thank you, with a jdk java 8, it worked. Only a new issue remains: as it opens, it says: Open GL2 (1.1.0) is too low for showing graph. ¿How can I fix this?

**Comment by eduramiba** [comment] 2017-10-24 18:23
@nube-colorada What is your graphics card model? Make sure to install the latest drivers from your vendor website. It seems windows is using the default software renderer.

**Comment by nube-colorada** [comment] 2017-10-25 18:03
Eduardo,  
Thanks a lot for your helpful and quick responses! Gephy seems to be working now. 
:)
