### ISSUE TITLE
4,000,000 Node Graph Previews as a Square

### ISSUE THREAD

**Issue by TheGreatKetchup** [gephi/gephi#2147] opened 2019-10-30 03:37 UTC
I am trying to create a map using a very large dataset. 1.5M nodes and 7M edges (500MB).

The issue is if I run the random dispersion, or Force Atlas II, the viewer only shows a square output window.

![Screen Shot 2019-10-29 at 11 32 43 PM](https://user-images.githubusercontent.com/22862051/67827006-dcf2f000-faa4-11e9-92cc-74cd1a3560af.png)

* Version used: Gephi 0.9.2
* Java version: 1.8.0
* Operating System: Windows 10

**Comment by eduramiba** [comment] 2019-10-31 20:59
Duplicate of #1518

**Closed by eduramiba** 2019-10-31 20:59 UTC
