### ISSUE TITLE
Application will not open

### ISSUE THREAD

**Issue by smnuarmy** [gephi/gephi#944] opened 2014-08-27 12:50 UTC
I just downloaded Gephi and installed it on my macbook pro and the program will not open.  Any suggestions?  It appears in the application folder and I have tried restarting my system.  

Thanks

Scott

**Comment by jackiekazil** [comment] 2015-03-04 03:45
I had the same problem. I documented the solution here: https://medium.com/notes-from-computational-social-science/gephi-is-broken-on-mac-os-97fbaef4305e --- Let me know if that worked for you.

**Comment by eduramiba** [comment] 2015-08-26 16:58
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:58 UTC
