### ISSUE TITLE
Gephi Crashes on startup - no error message

### ISSUE THREAD

**Issue by giorgioroffo** [gephi/gephi#1090] opened 2015-08-09 12:23 UTC
Hi,

I want to contributte to Gephi, but I can't use it because of crashes on startup.

it seems is a problm related to Java, see: https://forum.gephi.org/viewtopic.php?f=4&t=3595

Are you going to fix it?

I'm trying to downgrade java to 6,

thank you,

giorgio

**Comment by eduramiba** [comment] 2015-08-26 15:54
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:54 UTC
