### ISSUE TITLE
gephi

### ISSUE THREAD

**Issue by apramrajsengundar** [gephi/gephi#1128] opened 2015-09-15 19:55 UTC
coudn install gephi in mac - yosemite.

**Comment by eduramiba** [comment] 2015-09-15 19:56
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac

**Closed by eduramiba** 2015-09-15 19:56 UTC
