### ISSUE TITLE
Feature Request: Node Shape

### ISSUE THREAD

**Issue by mcadamsg** [gephi/gephi#1686] opened 2017-03-08 17:36 UTC
I need to change node shape for social network visualizations, as currently there are only 2 ways to differentiate nodes - size and color.

Is it possible to implement this through a plug-in?

## Environment

* Version used: Gephi 0.9.1

**Comment by eduramiba** [comment] 2017-03-08 17:56
Closing as duplicate of #1291

**Closed by eduramiba** 2017-03-08 17:56 UTC

**Comment by lparks87** [comment] 2021-05-04 00:46
In order to change the shape of the node, you can add the polygon node shape plugin. Then go into preview and select manage renderers on the left-hand side and enable polygon-shaped nodes and put the priority at the top. Then go into your data laboratory and create a new column named Polygon with an Integer data type. Then whatever value you place in that column will determine how many sides there are. For instance, a value of 3 for node 4 will make node 4 a triangle and a value of 4 for node 8 will make it a square. Hope this helps.
