### ISSUE TITLE
Gephi not open in Windows 7 Enterprise 64

### ISSUE THREAD

**Issue by sagazluiz** [gephi/gephi#1077] opened 2015-07-13 01:09 UTC
MY SISTEM
I´m use a Windows 7 Enterprise Edition 64 bits

MY PROBLEM
I have installed the Gephi but it is not working. It starts to initialize but closes suddenly. 

MY LOG
Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\r337555>C:\Program Files (x86)\Gephi-0.8.2\bin
'C:\Program' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\r337555> cd "C:\Program Files (x86)\Gephi-0.8.2\bin

C:\Program Files (x86)\Gephi-0.8.2\bin>Gephi64.exe

The launcher has determined that the parent process has a console and will reuse
 it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.

C:\Program Files (x86)\Gephi-0.8.2\bin>gephi.exe

C:\Program Files (x86)\Gephi-0.8.2\bin>

The launcher has determined that the parent process has a console and will reuse
 it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.

**Comment by songjinghe** [comment] 2015-07-24 02:56
checkout these instructions:
https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Comment by eduramiba** [comment] 2015-08-26 15:54
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 15:54 UTC
