### ISSUE TITLE
Running on JDK 1.7.0_11 causes gephi to crash when opening a file

### ISSUE THREAD

**Issue by andykitchen** [gephi/gephi#744] opened 2013-02-14 06:18 UTC
Newest JDK causes gephi to hang when opening a file, making it
unfortunately unusable.

Problem occurred after I installed newest oracle JDK:
```
$ java -version
java version "1.7.0_11"
Java(TM) SE Runtime Environment (build 1.7.0_11-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.6-b04, mixed mode)
```

Forcing gephi to use Apple Java 1.6 makes it work again:
```
java version "1.6.0_37"
Java(TM) SE Runtime Environment (build 1.6.0_37-b06-434-11M3909)
Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01-434, mixed mode)
```

**Comment by eduramiba** [comment] 2015-08-26 17:13
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:13 UTC
