### ISSUE TITLE
Gephi crashes on startup

### ISSUE THREAD

**Issue by soumenganguly** [gephi/gephi#1535] opened 2016-07-08 10:15 UTC
Hi,

I suppose this is a common issue, as it was also listed on Gephi's homepage.
I am running Linux(Fedora, with OpenGL support) and I've been able to reproduce this bug in other linux machines as well, though it runs fine on Windows and OSX. 

 When I try to open a CSV file in Gephi, it crashes with a JVM error. The Network file is fairly small(~1200 nodes) and I do not get the segmentation fault it encounters while dealing with a fairly small list. 

I have attached the log file.
Thanks for your time, I hope it would get resolved quickly.
[hs_err_pid7557.txt](https://github.com/gephi/gephi/files/353970/hs_err_pid7557.txt)

**Comment by eduramiba** [comment] 2016-07-08 10:42
Are you able to succesfully open a sample graph (les miserables for example)?

**Comment by eduramiba** [comment] 2016-07-08 10:43
If not, try the workaround at https://github.com/gephi/gephi/issues/1442

**Comment by soumenganguly** [comment] 2016-07-08 20:02
Hi eduramiba,
I tried to load graphs before but it failed. However, executing Gephi with the following:
LIBGL_ALWAYS_SOFTWARE=1 
fixes the issue. Do you know why this might be happening? I would love to make a PR, if this is a special case and not yet fixed.

**Comment by eduramiba** [comment] 2016-07-08 20:46
Hi,
Then closing as duplicate of #1442 / #1064 

This happens due to defective graphic card drivers (very common on linux unfortunately), so forcing software rendering (not using the graphics card) fixes it. Software rendering is much slower though.

Sometimes you might be able to fix it by upgrading / changing the driver, but be careful not to leave your system unusable.

**Closed by eduramiba** 2016-07-08 20:46 UTC
