### ISSUE TITLE
Gephi won't read my OneDrive and Folders

### ISSUE THREAD

**Issue by Wigzart** [gephi/gephi#2468] opened 2022-04-09 05:18 UTC
I upgraded to the latest version of Gephi yesterday on my MacBook Air M1. When I tried to import the .csv from my OneDrive, I found that Gephi cannot access anything within the drive - that happened also with other folders. That said, Gephi can only read so far from the main "Users" folder. 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/90691162/162557601-830d7caa-2598-4bde-acde-4a907a1c1161.png">

**Comment by mbastian** [comment] 2022-04-11 17:42
Closing as a duplicate of #2467

**Closed by mbastian** 2022-04-11 17:42 UTC
