### ISSUE TITLE
Problems starting the application

### ISSUE THREAD

**Issue by athinaeos** [gephi/gephi#1137] opened 2015-09-28 07:29 UTC
I have followed the instructions and downloaded the application, but it does not start. I run Windows 8 and Java 8.
Could you please help me?

Thank you

**Comment by eduramiba** [comment] 2015-09-28 18:50
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-09-28 18:50 UTC
