### ISSUE TITLE
Will not install on Mavericks 

### ISSUE THREAD

**Issue by jbokunewicz** [gephi/gephi#897] opened 2014-03-10 18:58 UTC
Hello, I am a professor at Stockton College and I am hoping to use GEPHI in my class.  I have tried to download it several times but when I click on the download the Icon appears for GEPHI but when I click on it, it just blinks.  Do you have any suggestions on how I can correct this?

**Comment by eduramiba** [comment] 2015-08-26 17:04
Possible duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 17:04 UTC
