### ISSUE TITLE
gephi won't load

### ISSUE THREAD

**Issue by elevine89** [gephi/gephi#1110] opened 2015-08-30 15:40 UTC
Good morning,

I downloaded the appropriate version of Gephi for my computer (it runs on Windows 7) and it hasn't been loading itself up after I've clicked the shortcut on my desktop.  What can I do to resolve this problem so I can start on my research?

Thank you!

-Eli

**Comment by eduramiba** [comment] 2015-08-30 17:35
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-30 17:35 UTC
