### ISSUE TITLE
Gephi doesn't work on Win8 with jre-8u45-windows-x64

### ISSUE THREAD

**Issue by aucu** [gephi/gephi#1051] opened 2015-05-08 08:02 UTC
My PC is win8 64bit, when setup gephi-0.8.2-beta version, it can not  be started, could you help to solve this problem? Or could you give me some suggestions to run it normally?
I need to use gephi in data analysis and visualization.
Thanks a lot.

Best,
aucu

**Comment by withforesight** [comment] 2015-05-12 17:33
had the same problem (on Windows 8.1 32-bit, Java 8 (jre1.8.0_31)
What worked for me was downloading the snapshot version from here:
https://github.com/gephi/gephi (under Nightly Builds)

hth

**Comment by aucu** [comment] 2015-05-14 09:14
Thanks for your suggestion, it's ok now.
Best,

Lee

2015-05-13 1:33 GMT+08:00 Mike Behar <notifications@github.com>:

> had the same problem (on Windows 8.1 32-bit, Java 8 (jre1.8.0_31)
> What worked for me was downloading the snapshot version from here:
> https://github.com/gephi/gephi (under Nightly Builds)
>
> hth
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gephi/gephi/issues/1051#issuecomment-101360055>.
>



-- 

Jintong Li
Ph.D.
Department of International Relations
Zhou Enlai School of Government
Nankai University,Tianjin,China

**Comment by eduramiba** [comment] 2015-08-26 16:03
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Closed by eduramiba** 2015-08-26 16:03 UTC

**Comment by aucu** [comment] 2015-08-27 20:39
Thanks for your advice.

Best regards.

2015-08-26 12:03 GMT-04:00 Eduardo Ramos <notifications@github.com>:

> Duplicate of #748 <https://github.com/gephi/gephi/issues/748>
>
> Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
> It's due to problems with old JOGL version and is going to be updated in
> next version.
>
> Please check
> https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help
> about running Gephi with Java 6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gephi/gephi/issues/1051#issuecomment-135080202>.
>



-- 

Jintong Li
Ph.D.
Department of International Relations
Zhou Enlai School of Government
Nankai University,Tianjin,China
