### ISSUE TITLE
Version 0.9.2

### ISSUE THREAD

**Issue by fcfilho** [gephi/gephi#1837] opened 2017-11-10 13:40 UTC
## Expected Behavior
update vizualization lables

## Current Behavior
Doesn't update vizualization lables

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment] 2017-11-10 13:44
Can you be more specific please? What section of Gephi and what you try to do

**Comment by 2fc** [comment] 2017-11-10 14:19
ok,
First think, thank you for reply.

On OVERVIEW I do my graph with some labels properly and I can see it on
PREVIEW properly as well.
If a change the labels or add others one on OVERVIEW it works good, but
when I Update the PREVIEW it doesn't happens.

Thanks


_____________________
Fernando C. Filho
http://lattes.cnpq.br/0664332338000165

2017-11-10 11:44 GMT-02:00 Eduardo Ramos <notifications@github.com>:

**Comment by wetneb** [comment] 2021-12-02 12:12
Closing as duplicate of #1735.

**Closed by wetneb** 2021-12-02 12:12 UTC
